# Run AUCell on in vivo GRN

In [2]:
import dill
import scanpy as sc
import os
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import pyranges
# Set stderr to null to avoid strange messages from ray
import sys
_stderr = sys.stderr
null = open(os.devnull,'wb')
work_dir = '/rds/project/rds-SDzz0CATGms/users/bt392/09_Eomes_invitro_blood/results/revisions/05_SCENICplus/SCENICplus/'
projDir = work_dir
tmp_dir = '/home/bt392/ry/'

In [3]:
adata = sc.read_mtx(projDir + 'rna.mtx') # need to check if this is not transposed the wrong way
adata = adata.T
cluster_metadata = pd.read_csv(projDir + 'meta_scenic.txt')
genes = pd.read_csv(projDir + 'genes.txt', sep = ' ')

cluster_metadata = cluster_metadata.set_index('cell')
genes = genes.set_index('x')

adata.obs = cluster_metadata
adata.var = genes

In [5]:
eRegulon_metadata_filtered = pd.read_csv(os.path.join('/rds/project/rds-SDzz0CATGms/users/bt392/09_Eomes_invitro_blood/results/multiome_atlas/SCENICplus_sc/scenicplus/eRegulon_metadata_filtered.csv'))

In [56]:
region_ranking = dill.load(open(os.path.join('/rds/project/rds-SDzz0CATGms/users/bt392/09_Eomes_invitro_blood/results/multiome_atlas/SCENICplus_sc/scenicplus/region_ranking.pkl'), 'rb')) #load ranking calculated using the wrapper function
gene_ranking = dill.load(open(os.path.join('/rds/project/rds-SDzz0CATGms/users/bt392/09_Eomes_invitro_blood/results/multiome_atlas/SCENICplus_sc/scenicplus/gene_ranking.pkl'), 'rb')) #load ranking calculated using the wrapper function

In [13]:
from pyscenic.aucell import aucell

In [14]:
aucell(

<function pyscenic.aucell.aucell(exp_mtx: pandas.core.frame.DataFrame, signatures: Sequence[Type[ctxcore.genesig.GeneSignature]], auc_threshold: float = 0.05, noweights: bool = False, normalize: bool = False, seed=None, num_workers: int = 112) -> pandas.core.frame.DataFrame>

In [20]:
adata.X

<19740x32285 sparse matrix of type '<class 'numpy.float32'>'
	with 85191781 stored elements in Compressed Sparse Row format>

In [23]:
cluster_metadata

,barcode,sample,nFeature_RNA,nCount_RNA,mitochondrial_percent_RNA,ribosomal_percent_RNA,alias,day,genotype,replicate,...,stage.mapped_mnn,cellstage.score_mnn,closest.cell_mnn,celltype_genotype,celltype_extended_genotype,UMAP1,UMAP2,mofa_cluster,celltype_v1,celltype_v2
cell,,,,,,,,,,,,,,,,,,,,,
1A_Eo_DEG_G9_day3#AAACAGCCAGCAAGAT-1,AAACAGCCAGCAAGAT-1,1A_Eo_DEG_G9_day3,6110,22923,6.09,10.15,day3_WT_rep1,D3,WT,rep1,...,E7.25,0.56,cell_29706,Epiblast-WT,Epiblast-WT,-6.742873,-4.051344,7,Primitive_Streak,Primitive_Streak
1A_Eo_DEG_G9_day3#AAACAGCCAGCACCAT-1,AAACAGCCAGCACCAT-1,1A_Eo_DEG_G9_day3,4201,10794,6.57,7.38,day3_WT_rep1,D3,WT,rep1,...,E7.0,0.44,cell_79342,Primitive_Streak-WT,Primitive_Streak-WT,-5.456130,-2.490946,2,Primitive_Streak,Primitive_Streak
1A_Eo_DEG_G9_day3#AAACATGCAAGTAAGC-1,AAACATGCAAGTAAGC-1,1A_Eo_DEG_G9_day3,3659,8745,5.74,11.92,day3_WT_rep1,D3,WT,rep1,...,E7.25,0.56,cell_41792,Epiblast-WT,Epiblast-WT,-6.348085,-4.264254,7,Primitive_Streak,Primitive_Streak
1A_Eo_DEG_G9_day3#AAACATGCAATATACC-1,AAACATGCAATATACC-1,1A_Eo_DEG_G9_day3,3640,8461,3.70,7.21,day3_WT_rep1,D3,WT,rep1,...,E7.25,0.60,cell_5664,Primitive_Streak-WT,Primitive_Streak-WT,-6.044776,-2.846936,2,Primitive_Streak,Primitive_Streak
1A_Eo_DEG_G9_day3#AAACATGCAATCCTGA-1,AAACATGCAATCCTGA-1,1A_Eo_DEG_G9_day3,3632,8276,4.60,8.16,day3_WT_rep1,D3,WT,rep1,...,E7.25,0.80,cell_81702,Primitive_Streak-WT,Primitive_Streak-WT,-4.960897,-3.201840,11,Primitive_Streak,Primitive_Streak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rv_eo_deg_day4_control#TTTGCATTCAGCAAGA-1,TTTGCATTCAGCAAGA-1,rv_eo_deg_day4_control,5990,24358,5.47,12.61,day4_WT_rep1,D4,WT,rep1,...,E7.25,0.28,cell_78069,ExE_mesoderm-WT,Lateral_plate_mesoderm-WT,3.014189,2.176409,5,Mesenchyme,Mesenchyme
rv_eo_deg_day4_control#TTTGCATTCCACAATA-1,TTTGCATTCCACAATA-1,rv_eo_deg_day4_control,6378,26312,7.59,13.26,day4_WT_rep1,D4,WT,rep1,...,E7.25,0.56,cell_79899,Mixed_mesoderm-WT,Lateral_plate_mesoderm-WT,5.654938,0.157417,3,HE,HE
rv_eo_deg_day4_control#TTTGCATTCGCTAGAT-1,TTTGCATTCGCTAGAT-1,rv_eo_deg_day4_control,6716,36065,10.15,10.62,day4_WT_rep1,D4,WT,rep1,...,E7.25,0.36,cell_18590,Haematoendothelial_progenitors-WT,Haematoendothelial_progenitors-WT,5.910633,0.031369,3,HE,HE
rv_eo_deg_day4_control#TTTGTGGCATCCCTCA-1,TTTGTGGCATCCCTCA-1,rv_eo_deg_day4_control,6497,28115,10.61,11.25,day4_WT_rep1,D4,WT,rep1,...,E7.5,0.44,cell_50043,Surface_ectoderm-WT,Non-neural_ectoderm-WT,-6.383644,-2.312773,2,Primitive_Streak,Primitive_Streak
rv_eo_deg_day4_control#TTTGTGTTCCTGAATA-1,TTTGTGTTCCTGAATA-1,rv_eo_deg_day4_control,6383,32341,8.32,10.14,day4_WT_rep1,D4,WT,rep1,...,E7.75,0.48,cell_21009,Blood_progenitors_1-WT,Haematoendothelial_progenitors-WT,6.935485,-0.070283,3,HE,HE

Index(['Xkr4', 'Gm1992', 'Gm19938', 'Gm37381', 'Rp1', 'Sox17', 'Gm37587',
       'Gm37323', 'Mrpl15', 'Lypla1',
       ...
       'Gm16367', 'AC163611.1', 'AC163611.2', 'AC140365.1', 'AC124606.2',
       'AC124606.1', 'AC133095.2', 'AC133095.1', 'AC234645.1', 'AC149090.1'],
      dtype='object', name='x', length=32285)

In [52]:
df = pd.DataFrame(adata.X.toarray())
df.index = cluster_metadata.index
df.columns = genes.index

In [53]:
df

x,Xkr4,Gm1992,Gm19938,Gm37381,Rp1,Sox17,Gm37587,Gm37323,Mrpl15,Lypla1,...,Gm16367,AC163611.1,AC163611.2,AC140365.1,AC124606.2,AC124606.1,AC133095.2,AC133095.1,AC234645.1,AC149090.1
cell,,,,,,,,,,,,,,,,,,,,,
1A_Eo_DEG_G9_day3#AAACAGCCAGCAAGAT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1A_Eo_DEG_G9_day3#AAACAGCCAGCACCAT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1A_Eo_DEG_G9_day3#AAACATGCAAGTAAGC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
1A_Eo_DEG_G9_day3#AAACATGCAATATACC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
1A_Eo_DEG_G9_day3#AAACATGCAATCCTGA-1,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rv_eo_deg_day4_control#TTTGCATTCAGCAAGA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
rv_eo_deg_day4_control#TTTGCATTCCACAATA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rv_eo_deg_day4_control#TTTGCATTCGCTAGAT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
rv_eo_deg_day4_control#TTTGTGGCATCCCTCA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
rv_eo_deg_day4_control#TTTGTGTTCCTGAATA-1,8.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0

In [54]:
test = aucell(exp_mtx = df,
      signatures = {'Tbx4': ['Eomes', 'Lhx1']})

Process Process-1:
Traceback (most recent call last):
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pyscenic/aucell.py", line 85, in _enrichment
    result_mtx[offset + (idx * inc) : offset + ((idx + 1) * inc)] = enrichment4cells(
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/site-packages/ctxcore/recovery.py", line 147, in enrichment4cells
    list(zip(rnk_mtx.index.values, repeat(regulon.name))), names=["Cell", "Regulon"]
AttributeError: 'str' object has no attribute 'name'

AttributeError: 'str' object has no attribute 'name'

In [55]:
test = aucell(exp_mtx = df,
      signatures = ['Eomes', 'Lhx1'])

Process Process-2:
Traceback (most recent call last):
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Process Process-3:
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pyscenic/aucell.py", line 85, in _enrichment
    result_mtx[offset + (idx * inc) : offset + ((idx + 1) * inc)] = enrichment4cells(
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/site-packages/ctxcore/recovery.py", line 147, in enrichment4cells
    list(zip(rnk_mtx.index.values, repeat(regulon.name))), names=["Cell", "Regulon"]
AttributeError: 'str' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pyscenic/aucell.py", line 85, in _enrichment
    result_mtx[offset + (idx * inc) : offset + ((idx + 1) * inc)] = enrichment4cells(
  File "/home/bt392/miniconda3/envs/scenicplus/lib/python3.8/site-packages/ctxcore/recovery.py", line 147, in enrichment4cells
    list(zip(rnk_mtx.index.values, repeat(regulon.name))), names=["Cell", "Regulon"]
AttributeError: 'str' object has no attribute 'name'

AttributeError: 'str' object has no attribute 'name'

In [ ]:
from ctxcore.genesig import GeneSignature

In [ ]:
df

In [84]:
test = aucell(exp_mtx = df,
      signatures = GeneSignature(name = 'Tbx4', gene2weight = {'Eomes': 1, 'Lhx1': 1}))

KeyError: 0

In [ ]:
test

In [ ]:
from pyscenic.aucell import aucell, derive_auc_threshold, create_rankings

GeneSignature(name='Tbx4', gene2weight=frozendict.frozendict({'Eomes': 0.5, 'Lhx1': 0.1}))

In [ ]:
percentiles = derive_auc_threshold(df)
percentiles

0.01    0.079294
0.05    0.085828
0.10    0.091869
0.50    0.130866
1.00    0.292272
dtype: float64

In [69]:
from pyscenic.genesig import GeneSignature

ModuleNotFoundError: No module named 'pyscenic.genesig'