In [1]:
suppressPackageStartupMessages({
    library(data.table)
    library(tidyr)
    library(ArchR)
    })

# I/O

basedir = '/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/genome/10x_rabbit_ref/'

## Explanation of new genome creation at end

In [6]:
genes = fread(paste0(basedir, 'genes.gtf'))
ensoc_genes = fread(paste0(basedir, 'ensoc_genes.csv'))$V2[-1]

Warning message in fread(paste0(basedir, "genes.gtf")):
“Detected 1 column names but the data has 9 columns (i.e. invalid file). Added 8 extra default column names at the end.”

In [37]:
length(ensoc_genes)

[1] 9779

In [13]:
genes = genes[genes$V3 == 'gene', ]

In [7]:
colnames(genes) = paste0('V', 1:9)

In [8]:
chr = c(1:22, 'X')

In [15]:
genes_chr = genes[genes$V1 %in% chr]
genes_nonchr = genes[!genes$V1 %in% chr]

In [90]:
nrow(genes_chr)
nrow(genes_nonchr)

[1] 15033

[1] 5579

In [32]:
class(paste(ensoc_genes,collapse="|"))

[1] "character"

In [79]:
genes_chr$V9 = sapply(strsplit(genes_chr$V9,";"), `[`, 1)
genes_chr$V9 = sapply(strsplit(genes_chr$V9,"\""), `[`, 2)

In [53]:
nrow(genes_chr[grep(paste(ensoc_genes[1:2000],collapse="|"), genes_chr$V9)])
nrow(genes_chr[grep(paste(ensoc_genes[2001:4000],collapse="|"), genes_chr$V9)])
nrow(genes_chr[grep(paste(ensoc_genes[4001:6000],collapse="|"), genes_chr$V9)])
nrow(genes_chr[grep(paste(ensoc_genes[6001:8000],collapse="|"), genes_chr$V9)])
nrow(genes_chr[grep(paste(ensoc_genes[8001:10000],collapse="|"), genes_chr$V9)])

[1] 1119

[1] 1125

[1] 972

[1] 1019

[1] 1041

In [ ]:
#= 5276 genes known and on normal chr
# thus 4503 not know

In [54]:
nrow(genes_nonchr[grep(paste(ensoc_genes[1:2000],collapse="|"), genes_nonchr$V9)])
nrow(genes_nonchr[grep(paste(ensoc_genes[2001:4000],collapse="|"), genes_nonchr$V9)])
nrow(genes_nonchr[grep(paste(ensoc_genes[4001:6000],collapse="|"), genes_nonchr$V9)])
nrow(genes_nonchr[grep(paste(ensoc_genes[6001:8000],collapse="|"), genes_nonchr$V9)])
nrow(genes_nonchr[grep(paste(ensoc_genes[8001:10000],collapse="|"), genes_nonchr$V9)])
# 71 genes that are annotated on other chr?

[1] 0

[1] 0

[1] 0

[1] 0

[1] 71

In [55]:
genes_nonchr[grep(paste(ensoc_genes[8001:10000],collapse="|"), genes_nonchr$V9)]
# Also actual genes

   V1           V2      V3   V4       V5       V6 V7 V8
1  GL018699     ensembl gene 13251374 13298273 .  +  .
2  GL018701     ensembl gene  5906330  5945139 .  -  .
3  GL018702     ensembl gene   599062   702322 .  -  .
4  GL018704     ensembl gene   908983   915505 .  -  .
5  GL018704     ensembl gene  5978447  5991901 .  -  .
6  GL018704     ensembl gene  6002620  6053473 .  -  .
7  GL018704     ensembl gene  6552108  6565212 .  -  .
8  GL018705     ensembl gene  3365033  3454172 .  -  .
9  GL018705     ensembl gene  4618009  4705274 .  +  .
10 GL018706     ensembl gene   278548   324782 .  -  .
11 GL018706     ensembl gene   628132   640671 .  +  .
12 GL018714     ensembl gene   250909   256179 .  +  .
13 GL018717     ensembl gene    10951    25490 .  -  .
14 GL018723     ensembl gene  2759156  2778284 .  -  .
15 GL018729     ensembl gene   116812   193307 .  +  .
16 GL018729     ensembl gene   306867   308870 .  -  .
17 GL018734     ensembl gene   528463   541344 .  +  .
18 GL018734     ensembl gene  1544571  1545500 .  +  .
19 GL018741     ensembl gene   540557   544125 .  +  .
20 GL018743     ensembl gene   980005   996519 .  +  .
21 GL018746     ensembl gene   600715   690300 .  +  .
22 GL018746     ensembl gene   873887   917475 .  +  .
23 GL018746     ensembl gene   917333   934847 .  -  .
24 GL018755     ensembl gene   265663   315601 .  +  .
25 GL018760     ensembl gene   989727  1058650 .  +  .
26 GL018765     ensembl gene   904468   905151 .  +  .
27 GL018767     ensembl gene   656884   660046 .  -  .
28 GL018771     ensembl gene    98061   217390 .  -  .
29 GL018779     ensembl gene   269313   269447 .  +  .
30 GL018788     ensembl gene   892427   931604 .  -  .
⋮  ⋮            ⋮       ⋮    ⋮        ⋮        ⋮  ⋮  ⋮
42 GL018843     ensembl gene 274364   276438   .  -  .
43 GL018847     ensembl gene 517965   520748   .  +  .
44 GL018847     ensembl gene 610108   619369   .  +  .
45 GL018847     ensembl gene 621000   638248   .  +  .
46 GL018846     ensembl gene  13378    61735   .  +  .
47 GL018866     ensembl gene  48042    72863   .  +  .
48 GL018867     ensembl gene  50466   250738   .  -  .
49 GL018883     ensembl gene 274093   429575   .  -  .
50 GL018883     ensembl gene 333216   402290   .  -  .
51 GL018883     ensembl gene 388016   441017   .  -  .
52 GL018883     ensembl gene 454683   467146   .  -  .
53 GL018909     ensembl gene  10673    20141   .  +  .
54 GL018908     ensembl gene 274399   293134   .  +  .
55 GL018940     ensembl gene  12897    17725   .  -  .
56 GL018984     ensembl gene 140568   258334   .  -  .
57 GL018968     ensembl gene  10146    11627   .  +  .
58 GL019028     ensembl gene  38376    43059   .  +  .
59 GL019027     ensembl gene  41865    46927   .  -  .
60 GL019084     ensembl gene  82989   101863   .  +  .
61 GL019144     ensembl gene  47610   131648   .  -  .
62 GL019167     ensembl gene  42729   134557   .  -  .
63 GL019171     ensembl gene  10771    55534   .  -  .
64 GL019206     ensembl gene    200    35881   .  -  .
65 GL019367     ensembl gene  43205    58714   .  +  .
66 GL019424     ensembl gene      2     1516   .  +  .
67 GL019596     ensembl gene    444     3771   .  -  .
68 GL019601     ensembl gene  14748    17210   .  +  .
69 GL019670     ensembl gene  15126    25968   .  +  .
70 GL019774     ensembl gene    298     8135   .  -  .
71 AAGW02082198 ensembl gene   2181     5928   .  +  .
   V9
1  gene_id "ENSOCUG00000004630"; gene_version "4"; gene_name "AKNA"; gene_source "ensembl"; gene_biotype "protein_coding";
2  gene_id "ENSOCUG00000000485"; gene_version "4"; gene_name "NAF1"; gene_source "ensembl"; gene_biotype "protein_coding";
3  gene_id "ENSOCUG00000003387"; gene_version "4"; gene_name "KATNAL1"; gene_source "ensembl"; gene_biotype "protein_coding";
4  gene_id "ENSOCUG00000010871"; gene_version "3"; gene_name "DNALI1"; gene_source "ensembl"; gene_biotype "protein_coding";
5  gene_id "ENSOCUG00000007530"; gene_version "4"; gene_name "TXLNA"; gene_source "ensembl"; gene_biotype "protein_coding";
6  gene_id "ENSOCUG00000017669"; gene_version "3"; gene_name "KPNA6"; gene_source "ensembl"; gene_biotype "protein_coding";
7  gene_id "ENSOCUG00000023359"; gene_version "3"; gene_name "TINAGL1"; gene_source "ensembl"; gene_biotype "protein_coding";
8  gene_id "ENSOCUG00000006781"; gene_version "4"; gene_name "KPNA3"; gene_source "ensembl"; gene_biotype "protein_coding";
9  gene_id "ENSOCUG00000008904"; gene_version "4"; gene_name "RNASEH2B"; gene_source "ensembl"; gene_biotype "protein_coding";
10 gene_id "ENSOCUG00000008094"; gene_version "3"; gene_name "HGSNAT"; gene_source "ensembl"; gene_biotype "protein_coding";
11 gene_id "ENSOCUG00000009516"; gene_version "4"; gene_name "CHRNA6"; gene_source "ensembl"; gene_biotype "protein_coding";
12 gene_id "ENSOCUG00000024399"; gene_version "2"; gene_name "NAB2"; gene_source "ensembl"; gene_biotype "protein_coding";
13 gene_id "ENSOCUG00000016577"; gene_version "3"; gene_name "NAA40"; gene_source "ensembl"; gene_biotype "protein_coding";
14 gene_id "ENSOCUG00000004122"; gene_version "3"; gene_name "NIPSNAP1"; gene_source "ensembl"; gene_biotype "protein_coding";
15 gene_id "ENSOCUG00000014888"; gene_version "4"; gene_name "IFNAR1"; gene_source "ensembl"; gene_biotype "protein_coding";
16 gene_id "ENSOCUG00000003853"; gene_version "3"; gene_name "DNAJC28"; gene_source "ensembl"; gene_biotype "protein_coding";
17 gene_id "ENSOCUG00000006739"; gene_version "3"; gene_name "NAGA"; gene_source "ensembl"; gene_biotype "protein_coding";
18 gene_id "ENSOCUG00000009651"; gene_version "1"; gene_name "DNAJB7"; gene_source "ensembl"; gene_biotype "protein_coding";
19 gene_id "ENSOCUG00000002927"; gene_version "3"; gene_name "NANP"; gene_source "ensembl"; gene_biotype "protein_coding";
20 gene_id "ENSOCUG00000004839"; gene_version "4"; gene_name "DNAJA2"; gene_source "ensembl"; gene_biotype "protein_coding";
21 gene_id "ENSOCUG00000000228"; gene_version "3"; gene_name "DNAJA4"; gene_source "ensembl"; gene_biotype "protein_coding";
22 gene_id "ENSOCUG00000006114"; gene_version "4"; gene_name "CHRNA5"; gene_source "ensembl"; gene_biotype "protein_coding";
23 gene_id "ENSOCUG00000005023"; gene_version "4"; gene_name "CHRNA3"; gene_source "ensembl"; gene_biotype "protein_coding";
24 gene_id "ENSOCUG00000017968"; gene_version "4"; gene_name "GNAS"; gene_source "ensembl"; gene_biotype "protein_coding";
25 gene_id "ENSOCUG00000001792"; gene_version "4"; gene_name "KPNA7"; gene_source "ensembl"; gene_biotype "protein_coding";
26 gene_id "ENSOCUG00000017294"; gene_version "3"; gene_name "DNAJC30"; gene_source "ensembl"; gene_biotype "protein_coding";
27 gene_id "ENSOCUG00000027536"; gene_version "3"; gene_name "SNAPC2"; gene_source "ensembl"; gene_biotype "protein_coding";
28 gene_id "ENSOCUG00000000587"; gene_version "4"; gene_name "DNAJC13"; gene_source "ensembl"; gene_biotype "protein_coding";
29 gene_id "ENSOCUG00000039418"; gene_version "1"; gene_name "TUNAR"; gene_source "ensembl"; gene_biotype "protein_coding";
30 gene_id "ENSOCUG00000001768"; gene_version "4"; gene_name "NIPSNAP2"; gene_source "ensembl"; gene_biotype "protein_coding";
⋮  ⋮
42 gene_id "ENSOCUG00000014534"; gene_version "4"; gene_name "AANAT"; gene_source "ensembl"; gene_biotype "protein_coding";
43 gene_id "ENSOCUG00000013385"; gene_version "2"; gene_name "NAIF1"; gene_source "ensembl"; gene_biotype "protein_coding";
44 gene_id "ENSOCUG00000020994"; gene_version "2"; gene_name "ST6GALNAC4"; gene_source "ensembl"; gene_biotype "protein_coding";
45 gene_id "ENSOCUG00000026208"; gene_version "2"; gene_name "ST6GALNAC6"; gene_source "ensembl"; gene_biotype "protein_coding";
46 gene_id "ENSOCUG00000014187"; gene_version "4"; gene_name "MINAR1"; gene_source "ensembl"; gene_biotype "protein_coding";
47 gene_id "ENSOCUG00000024065"; gene_version "3"; gene_name "NARF"; gene_source "ensembl"; gene_biotype "protein_coding";
48 gene_id "ENSOCUG00000012674"; gene_version "4"; gene_name "CACNA1B"; gene_source "ensembl"; gene_biotype "protein_coding";
49 gene_id "ENSOCUG00000016318"; gene_version "4"; gene_name "SERPINA6"; gene_source "ensembl"; gene_biotype "protein_coding";
50 gene_id "ENSOCUG00000026257"; gene_version "2"; gene_name "SERPINA1"; gene_source "ensembl"; gene_biotype "protein_coding";
51 gene_id "ENSOCUG00000029657"; gene_version "2"; gene_name "SERPINA9"; gene_source "ensembl"; gene_biotype "protein_coding";
52 gene_id "ENSOCUG00000017143"; gene_version "4"; gene_name "SERPINA12"; gene_source "ensembl"; gene_biotype "protein_coding";
53 gene_id "ENSOCUG00000026273"; gene_version "3"; gene_name "SERPINA3"; gene_source "ensembl"; gene_biotype "protein_coding";
54 gene_id "ENSOCUG00000009400"; gene_version "4"; gene_name "DNAI2"; gene_source "ensembl"; gene_biotype "protein_coding";
55 gene_id "ENSOCUG00000005422"; gene_version "3"; gene_name "SNAI1"; gene_source "ensembl"; gene_biotype "protein_coding";
56 gene_id "ENSOCUG00000011985"; gene_version "4"; gene_name "CACNA1A"; gene_source "ensembl"; gene_biotype "protein_coding";
57 gene_id "ENSOCUG00000026883"; gene_version "2"; gene_name "DNASE1L2"; gene_source "ensembl"; gene_biotype "protein_coding";
58 gene_id "ENSOCUG00000022132"; gene_version "2"; gene_name "KCNA7"; gene_source "ensembl"; gene_biotype "protein_coding";
59 gene_id "ENSOCUG00000010929"; gene_version "4"; gene_name "NAGPA"; gene_source "ensembl"; gene_biotype "protein_coding";
60 gene_id "ENSOCUG00000021568"; gene_version "2"; gene_name "NADK"; gene_source "ensembl"; gene_biotype "protein_coding";
61 gene_id "ENSOCUG00000006360"; gene_version "4"; gene_name "SNAP47"; gene_source "ensembl"; gene_biotype "protein_coding";
62 gene_id "ENSOCUG00000001475"; gene_version "4"; gene_name "GNA12"; gene_source "ensembl"; gene_biotype "protein_coding";
63 gene_id "ENSOCUG00000010687"; gene_version "5"; gene_name "KCNAB2"; gene_source "ensembl"; gene_biotype "protein_coding";
64 gene_id "ENSOCUG00000005624"; gene_version "3"; gene_name "NAP1L4"; gene_source "ensembl"; gene_biotype "protein_coding";
65 gene_id "ENSOCUG00000015545"; gene_version "4"; gene_name "NAXD"; gene_source "ensembl"; gene_biotype "protein_coding";
66 gene_id "ENSOCUG00000016421"; gene_version "4"; gene_name "GRINA"; gene_source "ensembl"; gene_biotype "protein_coding";
67 gene_id "ENSOCUG00000014802"; gene_version "4"; gene_name "NANOS3"; gene_source "ensembl"; gene_biotype "protein_coding";
68 gene_id "ENSOCUG00000021573"; gene_version "2"; gene_name "DNASE2"; gene_source "ensembl"; gene_biotype "protein_coding";
69 gene_id "ENSOCUG00000015922"; gene_version "3"; gene_name "RNASEL"; gene_source "ensembl"; gene_biotype "protein_coding";
70 gene_id "ENSOCUG00000002185"; gene_version "4"; gene_name "CHRNA4"; gene_source "ensembl"; gene_biotype "protein_coding";
71 gene_id "ENSOCUG00000015910"; gene_version "4"; gene_name "DNASE1L1"; gene_source "ensembl"; gene_biotype "protein_coding";

In [56]:
library(BSgenome.Ocuniculus.NCBI.oryCun2)

Loading required package: BSgenome

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:tidyr’:

    expand


The following objects are masked from ‘package:data.table’:

    first, second


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following object is masked from ‘package:data.table’:

    shift


Loading required package: GenomeInfoDb

Loading required package: GenomicRanges

Loading required package: Biostrings

Loading required package: XVector


Attaching package: ‘Biostrings’


The following object is masked from ‘package:base’:

    strsplit


Loading required package: rtracklayer

In [57]:
BSgenome.Ocuniculus.NCBI.oryCun2

Rabbit genome:
# organism: Oryctolagus cuniculus (Rabbit)
# genome: OryCun2.0
# provider: NCBI
# release date: Oct. 2009
# 3242 sequences:
#   chr1      chr10     chr11     chr12     chr13     chr14     chr15
#   chr16     chr17     chr18     chr19     chr2      chr20     chr21
#   chr3      chr4      chr5      chr6      chr7      chr8      chr9
#   chrX      chrUn0001 chrUn0002 chrUn0003 chrUn0004 chrUn0005 chrUn0006
#   chrUn0007 chrUn0008 chrUn0009 chrUn0010 chrUn0011 chrUn0012 chrUn0013
#   ...       ...       ...       ...       ...       ...       ...
#   chrUn3192 chrUn3193 chrUn3194 chrUn3195 chrUn3196 chrUn3197 chrUn3198
#   chrUn3199 chrUn3200 chrUn3201 chrUn3202 chrUn3203 chrUn3204 chrUn3205
#   chrUn3206 chrUn3207 chrUn3208 chrUn3209 chrUn3210 chrUn3211 chrUn3212
#   chrUn3213 chrUn3214 chrUn3215 chrUn3216 chrUn3217 chrUn3218 chrUn3219
#   chrM
# (use 'seqnames()' to see all the sequence names, use the '$' or '[[' operator
# to access a given sequence)

In [132]:
genomeAnno = createGenomeAnnotation(
  genome = BSgenome.Ocuniculus.NCBI.oryCun2,
#   chromSizes = NULL,
#   blacklist = NULL, ##### THIS SETTING SHOULD BE USED FOR THE RERUN!!! OTHERWISE AUTOMATICALLY LOSE ALL OTHER CHRS
   filter = FALSE#,
#   filterChr = c("chr1")
)

Getting genome..

Getting chromSizes..

Getting blacklist..

Blacklist not downloaded! Continuing without, be careful for downstream biases..

In [133]:
genomeAnno$chromSizes

GRanges object with 3242 ranges and 0 metadata columns:
          seqnames      ranges strand
             <Rle>   <IRanges>  <Rle>
     [1]      chr1 1-194850757      *
     [2]     chr10  1-47997241      *
     [3]     chr11  1-87554214      *
     [4]     chr12 1-155355395      *
     [5]     chr13 1-143360832      *
     ...       ...         ...    ...
  [3238] chrUn3216      1-3091      *
  [3239] chrUn3217      1-3070      *
  [3240] chrUn3218      1-3031      *
  [3241] chrUn3219      1-3025      *
  [3242]      chrM     1-17245      *
  -------
  seqinfo: 3242 sequences from an unspecified genome

In [112]:
paste('total genome size: ')
sum(genomeAnno$chromSizes@ranges@width)
paste('known chr genome size: ')
sum(genomeAnno$chromSizes@ranges@width[1:22])
paste('unkown chr genome size: ')
sum(genomeAnno$chromSizes@ranges@width) - sum(genomeAnno$chromSizes@ranges@width[1:23])
paste('percentage unkown chr genome: ')
round((sum(genomeAnno$chromSizes@ranges@width) - sum(genomeAnno$chromSizes@ranges@width[1:23]))/sum(genomeAnno$chromSizes@ranges@width) * 100, 1)

[1] "total genome size: "

[1] 2737490501

[1] "known chr genome size: "

[1] 2247752104

[1] "unkown chr genome size: "

[1] 475567325

[1] "percentage unkown chr genome: "

[1] 17.4

# Fasta of genome made from 2bit file using command line

rabbit genome library contains chrUn, which probably correspond to the non-standard chrs in the 10x ref genome, but how do we convert between the two?

https://hgdownload.soe.ucsc.edu/goldenPath/oryCun2/bigZips/oryCun2.chromAlias.txt

shows conversion of chrUn to plasmid name, but how to edit these in fasta files?

Download files from:

https://hgdownload.soe.ucsc.edu/goldenPath/oryCun2/bigZips/

maybe go from 2bit file to fa file and recreate reference genome

Can recreate the geneAnnotation from the genes.gtf we already have, and rename chrs to chrUN (explained here: https://genome.ucsc.edu/goldenPath/help/twoBit.html)

In command line: 
rsync -aP rsync://hgdownload.soe.ucsc.edu/genome/admin/exe/linux.x86_64/twoBitToFa /rds/project/rds-SDzz0CATGms/users/bt392/software/UCSC/

chmod 744 twoBitToFa

cd /rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/genome/
/rds/project/rds-SDzz0CATGms/users/bt392/software/UCSC/twoBitToFa oryCun2.2bit oryCun2.fasta

# edit genes.gtf so it matches with the fasta file

In [ ]:
setwd('/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/genome/10x_rabbit_ref/')

In [206]:
genes = fread(paste0(basedir, 'genes.gtf'))
colnames(genes) = paste0('V', 1:9)

Warning message in fread(paste0(basedir, "genes.gtf")):
“Detected 1 column names but the data has 9 columns (i.e. invalid file). Added 8 extra default column names at the end.”

In [207]:
chrnames = fread('chr_names.txt', sep='\t')[,1:2]
colnames(chrnames) = paste0('V', c(2,1))

Warning message in fread("chr_names.txt", sep = "\t"):
“Detected 3 column names but the data has 2 columns. Filling rows automatically. Set fill=TRUE explicitly to avoid this warning.”

In [210]:
length(unique(genes[genes$V1 %in% chrnames$V1]$V1))
length(unique(genes$V1))

[1] 1026

[1] 1026

In [211]:
genes$idx = 1:nrow(genes)

In [212]:
genes = merge(genes, chrnames, by = 'V1')
genes = genes[order(genes$idx)]
genes$idx = NULL

In [213]:
genes$V1 = NULL
genes = genes[, c(9, 1:8)]

In [215]:
tail(genes)

  V2.y      V2.x    V3              V4   V5   V6 V7 V8
1 chrUn3205 ensembl start_codon     2400 2402 .  +  0
2 chrUn3205 ensembl exon            2549 3515 .  +  .
3 chrUn3205 ensembl CDS             2549 2745 .  +  2
4 chrUn3205 ensembl stop_codon      2746 2748 .  +  0
5 chrUn3205 ensembl five_prime_utr  2339 2399 .  +  .
6 chrUn3205 ensembl three_prime_utr 2749 3515 .  +  .
  V9
1 gene_id "ENSOCUG00000022430"; gene_version "2"; transcript_id "ENSOCUT00000008112"; transcript_version "3"; exon_number "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding";
2 gene_id "ENSOCUG00000022430"; gene_version "2"; transcript_id "ENSOCUT00000008112"; transcript_version "3"; exon_number "2"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSOCUE00000259531"; exon_version "2";
3 gene_id "ENSOCUG00000022430"; gene_version "2"; transcript_id "ENSOCUT00000008112"; transcript_version "3"; exon_number "2"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding"; protein_id "ENSOCUP00000035303"; protein_version "1";
4 gene_id "ENSOCUG00000022430"; gene_version "2"; transcript_id "ENSOCUT00000008112"; transcript_version "3"; exon_number "2"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding";
5 gene_id "ENSOCUG00000022430"; gene_version "2"; transcript_id "ENSOCUT00000008112"; transcript_version "3"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding";
6 gene_id "ENSOCUG00000022430"; gene_version "2"; transcript_id "ENSOCUT00000008112"; transcript_version "3"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding";

In [216]:
summary(genes$V2.y %in% chrnames$V2)

   Mode    TRUE
logical 1097115

In [217]:
fwrite(genes, 
       '/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/genome/10x_rabbit_final/genes_new.gtf',
       sep = '\t', 
      row.names = FALSE,
      col.names = FALSE,
      quote = FALSE)

# header added manually in file editor

# Create gene annotation from genes.gtf

In [224]:
genes = fread('/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/genome/10x_rabbit_final/genes_new.gtf')
colnames(genes) = paste0('V', 1:9)

Warning message in fread("/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/genome/10x_rabbit_final/genes_new.gtf"):
“Detected 1 column names but the data has 9 columns (i.e. invalid file). Added 8 extra default column names at the end.”

In [220]:
original = readRDS("/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/geneAnnotation.rds")

In [222]:
original$genes
original$exons
original$TSS

GRanges object with 21102 ranges and 2 metadata columns:
          seqnames              ranges strand |            gene_id
             <Rle>           <IRanges>  <Rle> |        <character>
      [1]     chr1         15188-30378      + | ENSOCUG00000014251
      [2]     chr1         52453-53037      + | ENSOCUG00000005054
      [3]     chr1         57421-74905      - | ENSOCUG00000005046
      [4]     chr1         75200-85748      + | ENSOCUG00000005044
      [5]     chr1         92423-95845      - | ENSOCUG00000005040
      ...      ...                 ...    ... .                ...
  [21098]     chrX 111491397-111496239      - | ENSOCUG00000007220
  [21099]     chrX 111494764-111494835      - | ENSOCUG00000019315
  [21100]     chrX 111523844-111597291      + | ENSOCUG00000029751
  [21101]     chrX 111532709-111532815      - | ENSOCUG00000022547
  [21102]     chrX 111628200-111629717      - | ENSOCUG00000027130
                      symbol
                 <character>
      [1]              WDR31
      [2]             RNF183
      [3]              PRPF4
      [4]              CDC26
      [5]            SLC31A1
      ...                ...
  [21098] ENSOCUG00000007220
  [21099] ENSOCUG00000019315
  [21100] ENSOCUG00000029751
  [21101]                 U6
  [21102]             GPR101
  -------
  seqinfo: 22 sequences from an unspecified genome

GRanges object with 175810 ranges and 3 metadata columns:
           seqnames              ranges strand |   exon_id            gene_id
              <Rle>           <IRanges>  <Rle> | <integer>        <character>
       [1]     chr1         15188-15281      + |         1 ENSOCUG00000014251
       [2]     chr1         20324-20325      + |         2 ENSOCUG00000014251
       [3]     chr1         20453-20602      + |         3 ENSOCUG00000014251
       [4]     chr1         20453-20602      + |         4 ENSOCUG00000014251
       [5]     chr1         21033-21162      + |         5 ENSOCUG00000014251
       ...      ...                 ...    ... .       ...                ...
  [175806]     chrX 111494764-111494835      - |    175806 ENSOCUG00000007220
  [175807]     chrX 111494883-111495010      - |    175807 ENSOCUG00000007220
  [175808]     chrX 111496121-111496239      - |    175808 ENSOCUG00000007220
  [175809]     chrX 111532709-111532815      - |    175809 ENSOCUG00000022547
  [175810]     chrX 111628200-111629717      - |    175810 ENSOCUG00000027130
                       symbol
                  <character>
       [1]              WDR31
       [2]              WDR31
       [3]              WDR31
       [4]              WDR31
       [5]              WDR31
       ...                ...
  [175806] ENSOCUG00000007220
  [175807] ENSOCUG00000007220
  [175808] ENSOCUG00000007220
  [175809]                 U6
  [175810]             GPR101
  -------
  seqinfo: 22 sequences from an unspecified genome

GRanges object with 38003 ranges and 2 metadata columns:
                     seqnames    ranges strand |     tx_id            tx_name
                        <Rle> <IRanges>  <Rle> | <integer>        <character>
  ENSOCUG00000014251     chr1     15188      + |         1 ENSOCUT00000014253
  ENSOCUG00000014251     chr1     20324      + |         2 ENSOCUT00000038745
  ENSOCUG00000005054     chr1     52453      + |         3 ENSOCUT00000005053
  ENSOCUG00000005044     chr1     75200      + |         4 ENSOCUT00000005041
  ENSOCUG00000005028     chr1    125890      + |         5 ENSOCUT00000005032
                 ...      ...       ...    ... .       ...                ...
  ENSOCUG00000000255     chrX 111369675      - |     37999 ENSOCUT00000000255
  ENSOCUG00000007220     chrX 111496239      - |     38000 ENSOCUT00000007220
  ENSOCUG00000019315     chrX 111494835      - |     38001 ENSOCUT00000019315
  ENSOCUG00000022547     chrX 111532815      - |     38002 ENSOCUT00000023399
  ENSOCUG00000027130     chrX 111629717      - |     38003 ENSOCUT00000023097
  -------
  seqinfo: 22 sequences from an unspecified genome

In [248]:
genes$gene_id = sapply(strsplit(genes$V9,";"), `[`, 1)
genes$gene_id = sapply(strsplit(genes$gene_id,"\""), `[`, 2)

In [250]:
genes_gene = genes[genes$V3 == 'gene']
genes_exon = genes[genes$V3 == 'exon']

### Get all gene names

In [289]:
gene_names = genes_gene[grep('gene_name', genes_gene$V9)]

In [290]:
gene_names$symbol = sapply(strsplit(gene_names$V9,"gene_name"), `[`, 2)
gene_names$symbol = sapply(strsplit(gene_names$symbol,";"), `[`, 1)
gene_names$symbol = gsub('\"', '', gene_names$symbol)
gene_names = gene_names[, c('gene_id', 'symbol')]

In [291]:
all_gene_names = genes_gene[, 'gene_id']
all_gene_names = merge(all_gene_names, gene_names, by='gene_id', all.x=TRUE)

In [293]:
summary(is.na(all_gene_names$symbol))

   Mode   FALSE    TRUE
logical   12669    7943

In [344]:
no_name = all_gene_names[is.na(all_gene_names$symbol),][,1]

In [345]:
# 7943 genes without gene names, let's see if we can get them from other files

In [346]:
biomart = fread('/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/gene_map_biomart.csv')

In [347]:
no_name = merge(no_name, biomart, by='gene_id')

In [348]:
paste('gene names recovered:') 
nrow(no_name[!grep('^ENSOCUG', no_name$symbol)])
biomart_name = no_name[!grep('^ENSOCUG', no_name$symbol)]

[1] "gene names recovered:"

[1] 301

In [352]:
final_gene_names = rbind(gene_names, no_name)

In [354]:
nrow(final_gene_names)

[1] 20612

### Create geneAnnotation file

In [27]:
suppressPackageStartupMessages({
        library(biomaRt)
        library(BSgenome.Ocuniculus.NCBI.oryCun2)
        library(GenomicFeatures)
        library(compEpiTools)
        library(GenomeInfoDb)
        library(stringi)
        library(AnnotationHub)
    })

In [401]:
# Create gene annotation using Txdb file
rabbit_txdb <- makeTxDbFromBiomart(biomart="ensembl", dataset="ocuniculus_gene_ensembl")

taxid = taxonomyId(rabbit_txdb)
## If we don't have a package, then lets get the taxIds and AHIds
        ## for the hub objects
        loadNamespace("AnnotationHub")
        ah <- AnnotationHub::AnnotationHub()
        ah <- subset(ah, ah$rdataclass=='OrgDb') 
        mc <- mcols(ah)[,'taxonomyid', drop=FALSE]
        ## Then just get the object
        AHID <- rownames(mc[mc$taxonomyid==taxid,,drop=FALSE])
        rabbit_OrgDb <- ah[[AHID[2]]]

#rabbit_txdb
geneAnnotation <- createGeneAnnotation(
  TxDb  = rabbit_txdb,
    OrgDb =rabbit_OrgDb,
  TSS = TSS(rabbit_txdb), 
  exons = exons(rabbit_txdb)
)

Warning message:
"Ensembl will soon enforce the use of https.
Ensure the 'host' argument includes "https://""
Download and preprocess the 'transcripts' data frame ...
OK

Download and preprocess the 'chrominfo' data frame ...
OK

Download and preprocess the 'splicings' data frame ...
OK

Download and preprocess the 'genes' data frame ...
OK

Prepare the 'metadata' data frame ...
Ensembl site unresponsive, trying uswest mirror

OK

Make the TxDb object ...
OK

snapshotDate(): 2021-10-20

loading from cache

'select()' returned 1:1 mapping between keys and columns

Getting Genes..

Determined Annotation Style = ENSEMBL

Getting Exons..

Getting TSS..

In [627]:
chrnames = fread('chr_names.txt', sep='\t')[,1:2]
colnames(chrnames) = paste0('V', c(2,1))

Warning message in fread("chr_names.txt", sep = "\t"):
"Detected 3 column names but the data has 2 columns. Filling rows automatically. Set fill=TRUE explicitly to avoid this warning."

In [628]:
# seqnames order
chr_old = data.frame(V1 = as.vector(seqnames(geneAnnotation$genes)))
chr_old$idx = 1:nrow(chr_old)
chr_new = merge(chr_old, chrnames, by='V1')
chr_new = chr_new[order(chr_new$idx),]

In [629]:
anno_gene.GR = GRanges(
    seqnames = Rle(chr_new$V2),
    ranges = IRanges(start= geneAnnotation$genes@ranges@start, 
                     end = geneAnnotation$genes@ranges@start + geneAnnotation$genes@ranges@width),
    strand = Rle(as.vector(geneAnnotation$genes@strand)),
    gene_id = geneAnnotation$genes$gene_id)

# gene names
order = as.data.frame(anno_gene.GR)
order$idx = 1:nrow(order)
symbols = merge(order, final_gene_names, by='gene_id', all.x=TRUE)
symbols = symbols[order(symbols$idx),]
symbols[is.na(symbols$symbol),]$symbol = symbols[is.na(symbols$symbol),]$gene_id

anno_gene.GR$gene_name = symbols$symbol

In [632]:
# Annotate exons with genes
overlaps = as.data.frame(findOverlaps(geneAnnotation$exons, geneAnnotation$genes))
overlaps = overlaps[!duplicated(overlaps$queryHits),] # removes exons mapped to multiple genes
exon_names = geneAnnotation$genes$gene_id[overlaps$subjectHits]

# seqnames order
chr_old = data.frame(V1 = as.vector(seqnames(geneAnnotation$exons)))
chr_old$idx = 1:nrow(chr_old)
chr_new = merge(chr_old, chrnames, by='V1')
chr_new = chr_new[order(chr_new$idx),]

In [633]:
anno_exon.GR = GRanges(
    seqnames = Rle(chr_new$V2),
    ranges = IRanges(start= geneAnnotation$exons@ranges@start, 
                     end = geneAnnotation$exons@ranges@start + geneAnnotation$exons@ranges@width),
    strand = Rle(as.vector(geneAnnotation$exons@strand)),
    exon_id = geneAnnotation$exons$exon_id, 
    gene_id = exon_names)

# gene names
order = as.data.frame(anno_exon.GR)
order$idx = 1:nrow(order)
symbols = merge(order, final_gene_names, by='gene_id', all.x=TRUE)
symbols = symbols[order(symbols$idx),]
symbols[is.na(symbols$symbol),]$symbol = symbols[is.na(symbols$symbol),]$gene_id

anno_exon.GR$gene_name = symbols$symbol

In [634]:
# seqnames order
chr_old = data.frame(V1 = as.vector(seqnames(geneAnnotation$TSS)))
chr_old$idx = 1:nrow(chr_old)
chr_new = merge(chr_old, chrnames, by='V1')
chr_new = chr_new[order(chr_new$idx),]

In [635]:
anno_TSS.GR = GRanges(
    seqnames = Rle(chr_new$V2),
    ranges = IRanges(start= geneAnnotation$TSS@ranges@start,
                    end = geneAnnotation$TSS@ranges@start, names = ),
    strand = Rle(as.vector(geneAnnotation$TSS@strand)),
    tx_id = geneAnnotation$TSS$tx_id, 
    tx_name =  geneAnnotation$TSS$tx_name)

In [636]:
geneAnno = geneAnnotation
geneAnno$genes = anno_gene.GR
geneAnno$exons = anno_exon.GR
geneAnno$TSS = anno_TSS.GR

In [643]:
saveRDS(geneAnno, "/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/geneAnnotation_new.rds")

In [639]:
geneAnno$genes
geneAnno$exons
geneAnno$TSS

GRanges object with 29587 ranges and 2 metadata columns:
           seqnames      ranges strand |            gene_id          gene_name
              <Rle>   <IRanges>  <Rle> |        <character>        <character>
      [1]      chr1 15188-30379      + | ENSOCUG00000014251              WDR31
      [2]      chr1 52453-53038      + | ENSOCUG00000005054             RNF183
      [3]      chr1 57421-74906      - | ENSOCUG00000005046              PRPF4
      [4]      chr1 75200-85749      + | ENSOCUG00000005044              CDC26
      [5]      chr1 92423-95846      - | ENSOCUG00000005040            SLC31A1
      ...       ...         ...    ... .                ...                ...
  [29583] chrUn1898 11177-12630      + | ENSOCUG00000037764 ENSOCUG00000037764
  [29584] chrUn2076   7995-8513      - | ENSOCUG00000036320 ENSOCUG00000036320
  [29585] chrUn2536     75-3970      - | ENSOCUG00000030662 ENSOCUG00000030662
  [29586] chrUn2536   1275-2316      + | ENSOCUG00000036489 ENSOCUG00000036489
  [29587] chrUn3209     21-1545      + | ENSOCUG00000026854 ENSOCUG00000026854
  -------
  seqinfo: 1402 sequences from an unspecified genome; no seqlengths

GRanges object with 234369 ranges and 3 metadata columns:
            seqnames      ranges strand |   exon_id            gene_id
               <Rle>   <IRanges>  <Rle> | <integer>        <character>
       [1]      chr1 15188-15282      + |         1 ENSOCUG00000014251
       [2]      chr1 20324-20326      + |         2 ENSOCUG00000014251
       [3]      chr1 20453-20603      + |         3 ENSOCUG00000014251
       [4]      chr1 20453-20603      + |         4 ENSOCUG00000014251
       [5]      chr1 21033-21163      + |         5 ENSOCUG00000014251
       ...       ...         ...    ... .       ...                ...
  [234365] chrUn2536   1275-2316      + |    234365 ENSOCUG00000036489
  [234366] chrUn2536      75-540      - |    234366 ENSOCUG00000030662
  [234367] chrUn2536   1735-2511      - |    234367 ENSOCUG00000030662
  [234368] chrUn2536   3715-3970      - |    234368 ENSOCUG00000030662
  [234369] chrUn3209     21-1545      + |    234369 ENSOCUG00000026854
                    gene_name
                  <character>
       [1]              WDR31
       [2]              WDR31
       [3]              WDR31
       [4]              WDR31
       [5]              WDR31
       ...                ...
  [234365] ENSOCUG00000036489
  [234366] ENSOCUG00000030662
  [234367] ENSOCUG00000030662
  [234368] ENSOCUG00000030662
  [234369] ENSOCUG00000026854
  -------
  seqinfo: 1402 sequences from an unspecified genome; no seqlengths

GRanges object with 51853 ranges and 2 metadata columns:
           seqnames    ranges strand |     tx_id            tx_name
              <Rle> <IRanges>  <Rle> | <integer>        <character>
      [1]      chr1     15188      + |         1 ENSOCUT00000014253
      [2]      chr1     20324      + |         2 ENSOCUT00000038745
      [3]      chr1     52453      + |         3 ENSOCUT00000005053
      [4]      chr1     75200      + |         4 ENSOCUT00000005041
      [5]      chr1    125890      + |         5 ENSOCUT00000005032
      ...       ...       ...    ... .       ...                ...
  [51849] chrUn1898     11177      + |     51849 ENSOCUT00000045693
  [51850] chrUn2076      8512      - |     51850 ENSOCUT00000064048
  [51851] chrUn2536      1275      + |     51851 ENSOCUT00000040680
  [51852] chrUn2536      3969      - |     51852 ENSOCUT00000053781
  [51853] chrUn3209        21      + |     51853 ENSOCUT00000029796
  -------
  seqinfo: 1402 sequences from an unspecified genome; no seqlengths

In [3]:
geneAnno = readRDS("/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/geneAnnotation_new.rds")

In [8]:
geneAnno$genes$symbol = geneAnno$genes$gene_name
geneAnno$genes$gene_name = NULL

geneAnno$exons$symbol = geneAnno$exons$gene_name
geneAnno$exons$gene_name = NULL

In [25]:
saveRDS(geneAnno, "/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/geneAnnotation_new.rds")

### See if we can discard chrs because they take crazy long to run

In [37]:
here::i_am("snakemake/01_create_arrow.R")
library(BSgenome.Ocuniculus.NCBI.oryCun2)
source(here::here("settings.R"))

here() starts at /rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final

Setting default number of Parallel threads to 1.

In [38]:
geneAnnotation = readRDS(file.path(io$basedir, 'geneAnnotation_new.rds'))

In [39]:
genomeAnnotation = createGenomeAnnotation(
  genome = BSgenome.Ocuniculus.NCBI.oryCun2,
  chromSizes = NULL,
  blacklist = NULL,
  filter = FALSE,
  filterChr = c("chrM")
)

Getting genome..

Getting chromSizes..

Getting blacklist..

Blacklist not downloaded! Continuing without, be careful for downstream biases..

In [44]:
chrs_genes = as.vector(seqnames(geneAnnotation$genes))

In [46]:
chrs_genome = as.vector(seqnames(genomeAnnotation$chromSizes))

In [48]:
intersect = intersect(chrs_genes, chrs_genome)

In [50]:
length(intersect)

[1] 1402

In [51]:
length(chrs_genome)

[1] 3242

In [58]:
chrs_exclude = chrs_genome[!chrs_genome %in% intersect]

In [71]:
BSgenome.Ocuniculus.NCBI.oryCun2

Rabbit genome:
# organism: Oryctolagus cuniculus (Rabbit)
# genome: OryCun2.0
# provider: NCBI
# release date: Oct. 2009
# 3242 sequences:
#   chr1      chr10     chr11     chr12     chr13     chr14     chr15
#   chr16     chr17     chr18     chr19     chr2      chr20     chr21
#   chr3      chr4      chr5      chr6      chr7      chr8      chr9
#   chrX      chrUn0001 chrUn0002 chrUn0003 chrUn0004 chrUn0005 chrUn0006
#   chrUn0007 chrUn0008 chrUn0009 chrUn0010 chrUn0011 chrUn0012 chrUn0013
#   ...       ...       ...       ...       ...       ...       ...
#   chrUn3192 chrUn3193 chrUn3194 chrUn3195 chrUn3196 chrUn3197 chrUn3198
#   chrUn3199 chrUn3200 chrUn3201 chrUn3202 chrUn3203 chrUn3204 chrUn3205
#   chrUn3206 chrUn3207 chrUn3208 chrUn3209 chrUn3210 chrUn3211 chrUn3212
#   chrUn3213 chrUn3214 chrUn3215 chrUn3216 chrUn3217 chrUn3218 chrUn3219
#   chrM
# (use 'seqnames()' to see all the sequence names, use the '$' or '[[' operator
# to access a given sequence)

In [91]:
genomeAnnotation = createGenomeAnnotation(
  genome = BSgenome.Ocuniculus.NCBI.oryCun2,
  chromSizes = NULL,
  blacklist = NULL,
  filter = TRUE,
  filterChr = 'chrM'
)
object.size(genomeAnnotation$genome)

genomeAnnotation = createGenomeAnnotation(
  genome = BSgenome.Ocuniculus.NCBI.oryCun2,
  chromSizes = NULL,
  blacklist = NULL,
  filter = FALSE,
  filterChr = 'chrM'
)
object.size(genomeAnnotation$genome)

Getting genome..

Getting chromSizes..

Getting blacklist..

Blacklist not downloaded! Continuing without, be careful for downstream biases..

152 bytes

Getting genome..

Getting chromSizes..

Getting blacklist..

Blacklist not downloaded! Continuing without, be careful for downstream biases..

152 bytes

In [103]:
# selecting based on chrs with genes on them
print('whole genome size: ')
sum(genomeAnnotation$chromSizes@ranges@width)
print('selected genome size: ')
sub1 = genomeAnnotation$chromSizes[genomeAnnotation$chromSizes@seqnames@values %in% intersect]
sum(sub1@ranges@width)
print('excluded size: ')
sub2 = genomeAnnotation$chromSizes[!genomeAnnotation$chromSizes@seqnames@values %in% intersect]
sum(sub2@ranges@width)
print('percentage excluded: ')
round(sum(sub2@ranges@width)/sum(sub1@ranges@width) * 100,1)

[1] "whole genome size: "

[1] 2737490501

[1] "selected genome size: "

[1] 2705359246

[1] "excluded size: "

[1] 32131255

[1] "percentage excluded: "

[1] 1.2

In [118]:
# Or selecting based on top chrs
x = 500

print('whole genome size: ')
sum(genomeAnnotation$chromSizes@ranges@width)
print('selected genome size: ')
sub1 = genomeAnnotation$chromSizes[1:x]
sum(sub1@ranges@width)
print('excluded size: ')
sub2 = genomeAnnotation$chromSizes[x:length(genomeAnnotation$chromSizes)]
sum(sub2@ranges@width)
print('percentage excluded: ')
round(sum(sub2@ranges@width)/sum(sub1@ranges@width) * 100,1)

[1] "whole genome size: "

[1] 2737490501

[1] "selected genome size: "

[1] 2670702097

[1] "excluded size: "

[1] 66919095

[1] "percentage excluded: "

[1] 2.5

In [125]:
genomeAnnotation$chromSizes[1:x]@ranges@width

  [1] 194850757  47997241  87554214 155355395 143360832 163896628 109054052
  [8]  84478945  85008467  69800736  57279966 174332312  33191332  15578276
 [15] 155691105  91394100  37992211  27502587 173684459 111795807 116251907
 [22] 111700775  14171072  13461802   8543514   7969563   6940555   6663442
 [29]   6124611   5787221   5429729   4921390   4836177   4701477   4487093
 [36]   4460581   4375787   4100111   4024058   3946108   3992494   3916169
 [43]   4028765   3856598   3419770   3399777   3524111   3456190   3407339
 [50]   3196474   2880289   2762230   2696808   2831799   2715061   2624217
 [57]   2610161   2613145   2586821   2467970   2374666   2467173   2331373
 [64]   2398104   2352391   2210801   2209796   2220855   2199458   2067550
 [71]   2041368   2148096   2006438   1958842   1879513   2008236   1777580
 [78]   1825906   1735093   1691152   1700645   1734957   1610157   1602899
 [85]   1546167   1503878   1506796   1474860   1414822   1396388   1378268
 [92]   1335702   1312651   1279700   1225893   1456394   1295358   1299260
 [99]   1217826   1207509   1187392   1157137   1166848   1147153   1168253
[106]   1171746   1146635   1131163   1191687   1165285   1113411   1107004
[113]   1112688   1109196   1081106   1164262   1071538   1082042   1067461
[120]   1156787   1052913   1050750   1104258   1035676   1019757   1000506
[127]   1021025   1032594   1087329   1022575    981750   1014670   1022565
[134]    960476    974419    964430    940520    948018    936934    928860
[141]    947161   1043626    891850    910185    960125    901664    851866
[148]    844703    875022    922215    877054    859581    893225    838382
[155]    819185   1002905    848867    817644    812274    771210    769394
[162]    777151    909958    763600    799640    727262    718386    734255
[169]    709936    691702    709480    718166    677194    652566    692640
[176]    643000    644897    736287    671117    745422    645466    612083
[183]    612182    601335    611938    660382    595215    611413    663941
[190]    615524    597939    594256    638014    625076    584792    700076
[197]    571908    557607    597847    577984    695312    560259    616689
[204]    557480    544012    533469    524045    519804    594140    490365
[211]    695759    563273    484298    494640    508009    485655    520116
[218]    491810    485638    484949    477758    487845    517741    574424
[225]    520597    443426    533676    506393    554071    440353    490636
[232]    432161    449196    419706    460747    422373    478022    426691
[239]    427691    423532    544747    411751    487052    422684    562182
[246]    529108    409714    427045    588789    402175    397044    399838
[253]    411742    402426    392443    400091    401537    438693    466235
[260]    407822    364097    500451    383229    364963    384480    375673
[267]    360449    363945    380127    362585    383068    338366    345079
[274]    352109    378319    344976    362617    351627    322388    327937
[281]    329287    316904    390651    341666    312283    329791    323064
[288]    335086    319267    433379    309810    324334    321748    362023
[295]    303951    306030    307073    318877    313347    305990    353248
[302]    415988    353077    288718    315683    289602    297997    306135
[309]    353492    294012    296910    342155    291730    282669    279930
[316]    330290    288293    282206    337789    272723    293404    372349
[323]    266600    291431    270227    377253    278756    270375    267680
[330]    278674    296074    259960    310523    259833    279267    296745
[337]    314451    255788    314838    299706    257668    246242    248675
[344]    252097    386965    252537    377412    270339    244752    414911
[351]    299444    238549    239902    228799    238318    230350    242861
[358]    288633    238826    240786    380789    264947    446509    247762
[365]    227079    226169    238712    216051    218638    227053    218694
[372]    215483    247428    219630    218866    218320    224869    305376
[379]    225028    208638    208624    204766    205414    229295    239792
[386]    210305    431909    212013    203155    207091    228370    196526
[393]    200706    207068    242719    205348    196740    187862    187187
[400]    219564    204101    212876    190959    305139    195033    182623
[407]    185195    182517    185092    198899    182892    291127    179452
[414]    190382    178399    177748    188503    177111    180943    171866
[421]    272875    210757    168426    175054    166872    166925    170646
[428]    171269    181819    205233    178882    169806    245216    161169
[435]    168649    169983    247568    171919    166707    201426    166725
[442]    156353    290270    151114    154793    163485    157626    166360
[449]    166449    265548    158469    157054    249440    161558    171979
[456]    157887    172468    146275    145535    141946    177735    158679
[463]    149950    146021    144703    153905    194295    201710    179805
[470]    146287    156916    148361    139370    144554    140932    147895
[477]    139324    143423    148166    190423    145032    142860    143211
[484]    164977    139311    137024    151609    144779    132808    137074
[491]    140299    142873    134098    134231    138172    134657    134607
[498]    131533    138640    130691

In [121]:
as.vector(seqnames(genomeAnnotation$chromSizes[1:x]))

  [1] "chr1"      "chr10"     "chr11"     "chr12"     "chr13"     "chr14"
  [7] "chr15"     "chr16"     "chr17"     "chr18"     "chr19"     "chr2"
 [13] "chr20"     "chr21"     "chr3"      "chr4"      "chr5"      "chr6"
 [19] "chr7"      "chr8"      "chr9"      "chrX"      "chrUn0001" "chrUn0002"
 [25] "chrUn0003" "chrUn0004" "chrUn0005" "chrUn0006" "chrUn0007" "chrUn0008"
 [31] "chrUn0009" "chrUn0010" "chrUn0011" "chrUn0012" "chrUn0013" "chrUn0014"
 [37] "chrUn0015" "chrUn0016" "chrUn0017" "chrUn0018" "chrUn0019" "chrUn0020"
 [43] "chrUn0021" "chrUn0022" "chrUn0023" "chrUn0024" "chrUn0025" "chrUn0026"
 [49] "chrUn0027" "chrUn0028" "chrUn0029" "chrUn0030" "chrUn0031" "chrUn0032"
 [55] "chrUn0033" "chrUn0034" "chrUn0035" "chrUn0036" "chrUn0037" "chrUn0038"
 [61] "chrUn0039" "chrUn0040" "chrUn0041" "chrUn0042" "chrUn0043" "chrUn0044"
 [67] "chrUn0045" "chrUn0046" "chrUn0047" "chrUn0048" "chrUn0049" "chrUn0050"
 [73] "chrUn0051" "chrUn0052" "chrUn0053" "chrUn0054" "chrUn0055" "chrUn0056"
 [79] "chrUn0057" "chrUn0058" "chrUn0059" "chrUn0060" "chrUn0061" "chrUn0062"
 [85] "chrUn0063" "chrUn0064" "chrUn0065" "chrUn0066" "chrUn0067" "chrUn0068"
 [91] "chrUn0069" "chrUn0070" "chrUn0071" "chrUn0072" "chrUn0073" "chrUn0074"
 [97] "chrUn0075" "chrUn0076" "chrUn0077" "chrUn0078" "chrUn0079" "chrUn0080"
[103] "chrUn0081" "chrUn0082" "chrUn0083" "chrUn0084" "chrUn0085" "chrUn0086"
[109] "chrUn0087" "chrUn0088" "chrUn0089" "chrUn0090" "chrUn0091" "chrUn0092"
[115] "chrUn0093" "chrUn0094" "chrUn0095" "chrUn0096" "chrUn0097" "chrUn0098"
[121] "chrUn0099" "chrUn0100" "chrUn0101" "chrUn0102" "chrUn0103" "chrUn0104"
[127] "chrUn0105" "chrUn0106" "chrUn0107" "chrUn0108" "chrUn0109" "chrUn0110"
[133] "chrUn0111" "chrUn0112" "chrUn0113" "chrUn0114" "chrUn0115" "chrUn0116"
[139] "chrUn0117" "chrUn0118" "chrUn0119" "chrUn0120" "chrUn0121" "chrUn0122"
[145] "chrUn0123" "chrUn0124" "chrUn0125" "chrUn0126" "chrUn0127" "chrUn0128"
[151] "chrUn0129" "chrUn0130" "chrUn0131" "chrUn0132" "chrUn0133" "chrUn0134"
[157] "chrUn0135" "chrUn0136" "chrUn0137" "chrUn0138" "chrUn0139" "chrUn0140"
[163] "chrUn0141" "chrUn0142" "chrUn0143" "chrUn0144" "chrUn0145" "chrUn0146"
[169] "chrUn0147" "chrUn0148" "chrUn0149" "chrUn0150" "chrUn0151" "chrUn0152"
[175] "chrUn0153" "chrUn0154" "chrUn0155" "chrUn0156" "chrUn0157" "chrUn0158"
[181] "chrUn0159" "chrUn0160" "chrUn0161" "chrUn0162" "chrUn0163" "chrUn0164"
[187] "chrUn0165" "chrUn0166" "chrUn0167" "chrUn0168" "chrUn0169" "chrUn0170"
[193] "chrUn0171" "chrUn0172" "chrUn0173" "chrUn0174" "chrUn0175" "chrUn0176"
[199] "chrUn0177" "chrUn0178" "chrUn0179" "chrUn0180" "chrUn0181" "chrUn0182"
[205] "chrUn0183" "chrUn0184" "chrUn0185" "chrUn0186" "chrUn0187" "chrUn0188"
[211] "chrUn0189" "chrUn0190" "chrUn0191" "chrUn0192" "chrUn0193" "chrUn0194"
[217] "chrUn0195" "chrUn0196" "chrUn0197" "chrUn0198" "chrUn0199" "chrUn0200"
[223] "chrUn0201" "chrUn0202" "chrUn0203" "chrUn0204" "chrUn0205" "chrUn0206"
[229] "chrUn0207" "chrUn0208" "chrUn0209" "chrUn0210" "chrUn0211" "chrUn0212"
[235] "chrUn0213" "chrUn0214" "chrUn0215" "chrUn0216" "chrUn0217" "chrUn0218"
[241] "chrUn0219" "chrUn0220" "chrUn0221" "chrUn0222" "chrUn0223" "chrUn0224"
[247] "chrUn0225" "chrUn0226" "chrUn0227" "chrUn0228" "chrUn0229" "chrUn0230"
[253] "chrUn0231" "chrUn0232" "chrUn0233" "chrUn0234" "chrUn0235" "chrUn0236"
[259] "chrUn0237" "chrUn0238" "chrUn0239" "chrUn0240" "chrUn0241" "chrUn0242"
[265] "chrUn0243" "chrUn0244" "chrUn0245" "chrUn0246" "chrUn0247" "chrUn0248"
[271] "chrUn0249" "chrUn0250" "chrUn0251" "chrUn0252" "chrUn0253" "chrUn0254"
[277] "chrUn0255" "chrUn0256" "chrUn0257" "chrUn0258" "chrUn0259" "chrUn0260"
[283] "chrUn0261" "chrUn0262" "chrUn0263" "chrUn0264" "chrUn0265" "chrUn0266"
[289] "chrUn0267" "chrUn0268" "chrUn0269" "chrUn0270" "chrUn0271" "chrUn0272"
[295] "chrUn0273" "chrUn0274" "chrUn0275" "chrUn0276" "chrUn0277" "chrUn0278"
[301] "chrUn0279" "chrUn0280" "chrUn0281" "chrUn0282" "chrUn0283" "chrUn0284"
[307] "chrUn0285" "chrUn0286" "chrUn0287" "chrUn0288" "chrUn0289" "chrUn0290"
[313] "chrUn0291" "chrUn0292" "chrUn0293" "chrUn0294" "chrUn0295" "chrUn0296"
[319] "chrUn0297" "chrUn0298" "chrUn0299" "chrUn0300" "chrUn0301" "chrUn0302"
[325] "chrUn0303" "chrUn0304" "chrUn0305" "chrUn0306" "chrUn0307" "chrUn0308"
[331] "chrUn0309" "chrUn0310" "chrUn0311" "chrUn0312" "chrUn0313" "chrUn0314"
[337] "chrUn0315" "chrUn0316" "chrUn0317" "chrUn0318" "chrUn0319" "chrUn0320"
[343] "chrUn0321" "chrUn0322" "chrUn0323" "chrUn0324" "chrUn0325" "chrUn0326"
[349] "chrUn0327" "chrUn0328" "chrUn0329" "chrUn0330" "chrUn0331" "chrUn0332"
[355] "chrUn0333" "chrUn0334" "chrUn0335" "chrUn0336" "chrUn0337" "chrUn0338"
[361] "chrUn0339" "chrUn0340" "chrUn0341" "chrUn0342" "chrUn0343" "chrUn0344"
[367] "chrUn0345" "chrUn0346" "chrUn0347" "chrUn0348" "chrUn0349" "chrUn0350"
[373] "chrUn0351" "chrUn0352" "chrUn0353" "chrUn0354" "chrUn0355" "chrUn0356"
[379] "chrUn0357" "chrUn0358" "chrUn0359" "chrUn0360" "chrUn0361" "chrUn0362"
[385] "chrUn0363" "chrUn0364" "chrUn0365" "chrUn0366" "chrUn0367" "chrUn0368"
[391] "chrUn0369" "chrUn0370" "chrUn0371" "chrUn0372" "chrUn0373" "chrUn0374"
[397] "chrUn0375" "chrUn0376" "chrUn0377" "chrUn0378" "chrUn0379" "chrUn0380"
[403] "chrUn0381" "chrUn0382" "chrUn0383" "chrUn0384" "chrUn0385" "chrUn0386"
[409] "chrUn0387" "chrUn0388" "chrUn0389" "chrUn0390" "chrUn0391" "chrUn0392"
[415] "chrUn0393" "chrUn0394" "chrUn0395" "chrUn0396" "chrUn0397" "chrUn0398"
[421] "chrUn0399" "chrUn0400" "chrUn0401" "chrUn0402" "chrUn0403" "chrUn0404"
[427] "chrUn0405" "chrUn0406" "chrUn0407" "chrUn0408" "chrUn0409" "chrUn0410"
[433] "chrUn0411" "chrUn0412" "chrUn0413" "chrUn0414" "chrUn0415" "chrUn0416"
[439] "chrUn0417" "chrUn0418" "chrUn0419" "chrUn0420" "chrUn0421" "chrUn0422"
[445] "chrUn0423" "chrUn0424" "chrUn0425" "chrUn0426" "chrUn0427" "chrUn0428"
[451] "chrUn0429" "chrUn0430" "chrUn0431" "chrUn0432" "chrUn0433" "chrUn0434"
[457] "chrUn0435" "chrUn0436" "chrUn0437" "chrUn0438" "chrUn0439" "chrUn0440"
[463] "chrUn0441" "chrUn0442" "chrUn0443" "chrUn0444" "chrUn0445" "chrUn0446"
[469] "chrUn0447" "chrUn0448" "chrUn0449" "chrUn0450" "chrUn0451" "chrUn0452"
[475] "chrUn0453" "chrUn0454" "chrUn0455" "chrUn0456" "chrUn0457" "chrUn0458"
[481] "chrUn0459" "chrUn0460" "chrUn0461" "chrUn0462" "chrUn0463" "chrUn0464"
[487] "chrUn0465" "chrUn0466" "chrUn0467" "chrUn0468" "chrUn0469" "chrUn0470"
[493] "chrUn0471" "chrUn0472" "chrUn0473" "chrUn0474" "chrUn0475" "chrUn0476"
[499] "chrUn0477" "chrUn0478"