# preparing extended atlas

In [1]:
suppressPackageStartupMessages({
    library(data.table)
    library(Matrix)
    library(dplyr)
})

In [2]:
main = '/rds/project/rds-SDzz0CATGms/users/bt392/atlasses/extended/'

In [3]:
meta = readRDS(paste0(main, 'integrated_meta_celltype_clus.rds'))
meta = meta[, c('cell', 'sample', 'stage', 'celltype.descendant', 'celltype.clustering')]
colnames(meta) = c('cell', 'sample', 'stage', 'celltype_original', 'celltype')

In [95]:
atlas_in = '/rds/project/rds-SDzz0CATGms/users/bt392/mouse/Mixl1_KO/atlas/atlas/'
old_meta = read.table(paste0(atlas_in, 'meta.tab'), header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "$")

In [ ]:
counts = fread(paste0(main, 'integrated_counts_datatable.tab')) %>% .[rowSums(.[,-1]) > 0,]
genes = counts[,1]
colnames(genes) = 'V1'

In [ ]:
counts = as(as.matrix(counts[,-1]), "dgTMatrix")

In [ ]:
writeMM(counts, paste0(main, 'raw_counts.mtx'))
write.table(genes, paste0(main, 'genes.tsv'), sep='\t')
write.table(meta, paste0(main, 'meta.tab'), sep='\t')

In [5]:
test = fread(file.path(getwd(), 'meta.tab'))

In [8]:
unique(test$celltype)

 [1] "Epiblast"
 [2] "Primitive Streak"
 [3] "ExE ectoderm"
 [4] "Visceral endoderm"
 [5] "ExE endoderm"
 [6] "Non-neural ectoderm"
 [7] "Nascent mesoderm"
 [8] "Parietal endoderm"
 [9] "Ectoderm"
[10] "Anterior Primitive Streak"
[11] "Haematoendothelial progenitors"
[12] "Caudal epiblast"
[13] "Blood progenitors"
[14] "Intermediate mesoderm"
[15] "Paraxial mesoderm"
[16] "Lateral plate mesoderm"
[17] "Mesenchyme"
[18] "PGC"
[19] "Node"
[20] "Gut tube"
[21] "Embryo proper endothelium"
[22] "Cardiopharyngeal progenitors SHF"
[23] "Notochord"
[24] "Amniotic ectoderm"
[25] "Venous endothelium"
[26] "Presomitic mesoderm"
[27] "Cardiomyocytes FHF 1"
[28] "Allantois"
[29] "Cranial mesoderm"
[30] "EMP"
[31] "Limb mesoderm"
[32] "Anterior somitic tissues"
[33] "Pharyngeal mesoderm"
[34] "Allantois endothelium"
[35] "Thyroid primordium"
[36] "Erythroid"
[37] "Hindbrain neural progenitors"
[38] "Cardiomyocytes SHF 1"
[39] "NMPs"
[40] "Pharyngeal endoderm"
[41] "Dorsal spinal cord progenitors"
[42] "Anterior cardiopharyngeal progenitors"
[43] "Placodal ectoderm"
[44] "Optic vesicle"
[45] "Ventral forebrain progenitors"
[46] "Spinal cord progenitors"
[47] "Hindgut"
[48] "Caudal mesoderm"
[49] "Embryo proper mesothelium"
[50] "Neural tube"
[51] "Midbrain/Hindbrain boundary"
[52] "Posterior somitic tissues"
[53] "Midgut"
[54] "Migratory neural crest"
[55] "Ventral hindbrain progenitors"
[56] "Surface ectoderm"
[57] "YS mesothelium"
[58] "Limb ectoderm"
[59] "Somitic mesoderm"
[60] "NMPs/Mesoderm-biased"
[61] "Cardiomyocytes FHF 2"
[62] "Foregut"
[63] "Dermomyotome"
[64] "Kidney primordium"
[65] "Otic placode"
[66] "Cardiomyocytes SHF 2"
[67] "Midbrain progenitors"
[68] "Cardiopharyngeal progenitors FHF"
[69] "Epicardium"
[70] "Hindbrain floor plate"
[71] "Late dorsal forebrain progenitors"
[72] "Dorsal hindbrain progenitors"
[73] "Sclerotome"
[74] "YS endothelium"
[75] "Endocardium"
[76] "MEP"
[77] "Epidermis"
[78] "Megakaryocyte progenitors"
[79] "Early dorsal forebrain progenitors"
[80] "Cardiopharyngeal progenitors"
[81] "Chorioallantoic-derived erythroid progenitors"
[82] "YS mesothelium-derived endothelial progenitors"
[83] "Dorsal midbrain neurons"
[84] "Branchial arch neural crest"
[85] "Forelimb"
[86] "Frontonasal mesenchyme"
[87] "Otic neural progenitors"

In [4]:
ct_keep = c('Haematoendothelial progenitors',
  'Blood progenitors',
  'Embryo proper endothelium',
  'Venous endothelium',
  'EMP',
  'Erythroid',
  'MEP',
  'Megakaryocyte progenitors',
  'Chorioallantoic-derived erythroid progenitors',
  'YS mesothelium-derived endothelial progenitors')

In [5]:
main = '/rds/project/rds-SDzz0CATGms/users/bt392/atlasses/extended/'

meta = readRDS(paste0(main, 'integrated_meta_celltype_clus.rds')) %>% as.data.table()

In [6]:
unique(meta$celltype.extended)

 [1] Epiblast                       Primitive Streak
 [3] ExE ectoderm                   Visceral endoderm
 [5] ExE endoderm                   Nascent mesoderm
 [7] Rostral neurectoderm           Blood progenitors 2
 [9] Mixed mesoderm                 ExE mesoderm
[11] Intermediate mesoderm          Pharyngeal mesoderm
[13] Caudal epiblast                PGC
[15] Mesenchyme                     Haematoendothelial progenitors
[17] Blood progenitors 1            Surface ectoderm
[19] Gut                            Paraxial mesoderm
[21] Caudal neurectoderm            Notochord
[23] Somitic mesoderm               Caudal Mesoderm
[25] Erythroid1                     Def. endoderm
[27] Parietal endoderm              Allantois
[29] Anterior Primitive Streak      Endothelium
[31] Forebrain/Midbrain/Hindbrain   Spinal cord
[33] Cardiomyocytes                 Erythroid2
[35] NMP                            Erythroid3
[37] Neural crest                   Undetermined
38 Levels: Allantois Anterior Primitive Streak ... Undetermined

In [8]:
head(meta[celltype.clustering %in% ct_keep])

  cell     sample stage stage.mapped stage.collapsed stage.mapped.collapsed
1 cell_363 2      E7.5  E7.5         E7.5            E7.5
2 cell_382 2      E7.5  E7.5         E7.5            E7.5
3 cell_385 2      E7.5  E7.5         E7.5            E7.5
4 cell_393 2      E7.5  E7.5         E7.5            E7.5
5 cell_398 2      E7.5  E7.5         E7.5            E7.5
6 cell_407 2      E7.5  E7.5         E7.5            E7.5
  somite_count tube_name    tube_name_corrected celltype
1 Undetermined Undetermined Undetermined        Blood progenitors 2
2 Undetermined Undetermined Undetermined        Blood progenitors 2
3 Undetermined Undetermined Undetermined        Blood progenitors 2
4 Undetermined Undetermined Undetermined        Blood progenitors 2
5 Undetermined Undetermined Undetermined        Blood progenitors 2
6 Undetermined Undetermined Undetermined        Haematoendothelial progenitors
  celltype.extended              celltype.descendant
1 Blood progenitors 2            Blood progenitors 2
2 Blood progenitors 2            Blood progenitors 2
3 Blood progenitors 2            Blood progenitors 2
4 Blood progenitors 2            Blood progenitors 2
5 Blood progenitors 2            Blood progenitors 2
6 Haematoendothelial progenitors Haematoendothelial progenitors
  celltype.descendant.somites    doub.density cluster cluster.sub
1 Blood progenitors 2            0.5678490     2      3
2 Blood progenitors 2            0.5281952     4      1
3 Blood progenitors 2            0.7745255     4      1
4 Blood progenitors 2            0.2881783     2      3
5 Blood progenitors 2            0.1011993     2      3
6 Haematoendothelial progenitors 1.0269756    23      1
  celltype.clustering
1 Blood progenitors
2 Blood progenitors
3 Blood progenitors
4 Blood progenitors
5 Blood progenitors
6 Haematoendothelial progenitors

In [20]:
colnames(meta)

 [1] "cell"                        "sample"
 [3] "stage"                       "stage.mapped"
 [5] "stage.collapsed"             "stage.mapped.collapsed"
 [7] "somite_count"                "tube_name"
 [9] "tube_name_corrected"         "celltype"
[11] "celltype.extended"           "celltype.descendant"
[13] "celltype.descendant.somites" "doub.density"
[15] "cluster"                     "cluster.sub"
[17] "celltype.clustering"

In [27]:
library(purrr)
library(stringr)

In [34]:
tail(str_split(as.character(meta$cell),'_')) %>%  map_chr(1)

[1] "ext" "ext" "ext" "ext" "ext" "ext"

In [40]:

main = '/rds/project/rds-SDzz0CATGms/users/bt392/atlasses/extended/'
out = file.path(main, 'blood/')

print('reading meta')
meta = readRDS(paste0(main, 'integrated_meta_celltype_clus.rds')) %>% as.data.table(keep.rownames=T) %>% setnames('rn', 'cell')
meta = meta[, c('cell', 'sample', 'stage', 'celltype.descendant', 'celltype.clustering')]
colnames(meta) = c('cell', 'sample', 'stage', 'celltype_original', 'celltype')

[1] "reading meta"

In [43]:
meta = meta[celltype %in% ct_keep] %>%
    .[,dataset:=str_split(as.character(cell),'_') %>%  map_chr(1)] %>%
    .[,dataset:=ifelse(dataset=='ext', 'ext', 'blanca')]

In [54]:
test = matrix(c(1,2,3),c(4,5,6), c(5,7,3))
test

Warning message in matrix(c(1, 2, 3), c(4, 5, 6), c(5, 7, 3)):
“data length [3] is not a sub-multiple or multiple of the number of rows [4]”

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    1    2
[2,] 2    3    1    2    3
[3,] 3    1    2    3    1
[4,] 1    2    3    1    2

In [59]:
getwd()

[1] "/rds/project/rds-SDzz0CATGms/users/bt392/atlasses/extended"