In [1]:
import scanpy as sc

In [9]:
import scipy

In [34]:
import pandas as pd

In [ ]:
test_mtx = sc.read_mtx("/rds/project/rds-SDzz0CATGms/users/bt392/atlasses/gastrulation_multiome/whole_atlas_atac_mtx.mtx")

In [2]:
test_mtx_adata = sc.read_h5ad("/rds/project/rds-SDzz0CATGms/users/bt392/atlasses/gastrulation_multiome/data/processed/atac/anndata/PeakMatrix/PeakMatrix_anndata.h5ad")

In [3]:
test_mtx_adata

AnnData object with n_obs × n_vars = 57536 × 192251
    obs: 'BlacklistRatio', 'nDiFrags', 'nFrags', 'nMonoFrags', 'nMultiFrags', 'NucleosomeRatio', 'PassQC', 'PromoterRatio', 'ReadsInBlacklist', 'ReadsInPromoter', 'ReadsInTSS', 'Sample', 'TSSEnrichment', 'barcode', 'sample', 'nFeature_RNA', 'nCount_RNA', 'mitochondrial_percent_RNA', 'ribosomal_percent_RNA', 'stage', 'genotype', 'pass_rnaQC', 'doublet_score', 'doublet_call', 'celltype.mapped', 'celltype.score', 'closest.cell', 'TSSEnrichment_atac', 'ReadsInTSS_atac', 'PromoterRatio_atac', 'NucleosomeRatio_atac', 'nFrags_atac', 'BlacklistRatio_atac', 'ReadsInPeaks', 'FRIP'
    var: 'idx'
    uns: 'celltype_colors', 'stage_colors'

In [ ]:
test_mtx_adata.obs

In [8]:
test_mtx_adata.X[1:10, 1:10]

<9x9 sparse matrix of type '<class 'numpy.float32'>'
	with 1 stored elements in Compressed Sparse Column format>

In [10]:
test = scipy.sparse.csr_matrix(test_mtx_adata.X)

In [28]:
from scipy.sparse import csr_matrix
test = csr_matrix(test_mtx_adata.X)

In [33]:
test[1:5,:]

<4x192251 sparse matrix of type '<class 'numpy.float32'>'
	with 47770 stored elements in Compressed Sparse Row format>

In [35]:
test2 = pd.DataFrame.sparse.from_spmatrix(test)

In [45]:
cells = test_mtx_adata.obs.index
regions = test_mtx_adata.var.index

In [48]:
test2.index = cells
test2.columns =regions

In [58]:
test3 = test2.transpose()

In [59]:
test3.head()

,E7.5_rep1#AAACAGCCATCCTGAA-1,E7.5_rep1#AAACAGCCATGCTATG-1,E7.5_rep1#AAACATGCAATGAATG-1,E7.5_rep1#AAACATGCAATTATGC-1,E7.5_rep1#AAACATGCACCTATAG-1,E7.5_rep1#AAACATGCAGGATAAC-1,E7.5_rep1#AAACATGCATGAATAG-1,E7.5_rep1#AAACCAACATAATCGT-1,E7.5_rep1#AAACCGAAGAGGGACT-1,E7.5_rep1#AAACCGAAGCACTAGT-1,...,E8.75_rep2#TTTGTGAAGCTATGAC-1,E8.75_rep2#TTTGTGAAGCTTACTT-1,E8.75_rep2#TTTGTGAAGCTTAGTA-1,E8.75_rep2#TTTGTGGCAAACGCGA-1,E8.75_rep2#TTTGTGGCATCTTGAG-1,E8.75_rep2#TTTGTGTTCGTGCTTC-1,E8.75_rep2#TTTGTGTTCTGTGCAG-1,E8.75_rep2#TTTGTTGGTCTCAGCC-1,E8.75_rep2#TTTGTTGGTTCACTGT-1,E8.75_rep2#TTTGTTGGTTGAGCCG-1
chr1:3035602-3036202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
chr1:3062653-3063253,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
chr1:3072313-3072913,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
chr1:3191496-3192096,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
chr1:3340575-3341175,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
test2

,chr1:3035602-3036202,chr1:3062653-3063253,chr1:3072313-3072913,chr1:3191496-3192096,chr1:3340575-3341175,chr1:3443943-3444543,chr1:3482876-3483476,chr1:3514773-3515373,chr1:3549329-3549929,chr1:3566755-3567355,...,chrX:169827502-169828102,chrX:169844068-169844668,chrX:169879268-169879868,chrX:169880290-169880890,chrX:169883277-169883877,chrX:169902806-169903406,chrX:169905921-169906521,chrX:169915616-169916216,chrX:169925487-169926087,chrX:169937064-169937664
E7.5_rep1#AAACAGCCATCCTGAA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E7.5_rep1#AAACAGCCATGCTATG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E7.5_rep1#AAACATGCAATGAATG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E7.5_rep1#AAACATGCAATTATGC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E7.5_rep1#AAACATGCACCTATAG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E8.75_rep2#TTTGTGTTCGTGCTTC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E8.75_rep2#TTTGTGTTCTGTGCAG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E8.75_rep2#TTTGTTGGTCTCAGCC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E8.75_rep2#TTTGTTGGTTCACTGT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
E8.75_rep2#TTTGTTGGTTGAGCCG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,2.0,4.0,0.0,0.0,0.0

In [14]:
from pycisTopic.cistopic_class import *

In [51]:
cistopic_obj = create_cistopic_object(fragment_matrix=test2)

2022-08-31 12:39:45,037 cisTopic     INFO     Converting fragment matrix to sparse matrix
2022-08-31 12:45:47,092 cisTopic     INFO     Creating CistopicObject

ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements

In [12]:
test.

AttributeError: X not found

In [ ]:
test_mtx