In [1]:
suppressPackageStartupMessages(library(scran))
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(batchelor))
suppressPackageStartupMessages(library(argparse))

here::i_am("mapping/run/mnn/mapping_mnn.R")

# Load mapping functions
source(here::here("mapping/run/mnn/mapping_functions_extended.R"))

# Load default settings
source(here::here("settings.R"))
source(here::here("utils.R"))

here() starts at /rds/project/rds-SDzz0CATGms/users/bt392/01_Eomes_RNA/code

In [2]:
# I/O
io$path2atlas <- io$atlas.basedir
io$path2query <- io$basedir

# START TEST ##
args = list()
args$atlas_stages <- c("E8.5")
args$query_samples <- opts$samples[1]
args$query_sce <- io$rna.sce
args$query_sce <- paste0(io$basedir,"/processed/SingleCellExperiment.rds")
args$atlas_sce <- io$rna.atlas.sce
args$query_metadata <- paste0(io$basedir,"/results/rna/doublet_detection/sample_metadata_after_doublets.txt.gz")
args$atlas_metadata <- io$rna.atlas.metadata
args$test <- FALSE
args$npcs <- 5
args$n_neighbours <- 25
args$use_marker_genes <- FALSE
args$cosine_normalisation <- FALSE
args$outdir <- paste0(io$basedir,"/results/rna/mapping/test")
# END TEST ##

In [3]:
args$query_samples

[1] "SLX-20795_SITTH11_HKTG2DRXY"

In [4]:
################
## Load query ##
################

# Load cell metadata
meta_query <- fread(args$query_metadata) %>% 
  .[pass_rnaQC==TRUE & doublet_call==FALSE & sample%in%args$query_samples]
if (isTRUE(args$test)) meta_query <- head(meta_query,n=1000)

# Load SingleCellExperiment
sce_query <- load_SingleCellExperiment(args$query_sce, cells = meta_query$cell, remove_non_expressed_genes = TRUE)

# Update colData
tmp <- meta_query %>% .[cell%in%colnames(sce_query)] %>% setkey(cell) %>% .[colnames(sce_query)]
stopifnot(tmp$cell == colnames(sce_query))
colData(sce_query) <- tmp %>% as.data.frame %>% tibble::column_to_rownames("cell") %>%
  .[colnames(sce_query),] %>% DataFrame()

################
## Load atlas ##
################

# Load cell metadata
meta_atlas <- fread(args$atlas_metadata) %>%
  .[stage%in%args$atlas_stages] %>%
  .[,sample:=factor(sample)] 

# Filter
if (isTRUE(args$test)) meta_atlas <- head(meta_atlas,n=1000)

# Load SingleCellExperiment
sce_atlas <- load_SingleCellExperiment(args$atlas_sce, normalise = TRUE, cells = meta_atlas$cell, remove_non_expressed_genes = TRUE)

# Update colData
tmp <- meta_atlas %>% .[cell%in%colnames(sce_atlas)] %>% setkey(cell) %>% .[colnames(sce_atlas)]
stopifnot(tmp$cell == colnames(sce_atlas))
colData(sce_atlas) <- tmp %>% as.data.frame %>% tibble::column_to_rownames("cell") %>%
  .[colnames(sce_atlas),] %>% DataFrame()

# Sanity cehcks
stopifnot(sum(is.na(rownames(sce_atlas)))==0)
stopifnot(sum(duplicated(rownames(sce_atlas)))==0)

In [5]:
#####################
## Define gene set ##
#####################

# Get gene metadata
gene_metadata <- fread(io$gene_metadata) %>% .[,c("chr","ens_id","symbol")] %>%
  .[symbol!="" & ens_id%in%rownames(sce_atlas)] %>%
  .[!duplicated(symbol)]

rownames(sce_atlas) = gene_metadata[match(rownames(sce_atlas), ens_id), symbol]

# Imprinted genes
imprint = gene_metadata[c(grep('maternally', gene_metadata$description),
                       grep('paternally', gene_metadata$description)), symbol]
#Other imprinted genes: 
#- Nnat (https://www.genecards.org/cgi-bin/carddisp.pl?gene=NNAT)
#- Grb10 (https://www.genecards.org/cgi-bin/carddisp.pl?gene=GRB10)

# Intersect genes
genes.intersect <- intersect(rownames(sce_query), rownames(sce_atlas))

# Filter some genes manually
genes.intersect <- genes.intersect[grep("^Rik|Rik$|^mt-|^Rps|^Rpl|^Gm",genes.intersect,invert=T)] # filter out non-informative genes
genes.intersect <- genes.intersect[grep("^Hbb|^Hba",genes.intersect,invert=T)] # test removing Haem genes 
genes.intersect <- genes.intersect[!genes.intersect %in% c(imprint, 'Grb10', 'Nnat')] # remove imprinted genes
genes.intersect <- genes.intersect[!genes.intersect %in% c("Xist", "Tsix")] # remove Xist & Tsix
genes.intersect <- genes.intersect[!genes.intersect=="tomato-td"] # remove tomato itself
genes.intersect <- genes.intersect[!genes.intersect %in% gene_metadata[chr=="chrY",symbol]] # no genes on y-chr

In [7]:
length(genes.intersect)

[1] 11889

In [8]:
# Subset SingleCellExperiment objects
sce_query  <- sce_query[genes.intersect,]
sce_atlas <- sce_atlas[genes.intersect,]

In [17]:
  # Calculate mean-variance relationship and extract HVGs
  decomp <- modelGeneVar(sce_atlas, block=sce_atlas$sample)
  genes_to_use <- decomp[order(decomp$FDR),] %>% head(n=2500) %>% rownames
genes_to_use

   [1] "Mdk"          "Tmsb4x"       "Car2"         "Marcksl1"
   [5] "Id3"          "Mest"         "Tmsb10"       "Serpinh1"
   [9] "Phlda2"       "Crabp1"       "Tuba1a"       "Fth1"
  [13] "Gpx1"         "Myl7"         "Actc1"        "Bex1"
  [17] "Blvrb"        "Tmem14c"      "Krt18"        "Myl4"
  [21] "Cdkn1c"       "Acta2"        "Meg3"         "Cited4"
  [25] "Ttr"          "Crabp2"       "Bex3"         "Mgst3"
  [29] "Actg1"        "Ifitm1"       "Apom"         "Ptn"
  [33] "Rbp4"         "Ccnd2"        "Apoa1"        "Apoe"
  [37] "Krt8"         "Acta1"        "Prdx2"        "Glrx5"
  [41] "Id2"          "Hoxaas3"      "H19"          "Hmbs"
  [45] "Cited2"       "Tnnc1"        "Myl2"         "Amn"
  [49] "Lgals2"       "Car4"         "Slc2a3"       "Tpm1"
  [53] "Cldn6"        "Cited1"       "Ube2c"        "Bex4"
  [57] "Gpx3"         "S100g"        "Apoa2"        "Smim1"
  [61] "Rhox5"        "Dlk1"         "Cd24a"        "Prdx1"
  [65] "Cryab"        "Spink1"       "Ctsh"         "Afp"
  [69] "Tnni1"        "Pyy"          "Fbxl22"       "Igfbp2"
  [73] "Dppa3"        "Cpox"         "H2afv"        "Pgam1"
  [77] "Malat1"       "Pmp22"        "Ifitm2"       "Cldn5"
  [81] "Tcf15"        "Hand1"        "Tagln"        "Chchd10"
  [85] "Sparc"        "Alad"         "Slc2a1"       "Trap1a"
  [89] "Snca"         "Hebp1"        "Hspa5"        "Fabp5"
  [93] "Pkm"          "Vim"          "Csrp2"        "Car7"
  [97] "Hoxb5os"      "Lgals1"       "Fgb"          "Nkx2-9"
 [101] "Tnni3"        "Meox1"        "Pdia6"        "Cnn2"
 [105] "Cd63"         "Arg1"         "Fxyd2"        "Epcam"
 [109] "Cubn"         "Acp5"         "Slc25a5"      "Sh3bgr"
 [113] "Fgf8"         "Wnt6"         "Folr1"        "Slc25a4"
 [117] "Emb"          "Fst"          "Tpm4"         "Crip2"
 [121] "Cyp26a1"      "Etv2"         "Tdo2"         "Cnn3"
 [125] "Tdh"          "Hspb1"        "Plac1"        "Apob"
 [129] "Ass1"         "Mt1"          "Cldn7"        "Bhlha9"
 [133] "Cck"          "Tmem37"       "Plvap"        "Id1"
 [137] "T"            "Bex2"         "Krt19"        "Msx1"
 [141] "Cdx4"         "Anxa2"        "Msx3"         "Rrm2"
 [145] "Cd81"         "Cdx2"         "Hes3"         "Myl9"
 [149] "Hoxc8"        "Hspb2"        "Fscn1"        "Cnn1"
 [153] "Myl6"         "Plek"         "Mt2"          "Col1a1"
 [157] "Slc16a3"      "Npl"          "Rspo3"        "Hes7"
 [161] "Dll3"         "Pgk1"         "Sfrp5"        "Pdzk1"
 [165] "Sfn"          "Pnpo"         "Selenop"      "S100a10"
 [169] "Fmr1nb"       "Ddt"          "Rrad"         "Atpif1"
 [173] "Actn2"        "Phlda1"       "Sostdc1"      "Fech"
 [177] "Foxf1"        "Vgll3"        "Ftl1"         "Dqx1"
 [181] "Pitx1"        "Stmn1"        "Trh"          "S100a1"
 [185] "Nebl"         "Ctsl"         "Dab2"         "Fam210b"
 [189] "Arl6ip1"      "Calca"        "Actb"         "Tsen34"
 [193] "Slc39a8"      "Olfr1369-ps1" "Ube2l6"       "Fgf17"
 [197] "Ecscr"        "Cd34"         "Ramp2"        "Aqp3"
 [201] "Lmo2"         "Vamp8"        "Rax"          "Nkx6-2"
 [205] "Gpc3"         "Spin2c"       "Psmb8"        "Rbp1"
 [209] "Ccnd3"        "Slc38a5"      "Hoxb9"        "Nexn"
 [213] "Wisp1"        "H1f0"         "Psip1"        "Krt7"
 [217] "Prrx2"        "Cald1"        "Tead2"        "En1"
 [221] "Apela"        "Hdgf"         "Lgmn"         "Wfdc2"
 [225] "Slc25a37"     "Hapln1"       "Hoxc9"        "Gpx2"
 [229] "Apoc1"        "Bambi"        "Tceal8"       "Fam162a"
 [233] "Gngt2"        "H2afy2"       "Dkk4"         "Hoxa9"
 [237] "Sox17"        "Gp1bb"        "Prdx6"        "Gipc2"
 [241] "Gng11"        "Dcn"          "Fam181b"      "Tagln2"
 [245] "Cyba"         "Shh"          "Mllt3"        "Hhex"
 [249] "Klf2"         "Rnase4"       "Gal"          "Six3"
 [253] "Vsnl1"        "Tbx1"         "Cldn4"        "Anp32b"
 [257] "Hes5"         "Tbx6"         "H2afy"        "Cotl1"
 [261] "Srm"          "Retn"         "Cdkn1a"       "Hsp90b1"
 [265] "Dkk1"         "Slc9a3r1"     "Cxcl12"       "Aldh1a2"
 [269] "Epha5"        "Smoc2"        "Hesx1"        "Spint2"
 [273] "Itm2a"        "Creg1"        "Manf"         "Stmn2"
 [277] "Pitx2"        "Vamp5"        "Osr1"         "Ctsb"
 [281] "Ckb"          "Nkx2-3"       "Gclm"         "Hoxa7"
 [285] "Igfbp5"       "Urod"         "Mafb"         "Vcam1"
 [289] "Tubb4b"       "Smyd1"        "Fgf15"        "Mixl1"
 [293] "Msx2"         "Lhx2"         "Dlx5"         "Sox4"
 [297] "Atp1a2"       "Prss8"        "Peg3"         "Ccnb1"
 [301] "Sprr2a3"      "Mesp1"        "Tubb6"        "Cystm1"
 [305] "S100a11"      "Plac8"        "Gas6"         "Lgals3"
 [309] "Clic6"        "Map1b"        "Cdk1"         "H2afx"
 [313] "Hoxb8"        "Fn1"          "Rab27b"       "Col1a2"
 [317] "Fam212a"      "Crip1"        "Ctsc"         "Arhgdib"
 [321] "Calr"         "Atp1b1"       "Arf5"         "Rgs5"
 [325] "Dstn"         "Ncl"          "Kdr"          "Bmp4"
 [329] "Des"          "Asns"         "Clic1"        "Fgfbp3"
 [333] "Sct"          "Hoxb1"        "Gadd45g"      "Dll1"
 [337] "Tmem108"      "Twist2"       "S100a16"      "Calm2"
 [341] "Pcbd1"        "Epor"         "Wnt8b"        "Tlx2"
 [345] "Sp5"          "Mef2c"        "Foxi2"        "Ier2"
 [349] "Rasip1"       "Hist1h2bc"    "Prdx3"        "Tfap2b"
 [353] "Asb4"         "Hoxc10"       "Gypc"         "Cst3"
 [357] "Ppp1r14c"     "Tac2"         "Gstm1"        "Cdc20"
 [361] "Nrk"          "Fxyd5"        "Tmprss2"      "Anxa5"
 [365] "Flt1"         "Hoxd1"        "Tsc22d1"      "Tal2"
 [369] "Aldh1a3"      "Tacstd2"      "Cdx1"         "Hn1"
 [373] "Crb3"         "Mif"          "Hist1h2ap"    "Ripply3"
 [377] "Ptcra"        "Cthrc1"       "Tmem88"       "Lyar"
 [381] "Csrp1"        "Krtap17-1"    "Tm4sf5"       "Igfbp4"
 [385] "Arpc1b"       "Cks2"         "Ebf1"         "Smarcd3"
 [389] "Slc13a4"      "Nkx6-1"       "Nop10"        "Rasgrp2"
 [393] "Slc29a1"      "Pcolce"       "Marcks"       "Cbx1"
 [397] "Tmem150a"     "Hspd1"        "Hoxb2"        "Hmga2"
 [401] "Ppic"         "Hmgb3"        "Hoxa10"       "Eno1"
 [405] "Olfr889"      "Igf2"         "Tspan3"       "Pdlim1"
 [409] "Ccnd1"        "Isl1"         "Fgf3"         "Kpna2"
 [413] "Hnrnpa1"      "Limd2"        "Egr2"         "Sox9"
 [417] "Sigirr"       "Fgfbp1"       "Hsd11b2"      "Pcsk1n"
 [421] "Olfr655"      "Sfrp1"        "Bin2"         "Mycn"
 [425] "Cpn1"         "Espn"         "Pcdhgb5"      "Fkbp1a"
 [429] "Pax8"         "Pax6"         "Golga3"       "Arf4"
 [433] "Mab21l2"      "Myl12a"       "Ell2"         "Uap1l1"
 [437] "Otx2"         "Tinagl1"      "Popdc2"       "Prtg"
 [441] "Tnfrsf9"      "Mbnl3"        "Tal1"         "Plp2"
 [445] "Basp1"        "Krt23"        "Fabp3"        "Cldn3"
 [449] "Cadm1"        "Car14"        "Tfpi"         "Fli1"
 [453] "Elk3"         "Nhp2"         "Upp1"         "Sdpr"
 [457] "Maged2"       "Tubb3"        "Dusp9"        "Ppp1r14a"
 [461] "Tgfb2"        "Aplnr"        "Pdgfa"        "Cpm"
 [465] "Dlx2"         "Igfbpl1"      "Smox"         "Creb3l1"
 [469] "Lxn"          "Tmem54"       "Nxf7"         "Prkcdbp"
 [473] "Plin2"        "Gyg"          "Gjb3"         "Reep6"
 [477] "Laptm4b"      "Ywhaq"        "Bnip3l"       "Hoxb6"
 [481] "Ahnak"        "Aard"         "Nkx1-2"       "Eva1b"
 [485] "Fos"          "Glrx"         "Sox2"         "Slc7a7"
 [489] "Cmtm7"        "Cyr61"        "Lhx5"         "Rcn2"
 [493] "Rhoc"         "Dctpp1"       "Steap1"       "Bst2"
 [497] "Pcp4"         "Tmem267"      "Nkx6-3"       "Gpx4"
 [501] "Eng"          "Tmem100"      "Cldn10"       "Maged1"
 [505] "Upk1a"        "Ezr"          "Plp1"         "Pcdh19"
 [509] "Ctsz"         "Prdx4"        "Xlr3a"        "Tmod1"
 [513] "Ifitm3"       "Ldha"         "Ccdc141"      "Gsta4"
 [517] "Adm"          "Gap43"        "Aprt"         "Pecam1"
 [521] "Slc39a4"      "Ly6h"         "Shisa2"       "Tmem158"
 [525] "Tspan13"      "Hoxc6"        "Capn6"        "Gbp2"
 [529] "Nrp1"         "Stard10"      "Car3"         "Tubb5"
 [533] "Laptm4a"      "Ubc"          "Hoxd9"        "Foxb1"
 [537] "Gata5"        "Evx1os"       "Atp6v0b"      "Ehbp1"
 [541] "Itm2b"        "Akr1b3"       "Stx3"         "Phlda3"
 [545] "Rhoj"         "Tcf21"        "Tgfb1i1"      "Prkar2b"
 [549] "Peg10"        "Idh2"         "Rhd"          "Ldoc1"
 [553] "Hlx"          "Plet1"        "Klhl4"        "Sh3bgrl3"
 [557] "Rgs10"        "Icam4"        "Tax1bp3"      "Fermt1"
 [561] "Efna1"        "Abcb10"       "Kdelr3"       "Dut"
 [565] "Eras"         "Cap2"         "Cxcl14"       "Reep5"
 [569] "Egfl7"        "Cldn9"        "Gnai2"        "Nkg7"
 [573] "Pcbp4"        "Ppib"         "Foxd3"        "Adora2b"
 [577] "Cdc42ep3"     "Smagp"        "Tuba4a"       "Tpi1"
 [581] "Fabp7"        "Penk"         "Acan"         "Six1"
 [585] "Npm3"         "Fhl2"         "Gja1"         "Hoxd4"
 [589] "Snx3"         "Nrarp"        "Rbbp7"        "Rab25"
 [593] "Mogat2"       "Tspan6"       "Pqlc2"        "Eno3"
 [597] "Arhgap30"     "Irx3"         "Rbpms"        "Perp"
 [601] "Bmp2"         "Atp5l"        "Dusp2"        "Cdo1"
 [605] "Rcn3"         "Abcg2"        "Plk2"         "Gsn"
 [609] "Gdf3"         "Cenpa"        "Ptges3l"      "Rbm24"
 [613] "Gata4"        "Mpped2"       "Dhrs11"       "Sgce"
 [617] "Bub3"         "Rcsd1"        "Dcakd"        "Anxa3"
 [621] "Cgref1"       "Alox5ap"      "Timm8a1"      "Lmo1"
 [625] "Uros"         "Nkx3-1"       "Nkd1"         "Wnt5b"
 [629] "Ptpn18"       "Tmem163"      "Metrnl"       "Tubb2b"
 [633] "Foxd1"        "Bcam"         "Gata6"        "Tmem114"
 [637] "Glipr2"       "Pdlim4"       "Lef1"         "Tmem119"
 [641] "Pdlim7"       "Evx1"         "Guca1a"       "Sgk1"
 [645] "Cd9"          "Sap30"        "Set"          "Slc38a4"
 [649] "Rflna"        "Clu"          "Sec14l2"      "Dnajc22"
 [653] "Ptov1"        "Fkbp6"        "Nr2f1"        "Aurka"
 [657] "Arl4d"        "Sfrp2"        "Lrpap1"       "Myzap"
 [661] "Slbp"         "Tspan33"      "Selenoh"      "Bnip3"
 [665] "Lix1"         "Prss50"       "Rfesd"        "Tnfrsf12a"
 [669] "Hes1"         "Meis2"        "Mfap2"        "Fhl1"
 [673] "Pcgf5"        "Pglyrp1"      "Pla2g7"       "Alx1"
 [677] "Msmo1"        "Hoxa5"        "Fbxo32"       "Fezf2"
 [681] "Pdlim2"       "Nup62cl"      "Rgcc"         "Trp63"
 [685] "Fxyd6"        "Gulo"         "Tcea3"        "Mgst1"
 [689] "Rexo2"        "Ak1"          "Tomm5"        "Igfbp3"
 [693] "Ndufa4l2"     "Snai1"        "Dok4"         "Hoxa2"
 [697] "Col9a1"       "Emx2"         "Btbd17"       "Greb1"
 [701] "Rbms1"        "Psph"         "Xlr4b"        "Pou5f1"
 [705] "Hoxa11"       "Ppox"         "Nectin2"      "Phkg1"
 [709] "Anxa6"        "Zfp750"       "Ldhb"         "Xlr4a"
 [713] "Ppp1r1a"      "Ccdc80"       "Shox2"        "Pgrmc1"
 [717] "Rab20"        "Gadd45a"      "Fezf1"        "Dppa5a"
 [721] "Ddit4"        "Jun"          "H3f3a"        "Pld1"
 [725] "Cenpf"        "Lbh"          "Aqp11"        "Cd59a"
 [729] "Smc4"         "Phactr1"      "Acp1"         "Frzb"
 [733] "Prrx1"        "Klf6"         "Tm6sf1"       "Utf1"
 [737] "Mnx1"         "Nrgn"         "Rtn4"         "Ppid"
 [741] "Morc4"        "Sox11"        "Cdkn2a"       "Tfap2c"
 [745] "P2rx4"        "Phgdh"        "Gcat"         "Col2a1"
 [749] "Prnp"         "Cmtm8"        "Cd38"         "Fgf18"
 [753] "Tcn2"         "Fev"          "Slc16a1"      "Twist1"
 [757] "Ndn"          "Rbm47"        "Hprt"         "Lefty2"
 [761] "Rbm38"        "Nudt4"        "Dbi"          "Dynll1"
 [765] "H1fx"         "Pgf"          "Cyb5a"        "Tdrd12"
 [769] "Cox17"        "Efnb1"        "Wnt3a"        "Ung"
 [773] "Mid1ip1"      "Hoxa1"        "Alcam"        "Rprm"
 [777] "Rprml"        "Uqcrb"        "Sod3"         "Irx5"
 [781] "F2rl1"        "Col5a2"       "Bcl11a"       "Cygb"
 [785] "Defb42"       "Top2a"        "Tpm2"         "Ifi35"
 [789] "Aldoc"        "Rbpms2"       "Homer2"       "Arl4a"
 [793] "Ddah2"        "Plagl1"       "Tgfb1"        "Selenow"
 [797] "Apex1"        "Grrp1"        "Dek"          "Pdzph1"
 [801] "Gnas"         "Trim54"       "Rnf128"       "Emp2"
 [805] "Neu1"         "Hmgn3"        "Irx2"         "Tmem213"
 [809] "F11r"         "Anp32a"       "Atp5g1"       "Pcp4l1"
 [813] "Acer2"        "Klk13"        "Pax3"         "Ifitm5"
 [817] "Cntnap2"      "Cox7a1"       "Gng12"        "Klk14"
 [821] "Thbs1"        "Rrbp1"        "Cox4i2"       "Pdlim3"
 [825] "Foxd4"        "Pou3f1"       "Nog"          "Pa2g4"
 [829] "Rab17"        "Ntng1"        "Col26a1"      "Gpx8"
 [833] "Naaa"         "Cstb"         "Flt4"         "Calm1"
 [837] "Depdc7"       "Dusp6"        "C1qbp"        "Cbr3"
 [841] "Mfng"         "Trp53i11"     "Npc2"         "Hoxd10"
 [845] "Gldc"         "Ssx2ip"       "Josd2"        "Pfkl"
 [849] "Otx1"         "Akr1b8"       "Sparcl1"      "Ddah1"
 [853] "Slpi"         "Cox8a"        "Ptp4a3"       "Bves"
 [857] "Etv4"         "Sms"          "Id4"          "Gstt1"
 [861] "Mir124-2hg"   "Nrros"        "Oat"          "Pycr2"
 [865] "Ptch1"        "Ptgs1"        "S100a13"      "Ddx39b"
 [869] "Thnsl2"       "Lypd6b"       "Ager"         "Hmgb2"
 [873] "Arl4c"        "Stard8"       "Tgm3"         "Prss23"
 [877] "Cideb"        "Tbx20"        "Mfap4"        "Mapk13"
 [881] "Sult5a1"      "Lpar3"        "Lrrn4"        "Grhl3"
 [885] "Xlr3b"        "Tubb2a"       "Hand2"        "Fam64a"
 [889] "S1pr3"        "Cfap57"       "Ly6e"         "Hmgn1"
 [893] "Ncam1"        "Vwc2"         "Rab4a"        "Dcp1b"
 [897] "Epha7"        "Socs2"        "Tbx4"         "P3h3"
 [901] "Slc43a3"      "Tc2n"         "Npnt"         "Asb12"
 [905] "Sox18"        "Sp9"          "Higd1a"       "Uqcrq"
 [909] "Cfc1"         "Agl"          "Flrt3"        "Limch1"
 [913] "Fez1"         "Hoxb4"        "Gabarap"      "Psmb9"
 [917] "Ddit4l"       "Ucp2"         "Bri3"         "Fam162b"
 [921] "Morf4l2"      "Bpgm"         "Mmp11"        "Fam134b"
 [925] "Sord"         "Qprt"         "Syt5"         "Spats2l"
 [929] "Traf3ip2"     "Fgf4"         "Tfap2a"       "Casz1"
 [933] "Fgf9"         "Ngfr"         "Pdia3"        "Srrm4"
 [937] "Slc39a2"      "Lfng"         "Tmem245"      "Angpt2"
 [941] "Irf5"         "Erich2"       "Fcgrt"        "Amph"
 [945] "She"          "Flrt2"        "H2afj"        "Me1"
 [949] "Efemp2"       "Stx7"         "Lhx1"         "Notum"
 [953] "Efna3"        "Podxl"        "Cfl2"         "Myo6"
 [957] "Kcng2"        "Hey1"         "Hspa8"        "Cebpd"
 [961] "Frrs1"        "Smtnl2"       "Irs4"         "Lrmp"
 [965] "Gjb5"         "Ptpre"        "Phox2a"       "Vstm2b"
 [969] "Lypd1"        "Loxl2"        "P4hb"         "Abracl"
 [973] "Atf3"         "Pxdc1"        "Gas1"         "Fam43a"
 [977] "Tmed9"        "Mpc1"         "Igfbp7"       "Mmrn2"
 [981] "Nptx2"        "Gcsh"         "Tmem35a"      "Hcn4"
 [985] "Bola3"        "Wnt4"         "H2-D1"        "S100a6"
 [989] "Enpp2"        "Acot1"        "Spint1"       "Pdlim5"
 [993] "Cpne7"        "Batf3"        "Tbx3os1"      "Coro2a"
 [997] "Cacna2d2"     "Angpt1"       "Dbn1"         "Hnrnpdl"
[1001] "Tap2"         "Cntfr"        "Dnd1"         "Nfe2l3"
[1005] "Mtus2"        "Kcnk1"        "Coro1a"       "Ednrb"
[1009] "Cycs"         "Hpn"          "Hoxc4"        "Irx1"
[1013] "Fam89a"       "Irf8"         "Pcna"         "Slc9a3r2"
[1017] "Fam46a"       "Fbn2"         "Col4a1"       "Tbrg1"
[1021] "Grb14"        "Prdm6"        "Rfx4"         "Isg15"
[1025] "Sptb"         "Serpinf1"     "Rasd1"        "Cd40"
[1029] "Angptl6"      "Nkain4"       "Cdca7"        "Wls"
[1033] "Htra1"        "Pnmal2"       "Arhgef15"     "Wnt16"
[1037] "Ifi27l2a"     "Nusap1"       "Fam195a"      "Trp53inp1"
[1041] "Emilin1"      "Ltb"          "Pdpn"         "Irx4"
[1045] "Degs1"        "Bcas2"        "Ndufa12"      "Fas"
[1049] "Emp3"         "Plpp3"        "Sri"          "Sptssa"
[1053] "Sh3gl3"       "Cryba1"       "Lrrc34"       "Rgs2"
[1057] "Hoxd13"       "Rsph9"        "Plod2"        "Eps8"
[1061] "Elavl3"       "Copz2"        "Lmo4"         "Btg2"
[1065] "Ctso"         "Dapl1"        "Myo1c"        "Cracr2b"
[1069] "Ermn"         "Pmaip1"       "Ptges"        "Tuba1c"
[1073] "Ptms"         "Pnliprp1"     "Sat1"         "Clec2l"
[1077] "Mtl5"         "Ap1m2"        "Pcsk9"        "Rassf10"
[1081] "Pim1"         "Tgif1"        "Susd5"        "Glul"
[1085] "BC028528"     "Sod2"         "Plk1"         "Acvrl1"
[1089] "Neurod1"      "Tpd52"        "Zfp595"       "Smoc1"
[1093] "Foxc1"        "Rasl11a"      "Col4a2"       "Insl5"
[1097] "L1td1"        "Ltb4r2"       "Kif5b"        "Alx3"
[1101] "Acnat1"       "Lhx1os"       "Tg"           "Slit2"
[1105] "Svopl"        "F3"           "Fdps"         "Elovl1"
[1109] "Scarf1"       "Adamtsl2"     "Mpc2"         "Ackr3"
[1113] "Sgk3"         "Rem2"         "Aldoa"        "Plxnd1"
[1117] "Car5b"        "Pth1r"        "Idi1"         "Rspo1"
[1121] "Mrpl34"       "Rab37"        "Nasp"         "Moxd1"
[1125] "Pgm2"         "Tspan9"       "Nanog"        "Cdh1"
[1129] "Lad1"         "Jund"         "Junb"         "Myl12b"
[1133] "Cox6b2"       "Slc22a18"     "Kcns3"        "Fgf5"
[1137] "Nme5"         "Dgat2"        "Pcdh11x"      "Thy1"
[1141] "Ckap4"        "Egr1"         "Carhsp1"      "Tex264"
[1145] "Nop56"        "Wnt5a"        "Hist1h2ai"    "Gprc5a"
[1149] "Gna14"        "Ntf3"         "Capsl"        "Car8"
[1153] "Ipo11"        "Afap1l1"      "Arl3"         "Arhgap31"
[1157] "Galk1"        "Ptk7"         "Fstl1"        "Trib3"
[1161] "Snai2"        "Pop5"         "Tspan4"       "Nmral1"
[1165] "Kank3"        "Gstm5"        "P4ha2"        "Tmem120a"
[1169] "Ccne1"        "Fblim1"       "Sp6"          "Ndrg1"
[1173] "Nmi"          "Vcan"         "Steap2"       "Egr4"
[1177] "Rpia"         "Crym"         "Clmp"         "Dcaf12l1"
[1181] "Trim63"       "Hotairm1"     "Dleu7"        "Krt15"
[1185] "Hoxb7"        "Atox1"        "Cdh3"         "Krtcap2"
[1189] "Gucy1b3"      "Mmp14"        "Birc5"        "Cpa2"
[1193] "Foxf2"        "Hmgb1"        "Rarb"         "Tspan18"
[1197] "Sox21"        "Tecr"         "Bik"          "Rap1b"
[1201] "Rasgrp3"      "Mgarp"        "Timp3"        "Rabgap1l"
[1205] "Chst7"        "Grb7"         "Kcnk2"        "Cmtm3"
[1209] "Odc1"         "Tmem106a"     "Aff2"         "Got1l1"
[1213] "Plcd4"        "Dlx6"         "Ina"          "Kctd12b"
[1217] "Prph"         "Slc16a10"     "Gng4"         "Atxn7l3b"
[1221] "Cnpy2"        "Cul9"         "Mdfi"         "Mttp"
[1225] "Prkar1b"      "Myocd"        "Gfra3"        "Smim14"
[1229] "Bcat1"        "Arl5c"        "Plppr1"       "Lpar6"
[1233] "Bok"          "Slc43a2"      "Tnnt1"        "Ripk3"
[1237] "Cyp26b1"      "Ccng1"        "Rhbdl3"       "Cd151"
[1241] "Bace2"        "Ndrg2"        "Csn3"         "Selenos"
[1245] "Cndp2"        "Nab2"         "Gbp4"         "Uchl1"
[1249] "Eps8l2"       "Spon1"        "Palm3"        "Meis1"
[1253] "Lhfp"         "Cdh11"        "Minos1"       "Nt5c3"
[1257] "Snrnp25"      "Ociad2"       "Rarres2"      "Nlgn3"
[1261] "Fermt2"       "Gbx2"         "Bmper"        "Serpinc1"
[1265] "Dkc1"         "Vegfc"        "Alpk2"        "Nop58"
[1269] "Prps1"        "Tppp3"        "Bhmt2"        "Prr15l"
[1273] "Parm1"        "Cacybp"       "Amot"         "Cd79b"
[1277] "Ralb"         "Rab11a"       "Arhgef28"     "Mycl"
[1281] "March2"       "Capg"         "Rab3il1"      "Colec12"
[1285] "Stmn3"        "Col25a1"      "Zfpm1"        "Steap3"
[1289] "Plaur"        "Rab27a"       "Wnt3"         "Sh2d3c"
[1293] "Ube2s"        "Gas7"         "Zfp503"       "Art3"
[1297] "Renbp"        "Akr1c19"      "Card19"       "Cib1"
[1301] "Has2"         "Nr2f2"        "Calcrl"       "Gata3"
[1305] "Ets1"         "Lmcd1"        "Irgm1"        "Tgfbi"
[1309] "Mtch1"        "Bmp2k"        "Txndc17"      "Slc27a3"
[1313] "Sema4f"       "Ostf1"        "Sv2b"         "Ninj1"
[1317] "Epha2"        "S1pr5"        "Nrxn1"        "Upk3bl"
[1321] "Rbmxl1"       "Adssl1"       "Rdx"          "Notch1"
[1325] "Scara3"       "Rdh10"        "Hoxb3os"      "Ttc3"

In [25]:
library(Seurat)

Attaching SeuratObject


Attaching package: ‘Seurat’


The following object is masked from ‘package:SummarizedExperiment’:

    Assays

In [43]:
seurat_features = VariableFeatures(FindVariableFeatures(as.Seurat(sce_atlas), nfeatures = 2500))

In [42]:
summary(gene_stats.dt[match(VariableFeatures(seurat_features), gene),]$var_pseudobulk)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  0.010   0.540   1.110   1.435   1.930   8.940

In [46]:
  # Calculate mean-variance relationship and extract HVGs
  decomp <- modelGeneVar(sce_atlas)
  genes_to_use <- decomp[order(decomp$FDR),] %>% head(n=2500) %>% rownames

In [47]:
summary(gene_stats.dt[match(genes_to_use, gene),]$var_pseudobulk)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  0.000   0.160   0.500   1.072   1.552   8.940

In [48]:
head(gene_stats.dt[match(genes_to_use, gene),])

  ens_id             mean_single_cells var_single_cells mean_pseudobulk
1 ENSMUSG00000051855 1.70              2.81              7.67
2 ENSMUSG00000079523 4.34              1.71             10.69
3 ENSMUSG00000027562 1.87              2.68              7.55
4 ENSMUSG00000047945 3.98              1.17             10.03
5 ENSMUSG00000072235 2.61              2.23              8.60
6 ENSMUSG00000049775 2.11              2.00              8.49
  var_pseudobulk gene
1 4.27           Mest
2 0.88           Tmsb10
3 3.59           Car2
4 1.01           Marcksl1
5 2.75           Tuba1a
6 1.24           Tmsb4x

In [56]:
  decomp <- decomp[decomp$mean > 0.5,]
  decomp$FDR <- p.adjust(decomp$p.value, method = "fdr")
  genes_to_use <- decomp[order(decomp$FDR),] %>% head(n=2500) %>% rownames

In [57]:
head(gene_stats.dt[match(genes_to_use, gene),])

  ens_id             mean_single_cells var_single_cells mean_pseudobulk
1 ENSMUSG00000051855 1.70              2.81              7.67
2 ENSMUSG00000079523 4.34              1.71             10.69
3 ENSMUSG00000027562 1.87              2.68              7.55
4 ENSMUSG00000047945 3.98              1.17             10.03
5 ENSMUSG00000072235 2.61              2.23              8.60
6 ENSMUSG00000049775 2.11              2.00              8.49
  var_pseudobulk gene
1 4.27           Mest
2 0.88           Tmsb10
3 3.59           Car2
4 1.01           Marcksl1
5 2.75           Tuba1a
6 1.24           Tmsb4x

In [58]:
summary(gene_stats.dt[match(genes_to_use, gene),]$var_pseudobulk)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 0.0100  0.0600  0.1100  0.3682  0.2300  8.9400

In [59]:
summary(gene_stats.dt %>% setorder(-var_pseudobulk, na.last = T) %>% head(n=2500) %>% .$var_pseudobulk)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.71    0.94    1.29    1.67    1.99    8.94

In [34]:
head(gene_stats.dt)

  ens_id             mean_single_cells var_single_cells mean_pseudobulk
1 ENSMUSG00000085696 0.34              1.04             3.80
2 ENSMUSG00000025902 0.27              0.60             3.19
3 ENSMUSG00000062327 0.44              0.98             4.63
4 ENSMUSG00000005892 0.59              1.41             4.18
5 ENSMUSG00000021765 0.62              1.19             4.98
6 ENSMUSG00000025219 0.64              1.22             4.91
  var_pseudobulk gene
1 8.94           Hoxaas3
2 8.19           Sox17
3 7.92           T
4 7.67           Trh
5 7.36           Fst
6 7.02           Fgf8

In [15]:

  # Load gene statistics from the atlas
  gene_stats.dt <- fread(paste0(io$atlas.basedir,"/results/gene_statistics/gene_statistics.txt.gz")) %>%
    .[gene%in%genes.intersect]
  genes_to_use <- gene_stats.dt %>% setorder(-var_pseudobulk, na.last = T) %>% head(n=2500) %>% .$gene 
genes_to_use

   [1] "Hoxaas3"    "Sox17"      "T"          "Trh"        "Fst"
   [6] "Fgf8"       "Cdx1"       "Pou5f1"     "Mesp1"      "Cldn6"
  [11] "Cited4"     "Fgf5"       "Cdx2"       "Ptn"        "Epcam"
  [16] "Acta2"      "Utf1"       "Crabp2"     "Hand1"      "Cdx4"
  [21] "Crabp1"     "Hoxb5os"    "Sp5"        "Eomes"      "Fam212a"
  [26] "Phlda2"     "Mixl1"      "Hoxb8"      "Hoxb2"      "Hoxc8"
  [31] "Cfc1"       "Foxf1"      "Hoxb1"      "Tal1"       "Lmo2"
  [36] "Rspo3"      "Cldn7"      "Arg1"       "Hoxa1"      "Hapln1"
  [41] "Fgf3"       "Cyp26a1"    "Krt19"      "Hes3"       "Cryab"
  [46] "Snca"       "Gal"        "Krt8"       "Gata6"      "Prrx2"
  [51] "Lhx1"       "Ifitm1"     "Aplnr"      "Hoxb9"      "Hes7"
  [56] "Lefty2"     "Krt18"      "Otx2"       "Rhox5"      "Hoxb6"
  [61] "Crb3"       "Myl7"       "Hoxa7"      "Hhex"       "Smim1"
  [66] "Pmp22"      "Trap1a"     "Actc1"      "Dlk1"       "Foxb1"
  [71] "Hoxa9"      "Nkx1-2"     "Meis2"      "Dll3"       "Eras"
  [76] "Hoxc9"      "Tnni1"      "Apela"      "Plac1"      "Rab25"
  [81] "Aldh1a2"    "Dkk1"       "Igfbp2"     "Isl1"       "Mest"
  [86] "Myl4"       "Kdr"        "Gata4"      "Car4"       "Evx1"
  [91] "Sfrp1"      "Cited1"     "Cdh1"       "Upp1"       "Gsc"
  [96] "Ppp1r1a"    "Krt7"       "Pdlim4"     "Sfrp5"      "Pim2"
 [101] "Spink1"     "Calca"      "Gypc"       "Meox1"      "Fgf17"
 [106] "Sox2"       "Tbx6"       "Cthrc1"     "Hotairm1"   "Bmp4"
 [111] "Tinagl1"    "Nrp1"       "Hoxb4"      "Evx1os"     "Frzb"
 [116] "Car3"       "Mgst1"      "Lef1"       "Foxj1"      "Slc7a3"
 [121] "Igf2"       "Slc39a8"    "Sparc"      "Stmn2"      "Plet1"
 [126] "Pitx1"      "Etv2"       "Fabp7"      "Cdkn1c"     "Zic3"
 [131] "Pifo"       "Vim"        "Ldhb"       "Igfbp5"     "Rgs5"
 [136] "Id2"        "Msx1"       "Dppa5a"     "Bmp2"       "Mef2c"
 [141] "Pitx2"      "H19"        "Msx2"       "Ccnd2"      "Cpn1"
 [146] "Hoxd9"      "Gap43"      "Snai1"      "Hoxb3os"    "Pth1r"
 [151] "Car2"       "Flt1"       "Ina"        "Spin2c"     "Meg3"
 [156] "Zfp503"     "Ccnd1"      "Cldn5"      "Wfdc2"      "Fli1"
 [161] "Tcea3"      "Tmod1"      "Tagln"      "Wnt5b"      "Efna1"
 [166] "Fabp3"      "Sfn"        "Tnnc1"      "Ap1m2"      "Hoxa5"
 [171] "Hoxc6"      "Smarcd3"    "Cystm1"     "Ecscr"      "Pou3f1"
 [176] "Ube2l6"     "Hoxb7"      "Hand2"      "Fbn2"       "Irx3"
 [181] "Mt2"        "Igfbpl1"    "Hoxb5"      "Chchd10"    "Lhx1os"
 [186] "Epor"       "Sox4"       "Hesx1"      "Cntfr"      "Hoxd1"
 [191] "Gjb3"       "Sct"        "Shisa2"     "Cdh2"       "Gbx2"
 [196] "Cnn2"       "Amn"        "Arhgdib"    "Ctsh"       "Slc38a5"
 [201] "Wnt6"       "Cd59a"      "Fzd2"       "Fgf15"      "Mt1"
 [206] "Mfap2"      "Prdm6"      "Kdelr3"     "Tfpi"       "Anxa2"
 [211] "Gadd45g"    "Fgfbp1"     "Osr1"       "Ttr"        "Hoxd4"
 [216] "Gata2"      "Vrtn"       "Pdgfa"      "Blvrb"      "Sox9"
 [221] "Folr1"      "Hspb1"      "Tppp3"      "Pdpn"       "Igdcc3"
 [226] "Basp1"      "Capn6"      "Tmprss2"    "Acp5"       "Dll1"
 [231] "Grb7"       "Cldn4"      "Hoxa2"      "Asb4"       "Spint2"
 [236] "Gng11"      "Capsl"      "Nog"        "Cldn9"      "Bcat1"
 [241] "Col4a2"     "Fmr1nb"     "Sh3bgr"     "Vamp5"      "Epha5"
 [246] "Epha1"      "Tmem88"     "Perp"       "Rasgrp3"    "Dok4"
 [251] "Phlda1"     "Kcnk1"      "Gpx2"       "Ramp2"      "H2afy2"
 [256] "Emb"        "Apom"       "Cck"        "Gjc1"       "Cxcl12"
 [261] "Irx5"       "Apln"       "Ovol2"      "Wnt3a"      "Col9a1"
 [266] "Tgfb1"      "Cbfa2t3"    "Efna3"      "Prss8"      "Col4a1"
 [271] "Twist1"     "Car14"      "Hebp1"      "Bst2"       "Selenop"
 [276] "Fxyd6"      "Apoe"       "Nexn"       "Vcan"       "Wnt5a"
 [281] "Sox11"      "Etv4"       "Prkar2b"    "Smagp"      "Nefl"
 [286] "Lix1"       "Zfpm1"      "Tnfrsf12a"  "Pdgfra"     "Apoa1"
 [291] "Cmtm8"      "L1td1"      "Rasgrp2"    "Rbp1"       "Rhoj"
 [296] "Pmaip1"     "Slc2a3"     "Tdh"        "Bspry"      "Sparcl1"
 [301] "Esrp1"      "Sfrp2"      "Crmp1"      "Notum"      "Hes5"
 [306] "Stx3"       "Mmp14"      "Gata5"      "Nme5"       "Flrt3"
 [311] "Pid1"       "Tspan33"    "Popdc2"     "Spsb4"      "Tmem54"
 [316] "Lmo1"       "Ahnak"      "Hdgfrp3"    "Lpar3"      "Id3"
 [321] "Hoxc4"      "Nanog"      "Arl4c"      "Gng3"       "Erich2"
 [326] "Sgk1"       "Dab2"       "Ypel3"      "Hoxa10"     "Igfbp4"
 [331] "Tcf21"      "Grrp1"      "Nr2f1"      "Klf5"       "Rnase4"
 [336] "Clic6"      "Tgif1"      "Nebl"       "Hmga2"      "Tbx3"
 [341] "Limch1"     "Tuba1a"     "Cox4i2"     "Spint1"     "Tfap2c"
 [346] "Pcdh19"     "Map1b"      "Gpc3"       "Rab3il1"    "Itm2a"
 [351] "Nid1"       "Gfra3"      "Mogat2"     "Tgfb2"      "Tmem119"
 [356] "Fermt1"     "Ddit4"      "Rbm47"      "Bmp7"       "Slc7a7"
 [361] "Gas6"       "Chst7"      "Sh3gl3"     "Stard8"     "Stra6"
 [366] "Alx1"       "Six3"       "Serpinh1"   "Rbp4"       "Gsn"
 [371] "Hoxa3"      "Col2a1"     "Dusp2"      "Ppp1r14a"   "Npl"
 [376] "Cdkn2a"     "P4ha2"      "Dusp6"      "Nefm"       "Cyr61"
 [381] "Irx1"       "Myl2"       "Marcks"     "Stard10"    "Morc4"
 [386] "Mpzl2"      "S100g"      "Runx1"      "Cdh11"      "Gjb5"
 [391] "Rgma"       "Twist2"     "Cpe"        "Pecam1"     "Tekt1"
 [396] "Ifitm3"     "Uchl1"      "Lama1"      "Elf3"       "Meis1"
 [401] "Prss50"     "Hmgn3"      "Ctsc"       "Nptx2"      "Fn1"
 [406] "Prrx1"      "Anxa5"      "Plvap"      "Mfap4"      "Pla2g7"
 [411] "Trp53i11"   "Crip2"      "Tnni3"      "Ncam1"      "Apoc1"
 [416] "Fam89a"     "Lpar4"      "Riiad1"     "Cotl1"      "Tubb2b"
 [421] "Fgfbp3"     "Tpbg"       "Gas1"       "Tcf15"      "Mgst3"
 [426] "Nxf7"       "Cadm1"      "Cdc42ep3"   "Tubb4a"     "Zcchc18"
 [431] "Rxrg"       "Kitl"       "Hsd11b2"    "Xlr3a"      "Nr2f2"
 [436] "Tspan7"     "Nkd1"       "Pax3"       "Pyy"        "Pcgf5"
 [441] "Pcsk1n"     "Efnb1"      "Rcsd1"      "Gpx3"       "F3"
 [446] "Gngt2"      "Myl9"       "Cd34"       "Ypel1"      "Gna14"
 [451] "Cfap126"    "Mycl"       "Tmem132c"   "Hist3h2ba"  "Cldn3"
 [456] "Wnt8a"      "Stxbp6"     "Rarg"       "Atp1b1"     "F11r"
 [461] "Myzap"      "Dgkk"       "Col1a1"     "Bok"        "Icam4"
 [466] "Slpi"       "Ppfibp2"    "Kif5c"      "Prom1"      "Fgb"
 [471] "Mpped2"     "Rasl11a"    "Ndn"        "Prtg"       "Peg10"
 [476] "Bcl11a"     "F2rl1"      "Gpx8"       "Lpar1"      "Ccnjl"
 [481] "Htra1"      "Igfbp3"     "Cd9"        "Rbpms"      "Zic5"
 [486] "Bicc1"      "Csrp2"      "Epha4"      "Tctex1d1"   "Ubash3b"
 [491] "Ndrg1"      "Efcab10"    "Ddah1"      "Lfng"       "Alpl"
 [496] "Ezr"        "Afp"        "Nup62cl"    "Enkur"      "Pax6"
 [501] "Dlx5"       "Fsd1"       "Reep6"      "Tox3"       "Tenm4"
 [506] "Cd55"       "Apba2"      "Tgfb1i1"    "Rbm24"      "S100a16"
 [511] "Olfml3"     "Lhfp"       "Tor3a"      "Mapk13"     "Fhl2"
 [516] "Socs2"      "Dab1"       "Acta1"      "Unc5c"      "Aard"
 [521] "Slc40a1"    "Tbx20"      "Lxn"        "Six1"       "Tubb3"
 [526] "Wnt3"       "Bcam"       "Zeb2"       "Dnmt3b"     "Eng"
 [531] "Plp2"       "Mmp2"       "Klf2"       "Jakmip1"    "Mapk12"
 [536] "Pcolce"     "Tmem59l"    "Tmem37"     "Bambi"      "Tuba4a"
 [541] "Dusp9"      "Tmem108"    "Rasip1"     "Pkdcc"      "Rhd"
 [546] "Dbn1"       "Zfp703"     "Cnih2"      "Espn"       "Gipc2"
 [551] "Amot"       "Mlf1"       "Xlr4b"      "Fzd10"      "Adam19"
 [556] "Cap2"       "Kctd15"     "Cpne7"      "Rprm"       "Smoc1"
 [561] "Kdf1"       "Klk8"       "Lrig3"      "Laptm4b"    "Chmp4c"
 [566] "Emp2"       "Col1a2"     "Tead2"      "Pknox2"     "Hspb2"
 [571] "Ptpre"      "Cpm"        "Qprt"       "St14"       "Ell2"
 [576] "Pak1"       "Pmepa1"     "Skap1"      "Cyb561"     "Arid5b"
 [581] "Rsph1"      "Tpd52"      "Msi1"       "Dsp"        "Col13a1"
 [586] "Lamb1"      "Tspan18"    "Haglr"      "Btbd17"     "Apob"
 [591] "Alcam"      "Vstm2b"     "Lad1"       "Id1"        "Copz2"
 [596] "Ctxn1"      "Slain1"     "B3gnt7"     "Pgf"        "Elk3"
 [601] "Clu"        "Gpc4"       "Abcb10"     "Mdfi"       "Smim14"
 [606] "Cnrip1"     "Gja1"       "Foxd4"      "Ankrd33b"   "Stmn3"
 [611] "Tspan12"    "Foxp1"      "Fgfr1"      "Slc39a4"    "Shh"
 [616] "Nsg1"       "Cmtm3"      "Arl4d"      "Acer2"      "Cdc42ep1"
 [621] "Tpd52l1"    "Sptb"       "Cbx7"       "Ass1"       "Tagln3"
 [626] "Arhgap31"   "Pcdh7"      "Dppa3"      "Fam57b"     "Ptk7"
 [631] "Efna4"      "Cald1"      "Ets1"       "Foxc1"      "Zfp42"
 [636] "Acot1"      "Tmem176b"   "Parm1"      "Sox3"       "Fblim1"
 [641] "Lgmn"       "Scube2"     "Itgb5"      "Tmem238"    "Vegfc"
 [646] "Pcdh1"      "Zic2"       "Sgce"       "Lypd6b"     "Lhpp"
 [651] "Clmp"       "Bmp5"       "Rhoc"       "Ifi35"      "Gata3"
 [656] "Cubn"       "Greb1"      "Aqp11"      "Sp8"        "Tbx1"
 [661] "Slc9a3r1"   "Rnf165"     "Rab20"      "Gprc5a"     "Eva1b"
 [666] "Tacstd2"    "Nrk"        "Cpa2"       "Timp1"      "Fam134b"
 [671] "Ly6e"       "Ptpn18"     "Aqp3"       "Glipr2"     "Dpysl5"
 [676] "Adamts9"    "Rnf128"     "Fam46a"     "Rbpms2"     "Arhgef26"
 [681] "Dact1"      "Smtnl2"     "Tdrd5"      "Etv5"       "Pcbd1"
 [686] "Hnf1b"      "Nrp2"       "Cd82"       "Gpx7"       "Naaa"
 [691] "Tlx2"       "Clip3"      "Syngr1"     "Elf5"       "Cdo1"
 [696] "Armcx2"     "Cntnap2"    "Ddr1"       "Slc38a4"    "Tmem114"
 [701] "Ms4a4d"     "Notch1"     "Tal2"       "Fstl1"      "Fam181b"
 [706] "Peg3"       "Ripk4"      "Smoc2"      "Gldc"       "Msx3"
 [711] "Lrp2"       "Mllt3"      "Adgra2"     "Klf9"       "S100a13"
 [716] "Plaur"      "Efcab1"     "Fbln1"      "Lbh"        "Pfn2"
 [721] "Rftn1"      "Camsap3"    "Tshz2"      "Tcf7l1"     "Acrbp"
 [726] "Irx2"       "Epha2"      "Rarb"       "Rgs17"      "Sdc2"
 [731] "Tekt2"      "Dlc1"       "Fam110c"    "Ngfr"       "Ckb"
 [736] "Pxdc1"      "Lrrc34"     "Dnajc22"    "H2-D1"      "Ror2"
 [741] "Car8"       "Lgals2"     "Tmem121"    "Prnp"       "Amph"
 [746] "Flywch2"    "Chst15"     "Sall1"      "Myo6"       "Dnd1"
 [751] "Rnd2"       "Cnn1"       "Jup"        "Atf3"       "Smox"
 [756] "Ush1c"      "Cgnl1"      "Reln"       "Tnnt3"      "Alx3"
 [761] "Npdc1"      "Plagl1"     "Anxa3"      "Lpar6"      "Lrrn4"
 [766] "Tshz1"      "Fbxl22"     "Nrarp"      "Xlr4a"      "Mfng"
 [771] "Fhl1"       "Epas1"      "Smarca2"    "Slc43a3"    "Dhrs11"
 [776] "Tmem100"    "Fxyd5"      "Epb41l3"    "Atp9a"      "Rgs10"
 [781] "Bmper"      "Nrxn2"      "Prss23"     "Ckap4"      "Ebf1"
 [786] "Ascl2"      "Rtn1"       "Plk2"       "Creb3l1"    "Rab38"
 [791] "Ppp1r18"    "Snn"        "Ppp1r14c"   "Greb1l"     "Eno3"
 [796] "Pdzd4"      "Ccdc80"     "Tmem47"     "Speg"       "Nrep"
 [801] "Zeb2os"     "Sprr2a3"    "Amotl1"     "Slc16a10"   "Smarca1"
 [806] "P3h2"       "Cd302"      "Tfap2a"     "Uap1l1"     "Txndc12"
 [811] "Vash2"      "Tmem125"    "Wfikkn1"    "Bves"       "Smim22"
 [816] "Acvrl1"     "Tubb6"      "Timp2"      "Rsph9"      "Zc3hav1"
 [821] "Tspan9"     "Nradd"      "Zcchc12"    "Galnt12"    "Cxx1b"
 [826] "Fkbp10"     "Calb2"      "Col26a1"    "Pcolce2"    "Rragd"
 [831] "Mfge8"      "Porcn"      "Mtus1"      "Gprc5c"     "Nkx2-9"
 [836] "Lsp1"       "Sema6a"     "Cxadr"      "App"        "Cmtm7"
 [841] "Ndufa4l2"   "Pwwp2b"     "Col18a1"    "Sulf1"      "Pipox"
 [846] "Ntn1"       "Gli3"       "Tmem176a"   "Pdzph1"     "Podxl"
 [851] "Sgk3"       "Thbs3"      "Phldb2"     "Fermt2"     "Pdzk1"
 [856] "Tax1bp3"    "Shisa4"     "Smim10l2a"  "Rpp25"      "Pdlim2"
 [861] "Hoxc10"     "Dpysl3"     "Sema6d"     "Elovl4"     "Slc25a37"
 [866] "Rgs3"       "Ifitm2"     "Sall4"      "Ptms"       "Colec12"
 [871] "Ap1s3"      "Cdh3"       "Sfmbt2"     "S100a6"     "Plekho1"
 [876] "Lama4"      "Unc5b"      "Necab2"     "Crb2"       "Mycn"
 [881] "Akap12"     "Tln2"       "Akr1c19"    "Tcn2"       "Sh3bp5"
 [886] "Fam210b"    "Tdo2"       "Lmna"       "Arhgef16"   "Tm6sf1"
 [891] "Bhmt2"      "Mnx1"       "Sdc4"       "Dmtn"       "Cpne5"
 [896] "Psmb8"      "Des"        "Ptp4a3"     "Lima1"      "Sall3"
 [901] "Prkcdbp"    "Palm3"      "Rnf213"     "Serping1"   "Procr"
 [906] "Afap1l1"    "Creb3l2"    "Ntng1"      "Adora2b"    "Lrrc46"
 [911] "Celf4"      "Zfp711"     "Tfap2b"     "Pdlim3"     "Adamtsl2"
 [916] "Fbxo6"      "Serpinf1"   "Dusp14"     "Lamc1"      "Ak1"
 [921] "Creg1"      "H1fx"       "Lix1l"      "Tm4sf5"     "Spaca9"
 [926] "Ccdc141"    "Aadat"      "G0s2"       "Sult4a1"    "Emilin1"
 [931] "Arpc1b"     "Klc3"       "S100a10"    "Plppr1"     "Foxd3"
 [936] "Pea15a"     "Glrx"       "Plpp3"      "Agtrap"     "Thy1"
 [941] "Chst2"      "Kcnh2"      "Ptges"      "Lpl"        "Ppic"
 [946] "Meis3"      "Lhfpl2"     "Pnma2"      "H2-K1"      "Axin2"
 [951] "Etv1"       "Runx1t1"    "Plxnd1"     "Slit2"      "Cfap53"
 [956] "Grhl3"      "Tex264"     "Palld"      "Lck"        "Galnt3"
 [961] "S100a11"    "Wls"        "Anxa4"      "Atp6v0e2"   "Emp3"
 [966] "Phactr1"    "Tnfrsf19"   "Cxx1a"      "Arhgap8"    "St6galnac4"
 [971] "Tead4"      "Dusp4"      "Plod2"      "Fgf4"       "Fgfr2"
 [976] "Phyhipl"    "Spon1"      "Dnaaf3"     "Hs6st2"     "Emilin2"
 [981] "Fbn1"       "Kctd1"      "Elmo1"      "Vamp8"      "Pbx1"
 [986] "Raet1e"     "Sox21"      "Dcn"        "Efemp2"     "Ttyh1"
 [991] "Eva1a"      "Aes"        "Gstm6"      "Syt11"      "Ccdc160"
 [996] "Scpep1"     "Rab34"      "Crlf1"      "Tspan13"    "Dpf3"
[1001] "Cd38"       "Slc13a4"    "Sesn3"      "Atoh8"      "Atp8a1"
[1006] "Susd4"      "Penk"       "Dusp3"      "Ssbp2"      "Ndrg2"
[1011] "Nes"        "Mid1ip1"    "Zeb1"       "Slc16a2"    "Kcns3"
[1016] "S1pr2"      "Zfp462"     "Snrpn"      "Slc29a1"    "Urah"
[1021] "Lrpap1"     "Fam114a1"   "Plac8"      "Klhdc8b"    "Scara3"
[1026] "Frem2"      "Cd24a"      "Tmem158"    "Ccpg1os"    "Mmd"
[1031] "Rbm38"      "Smad1"      "Tpm1"       "Irf2bpl"    "Gdpd5"
[1036] "Igsf9"      "Chd3os"     "Nrg1"       "Lgals1"     "Eif4e3"
[1041] "Mir124-2hg" "Hpn"        "Apobec3"    "Aldoc"      "Ephx2"
[1046] "Tfeb"       "Pdgfrb"     "Bend5"      "Fbxo16"     "Hoxb3"
[1051] "Sept6"      "Smyd1"      "Pdlim1"     "Klf6"       "Mmp11"
[1056] "Nid2"       "Maged2"     "Pfkfb4"     "Tmem163"    "Prr7"
[1061] "Rnf122"     "Ldb2"       "Phlda3"     "Arhgef15"   "Slit3"
[1066] "Arhgap24"   "Elavl3"     "Anxa6"      "Cd63"       "Nmi"
[1071] "Car7"       "Ucp2"       "Tmem30b"    "Spats2l"    "Map7d2"
[1076] "Col23a1"    "Wipf3"      "Ccdc65"     "Nrcam"      "Capn2"
[1081] "Ociad2"     "Oaf"        "Mgarp"      "Stox2"      "Arhgap18"
[1086] "Fam178b"    "Flrt2"      "Nrgn"       "St3gal5"    "Ldoc1"
[1091] "Eml1"       "Adgrv1"     "Drc1"       "Ajuba"      "Ly6h"
[1096] "Vgll4"      "Rhpn2"      "Adm"        "Smad6"      "Nrtn"
[1101] "Hey1"       "Fgf10"      "Vcam1"      "Hsd17b11"   "Rimklb"
[1106] "Lin28a"     "Irf1"       "Id4"        "Ripk3"      "Enpp2"
[1111] "Cbs"        "Homer2"     "Bcar3"      "Ift74"      "Zbtb8a"
[1116] "Iqcg"       "Fam43a"     "Cltb"       "Lurap1l"    "Ece1"
[1121] "Fbln2"      "Hoxa4"      "Fkbp7"      "Stat3"      "Nuak2"
[1126] "Flt4"       "Ripply3"    "Epb41l4a"   "Sat1"       "Crispld1"
[1131] "Smad7"      "Plxna2"     "Ldhc"       "Cobll1"     "Nkx6-1"
[1136] "Hk1"        "Arhgap29"   "Gng2"       "Samd14"     "Robo2"
[1141] "Dand5"      "Nr6a1"      "Crip1"      "Rab11fip4"  "Ptgis"
[1146] "Myo1b"      "Gfpt2"      "Cpox"       "Trim2"      "Epha7"
[1151] "Hspg2"      "Prps1"      "Ttc28"      "Soga3"      "Hip1"
[1156] "Camk2d"     "Tmem150a"   "St8sia3"    "Flnc"       "Cgn"
[1161] "Rnd3"       "Ocln"       "Hes1"       "Snai2"      "Dync2li1"
[1166] "Flnb"       "Itm2c"      "Gnb4"       "Krtcap3"    "Rrad"
[1171] "Sec24d"     "Lor"        "She"        "Capg"       "Ctsl"
[1176] "Sigirr"     "Tgfbr3"     "Fez1"       "Camkv"      "Frmd6"
[1181] "Gstm1"      "Sox13"      "Lrp11"      "Batf3"      "Hapln3"
[1186] "Jam3"       "Lpp"        "Armcx1"     "Vat1"       "Plpp4"
[1191] "Fignl2"     "Ttc25"      "Derl3"      "Rac3"       "Spry4"
[1196] "Rgs2"       "Itga6"      "Mme"        "Tceal6"     "Dapk2"
[1201] "Nphp3"      "Polg"       "Limd2"      "Pcp4"       "P3h4"
[1206] "Itsn2"      "Hbegf"      "Rgl1"       "Rspo1"      "Rab39b"
[1211] "Ednra"      "Apoa2"      "Ednrb"      "Kif21a"     "Sord"
[1216] "Nkain4"     "Rasa3"      "Gab1"       "Emid1"      "Hlx"
[1221] "Large2"     "Lyn"        "Nkx2-3"     "Fam171b"    "Mapk3"
[1226] "Mcc"        "Dennd1c"    "Oxct1"      "Hoxc5"      "St3gal6"
[1231] "Rbms1"      "Tpm2"       "Prkcz"      "Dtx1"       "Plp1"
[1236] "Pbx4"       "Fndc3c1"    "Rflna"      "F2r"        "Zar1"
[1241] "Foxd1"      "Cideb"      "Tagln2"     "Was"        "Gnb5"
[1246] "Gng12"      "Fkbp6"      "Pcsk9"      "Stbd1"      "Kcnmb4"
[1251] "Ccdc189"    "Pcsk2os1"   "Nr2f6"      "Smpdl3a"    "Lgr5"
[1256] "Rab15"      "Tcf7l2"     "Fuom"       "Kif26b"     "Mxra8"
[1261] "Ugdh"       "Parva"      "Eea1"       "Tmem51"     "Bcl11b"
[1266] "Mex3b"      "Mab21l2"    "Zfp516"     "Airn"       "Klf4"
[1271] "Myb"        "Sgpl1"      "Pygl"       "Rab27b"     "Ablim1"
[1276] "Fam107b"    "Nfkb1"      "Mtmr7"      "Il17rd"     "Alox5ap"
[1281] "Usp51"      "Slc9a3r2"   "Sulf2"      "Mbnl2"      "Dapp1"
[1286] "Etl4"       "Foxf2"      "Lrrc56"     "Ddit4l"     "Lifr"
[1291] "Mettl7a1"   "Irak2"      "Nudt10"     "Mex3a"      "Fign"
[1296] "Trim25"     "Arap3"      "Slco3a1"    "Csrp1"      "Ermn"
[1301] "Ptbp2"      "Slc16a1"    "Hoxa11"     "Ackr3"      "Cxxc4"
[1306] "Cracr2b"    "Sall2"      "Gpc6"       "Slc22a18"   "Slc1a3"
[1311] "Myo1c"      "Chd3"       "Cacng4"     "Myc"        "Dlx2"
[1316] "Dst"        "Ift81"      "Tmod2"      "Prr5l"      "Lrp1"
[1321] "Bace2"      "Mum1l1"     "Sbk1"       "Tmsb4x"     "Tdrp"
[1326] "Nav2"       "Wdr86"      "Slc31a2"    "Nudt11"     "N4bp3"
[1331] "Peli2"      "Rax"        "Tsc22d3"    "Sh3bgrl2"   "Ggta1"
[1336] "Rhou"       "Pkp2"       "Lgals3"     "Syne2"      "Bin2"
[1341] "Sec14l2"    "Wisp1"      "Atp1a2"     "Map7"       "Gstt2"
[1346] "Gucy1a3"    "Gadd45a"    "Samd10"     "Zbtb16"     "Selenom"
[1351] "Ptges3l"    "Syt5"       "Cyba"       "Aplp1"      "Fam49a"
[1356] "Ppp1r13b"   "Rabgap1l"   "Tmem141"    "Tspan2"     "Tes"
[1361] "Ephb1"      "Siah2"      "Baiap2l1"   "Fzd5"       "Junb"
[1366] "B4galt6"    "Fxyd2"      "Kalrn"      "Grasp"      "Spa17"
[1371] "Steap1"     "Nsg2"       "Marveld2"   "Tapbp"      "Casz1"
[1376] "Plekha2"    "Prr5"       "Oscp1"      "Efna5"      "Socs3"
[1381] "Trim54"     "Hmcn1"      "Sox1"       "Epdr1"      "Ephb3"
[1386] "Bik"        "Scn8a"      "Gstk1"      "Ccdc92"     "BC028528"
[1391] "Cyp2s1"     "Npnt"       "Ehbp1"      "Rin3"       "Rell1"
[1396] "Maf"        "Ghr"        "Afdn"       "Itga3"      "Aif1l"
[1401] "Dnase2a"    "Nav1"       "Cuedc1"     "Sycp3"      "Zfp36l1"
[1406] "Igf2r"      "Ephb2"      "Coro1a"     "Sox18"      "Fgfr3"
[1411] "Vsnl1"      "Nfil3"      "Mirg"       "Homer3"     "Arhgef28"
[1416] "Cdkn1a"     "Stk39"      "Enho"       "Mxd4"       "Snx10"
[1421] "Msantd3"    "Dtx4"       "Rapgef5"    "Tram1l1"    "Dcaf12l1"
[1426] "Rfx4"       "Gamt"       "Pxdn"       "Irx4"       "Tmem45a"
[1431] "Gli1"       "Fabp5"      "Svep1"      "Hacd4"      "Lhx5"
[1436] "Scarf1"     "Fzd1"       "Fzd4"       "Tceal5"     "Nectin2"
[1441] "Myadm"      "Syndig1"    "Itga5"      "B9d1"       "Efnb3"
[1446] "Kit"        "Popdc3"     "Ptprk"      "Stc2"       "Hdac7"
[1451] "Pcsk5"      "Eps8l2"     "Steap3"     "Acbd7"      "Mapk8ip1"
[1456] "Sh3bgrl"    "Tmem184a"   "Smim3"      "Fndc3b"     "Cited2"
[1461] "B3galnt1"   "S100a1"     "Fam187b"    "Pard6g"     "Sh2d3c"
[1466] "Gstt1"      "Celsr1"     "Erbb3"      "Gyg"        "Ccdc103"
[1471] "Soat1"      "Phyh"       "Ccdc39"     "Dync1i1"    "Frmd4b"
[1476] "Mapkapk3"   "Ppp1r9b"    "Grsf1"      "Slc16a13"   "Cxxc5"
[1481] "Nap1l5"     "Dach1"      "Patj"       "Sema3e"     "Tspan6"
[1486] "Pnp2"       "Cep170b"    "Pgap1"      "Myo18a"     "Rab3b"

# MapWrap unpacked

In [48]:
  sce_atlas = sce_atlas
  meta_atlas = meta_atlas
  sce_query = sce_query
  meta_query = meta_query
  genes = genes_to_use
  npcs = args$npcs
  k = args$n_neighbours
  cosineNorm = args$cosine_normalisation
  order = NULL

In [49]:
   
  # Normalisation
  message(sprintf("Normalizing joint dataset using cosineNorm=%s...",cosineNorm))
  sce_all <- joint.normalisation(sce_query, sce_atlas, cosineNorm)
  message("Done\n")

Normalizing joint dataset using cosineNorm=FALSE...

Done

In [50]:
  
  # Feature selection
  if (is.null(genes)) {
    message("Genes not provided. Computing highly variable genes...")
    # hvgs <- getHVGs(sce_all, block=c(meta_atlas$sample, meta_query$sample))
    genes <- getHVGs(sce_all, block=sce_all$block)
    message("Done\n")
  } else {
    message(sprintf("%d Genes provided...",length(genes)))
  }

2500 Genes provided...

In [51]:
  # Dimensionality reduction
  message("Performing PCA...")
  big_pca <- multiBatchPCA(
    sce_all,
    batch = sce_all$block,
    subset.row = genes,
    d = npcs,
    preserve.single = TRUE,
    assay.type = if (cosineNorm) "cosineNorm" else "logcounts"
  )[[1]]
  rownames(big_pca) <- colnames(sce_all) 
  atlas_pca <- big_pca[1:ncol(sce_atlas),]
  query_pca   <- big_pca[-(1:ncol(sce_atlas)),]
  message("Done\n")

Performing PCA...

Done

In [52]:
  
  # Batch effect correction for the atlas
  message("Batch effect correction for the atlas...")  
  order_df        <- meta_atlas[!duplicated(meta_atlas$sample), c("stage", "sample")]
  order_df$ncells <- sapply(order_df$sample, function(x) sum(meta_atlas$sample == x))
  order_df$stage  <- factor(order_df$stage, levels = rev(c("E9.5",
                                       "E9.25",
                                       "E9.0",
                                       "E8.75",
                                       "E8.5",
                                       "E8.25",
                                       "E8.0",
                                       "E7.75",
                                       "E7.5",
                                       "E7.25",
                                       "mixed_gastrulation",
                                       "E7.0",
                                       "E6.75",
                                       "E6.5")))
  order_df       <- order_df[order(order_df$stage, order_df$ncells, decreasing = TRUE),]
  order_df$stage <- as.character(order_df$stage)
  
  set.seed(42)
  pca_atlas_corrected <- doBatchCorrect(counts         = logcounts(sce_atlas[genes,]), 
                                    timepoints      = meta_atlas$stage, 
                                    samples         = meta_atlas$sample, 
                                    timepoint_order = order_df$stage, 
                                    sample_order    = order_df$sample, 
                                    pc_override     = atlas_pca,
                                    npc             = npcs)
  message("Done\n")

Batch effect correction for the atlas...

Loading required package: BiocParallel

Done

In [54]:
  # Mapping query to batch-corrected atlas
  message("MNN mapping...")              
  # correct <- reducedMNN(rbind(pca_atlas_corrected, query_pca), batch = sce_all$block)[["corrected"]]
  correct <- reducedMNN(rbind(pca_atlas_corrected, query_pca),
                      # batch=c(rep("ATLAS", dim(meta_atlas)[1]), meta_query$sample),
                      batch = as.character(sce_all$block),
                      merge.order = order)$corrected
  pca_atlas_corrected <- correct[1:nrow(atlas_pca),]
  pca_query_corrected   <- correct[-(1:nrow(atlas_pca)),]

MNN mapping...

In [56]:
head(pca_query_corrected)
head(pca_atlas_corrected)

                                              [,1]       [,2]     [,3]
SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1 -14.987037 2.413490  24.6406411
SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1  -7.940671 7.905278 -14.2722171
SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1  -8.726419 8.758685  -0.9571918
SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1 -13.366618 3.451749  23.3918650
SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTGATAGTA-1 -15.784547 1.576234  23.8164706
SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTTAAGACA-1  -8.859923 9.763747   2.7037113
                                              [,4]       [,5]
SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1  -3.032402  5.767520
SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1 -16.816031 10.581002
SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1  -8.901286 -1.698947
SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1  -5.954716  0.584606
SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTGATAGTA-1  -1.795425  6.121257
SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTTAAGACA-1  -5.096928 -4.358171

         [,1]      [,2]      [,3]      [,4]        [,5]
cell_361 -22.18608 -5.858202 -7.477659 13.22464068 -8.494032
cell_362 -12.44580  6.015637  2.600329 -1.15762130  2.156080
cell_363 -10.66507  8.345092  7.358897 -3.35566261  3.066436
cell_364 -10.77508  6.928303  9.191929 -4.99766121 -4.773238
cell_365 -12.98190  5.618987  1.879723  0.01229901  2.966236
cell_366 -10.58148  6.606713  6.264774 -6.22517346 -5.805861

In [59]:
meta_atlas$celltype = meta_atlas$celltype_extended_atlas

In [60]:
  mapping <- get_meta(pca_atlas = pca_atlas_corrected,
                      meta_atlas = meta_atlas,
                      pca_query = pca_query_corrected,
                      meta_query = meta_query,
                      k = k)
  message("Done\n")

Done

In [61]:

  

  


  



  
  # Mapping scores
  message("Computing mapping scores...") 
  out <- list()
  for (i in seq(from = 1, to = k)) {
    out$closest.cells[[i]]     <- sapply(mapping, function(x) x$cells.mapped[i])
    out$celltypes.mapped[[i]]  <- sapply(mapping, function(x) x$celltypes.mapped[i])
    out$cellstages.mapped[[i]] <- sapply(mapping, function(x) x$stages.mapped[i])
  }  
  multinomial.prob <- getMappingScore(out)
  message("Done\n")
  
  # Prepare output
  message("Writing output...") 
  out$pca_atlas_corrected <- pca_atlas_corrected
  out$pca_query_corrected <- pca_query_corrected
  ct <- sapply(mapping, function(x) x$celltype.mapped); is.na(ct) <- lengths(ct) == 0
  st <- sapply(mapping, function(x) x$stage.mapped); is.na(st) <- lengths(st) == 0
  cm <- sapply(mapping, function(x) x$cells.mapped[1]); is.na(cm) <- lengths(cm) == 0
  out$mapping <- data.frame(
      cell            = names(mapping), 
      celltype.mapped = unlist(ct),
      stage.mapped    = unlist(st),
      closest.cell    = unlist(cm))
  
  out$mapping <- cbind(out$mapping,multinomial.prob)
  out$pca <- big_pca
  message("Done\n")
  
  return(out)

Computing mapping scores...

Done


Writing output...

Done

In [62]:
str(out)

List of 7
 $ closest.cells      :List of 25
  ..$ : Named chr [1:1000] "cell_393" "cell_965" "cell_1108" "cell_393" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_592" "cell_711" "cell_1386" "cell_1434" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_398" "cell_1099" "cell_1196" "cell_2671" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_2671" "cell_686" "cell_962" "cell_592" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_539" "cell_2664" "cell_807" "cell_830" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_698" "cell_756" "cell_457" "cell_384" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_761" "cell_1445" "cell_1319" "cell_446" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_519" "cell_1020" "cell_950" "cell_2676" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_484" "cell_909" "cell_410" "cell_846" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_737" "cell_939" "cell_888" "cell_364" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_846" "cell_827" "cell_757" "cell_539" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_1039" "cell_958" "cell_2667" "cell_737" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_498" "cell_679" "cell_996" "cell_1084" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_1434" "cell_1410" "cell_672" "cell_519" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_830" "cell_823" "cell_841" "cell_1281" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_363" "cell_1114" "cell_1251" "cell_498" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_384" "cell_1277" "cell_1048" "cell_957" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_1254" "cell_2678" "cell_1339" "cell_470" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_710" "cell_684" "cell_953" "cell_560" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_716" "cell_532" "cell_759" "cell_877" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_642" "cell_400" "cell_1443" "cell_2672" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_385" "cell_1440" "cell_1208" "cell_604" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_691" "cell_403" "cell_817" "cell_1402" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_1089" "cell_689" "cell_2661" "cell_398" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_896" "cell_1009" "cell_609" "cell_779" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
 $ celltypes.mapped   :List of 25
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Erythroid" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "ExE ectoderm" "Amniotic ectoderm" "Haematoendothelial progenitors" "Erythroid" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Non-neural ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Haematoendothelial progenitors" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Paraxial mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Haematoendothelial progenitors" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Paraxial mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Paraxial mesoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Lateral plate mesoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Paraxial mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "ExE ectoderm" "Mesenchyme" "ExE ectoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "ExE ectoderm" "Mesenchyme" "Paraxial mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Lateral plate mesoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "ExE ectoderm" "Mesenchyme" "Lateral plate mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Haematoendothelial progenitors" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Lateral plate mesoderm" "Lateral plate mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Epiblast" "Mesenchyme" "Caudal epiblast" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Haematoendothelial progenitors" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
 $ cellstages.mapped  :List of 25
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...