In [1]:
suppressPackageStartupMessages(library(scran))
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(batchelor))
suppressPackageStartupMessages(library(argparse))

here::i_am("mapping/run/mnn/mapping_mnn.R")

# Load mapping functions
source(here::here("mapping/run/mnn/mapping_functions.R"))

# Load default settings
source(here::here("settings.R"))
source(here::here("utils.R"))

here() starts at /rds/project/rds-SDzz0CATGms/users/bt392/03_Stat3_RNA/code

In [2]:
# I/O
io$path2atlas <- io$atlas.basedir
io$path2query <- io$basedir

# START TEST ##
args = list()
args$atlas_stages <- c("E7.5","E7.75")
args$query_samples <- opts$samples
args$query_sce <- io$rna.sce
args$query_sce <- paste0(io$basedir,"/processed/SingleCellExperiment.rds")
args$atlas_sce <- io$rna.atlas.sce
args$query_metadata <- paste0(io$basedir,"/results/rna/doublet_detection/sample_metadata_after_doublets.txt.gz")
args$atlas_metadata <- io$rna.atlas.metadata
args$test <- TRUE
args$npcs <- 5
args$n_neighbours <- 25
args$use_marker_genes <- FALSE
args$cosine_normalisation <- FALSE
args$outdir <- paste0(io$basedir,"/results/rna/mapping/test")
# END TEST ##

In [3]:
if (isTRUE(args$test)) print("Test mode activated...")

[1] "Test mode activated..."

In [4]:
meta_query <- fread(args$query_metadata) %>% 
  .[pass_rnaQC==TRUE & doublet_call==FALSE & sample%in%args$query_samples]

In [5]:
head(meta_query)

  cell                                          sample
1 SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1 SLX-21143_SITTA2_HTJH3DSX2
2 SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1 SLX-21143_SITTA2_HTJH3DSX2
3 SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1 SLX-21143_SITTA2_HTJH3DSX2
4 SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1 SLX-21143_SITTA2_HTJH3DSX2
5 SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTGATAGTA-1 SLX-21143_SITTA2_HTJH3DSX2
6 SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTTAAGACA-1 SLX-21143_SITTA2_HTJH3DSX2
  barcode            nFeature_RNA nCount_RNA mitochondrial_percent_RNA
1 AAACCCAAGATGTTCC-1 4837         53199      1.47
2 AAACCCATCAGACCTA-1 4973         24165      0.95
3 AAACGAACAATGTTGC-1 5585         34341      0.22
4 AAACGAACACACCAGC-1 5016         41496      1.66
5 AAACGAAGTGATAGTA-1 4308         44249      0.60
6 AAACGAAGTTAAGACA-1 3826         17237      1.42
  ribosomal_percent_RNA stage tdTom idx tdTom_corr pass_rnaQC doublet_score
1 22.87                 E8.5  TRUE  1   TRUE       TRUE       0.09
2 19.26                 E8.5  TRUE  3   TRUE       TRUE       0.24
3 26.76                 E8.5  TRUE  5   TRUE       TRUE       0.22
4 25.01                 E8.5  TRUE  6   TRUE       TRUE       0.11
5 24.26                 E8.5  TRUE  7   TRUE       TRUE       0.10
6 28.43                 E8.5  TRUE  8   TRUE       TRUE       0.10
  doublet_call
1 FALSE
2 FALSE
3 FALSE
4 FALSE
5 FALSE
6 FALSE

In [6]:
################
## Load query ##
################

# Load cell metadata
meta_query <- fread(args$query_metadata) %>% 
  .[pass_rnaQC==TRUE & doublet_call==FALSE & sample%in%args$query_samples]
if (isTRUE(args$test)) meta_query <- head(meta_query,n=1000)

# Load SingleCellExperiment
sce_query <- load_SingleCellExperiment(args$query_sce, cells = meta_query$cell, remove_non_expressed_genes = TRUE)

# Update colData
tmp <- meta_query %>% .[cell%in%colnames(sce_query)] %>% setkey(cell) %>% .[colnames(sce_query)]
stopifnot(tmp$cell == colnames(sce_query))
colData(sce_query) <- tmp %>% as.data.frame %>% tibble::column_to_rownames("cell") %>%
  .[colnames(sce_query),] %>% DataFrame()

################
## Load atlas ##
################

# Load cell metadata
meta_atlas <- fread(args$atlas_metadata) %>%
  .[stage%in%args$atlas_stages] %>%
  .[,sample:=factor(sample)]

# Filter
if (isTRUE(args$test)) meta_atlas <- head(meta_atlas,n=1000)

# Load SingleCellExperiment
sce_atlas <- load_SingleCellExperiment(args$atlas_sce, normalise = TRUE, cells = meta_atlas$cell, remove_non_expressed_genes = TRUE)

# Update colData
tmp <- meta_atlas %>% .[cell%in%colnames(sce_atlas)] %>% setkey(cell) %>% .[colnames(sce_atlas)]
stopifnot(tmp$cell == colnames(sce_atlas))
colData(sce_atlas) <- tmp %>% as.data.frame %>% tibble::column_to_rownames("cell") %>%
  .[colnames(sce_atlas),] %>% DataFrame()

# Sanity cehcks
stopifnot(sum(is.na(rownames(sce_atlas)))==0)
stopifnot(sum(duplicated(rownames(sce_atlas)))==0)

In [7]:
#####################
## Define gene set ##
#####################

# Get gene metadata
gene_metadata <- fread(io$gene_metadata) %>% .[,c("chr","ens_id","symbol")] %>%
  .[symbol!="" & ens_id%in%rownames(sce_atlas)] %>%
  .[!duplicated(symbol)]

# Intersect genes
genes.intersect <- intersect(rownames(sce_query), rownames(sce_atlas))

# Filter some genes manually
genes.intersect <- genes.intersect[grep("^Rik|Rik$|^mt-|^Rps|^Rpl|^Gm",genes.intersect,invert=T)]
genes.intersect <- genes.intersect[!genes.intersect=="Xist"]
genes.intersect <- genes.intersect[!genes.intersect%in%gene_metadata[chr=="chrY",symbol]]

In [8]:
head(genes.intersect, 1000)

   [1] "Sox17"      "Mrpl15"     "Lypla1"     "Tcea1"      "Atp6v1h"
   [6] "Rb1cc1"     "Pcmtd1"     "Rrs1"       "Vcpip1"     "Sgk3"
  [11] "Snhg6"      "Cops5"      "Cspp1"      "Arfgef1"    "Prex2"
  [16] "Sulf1"      "Ncoa2"      "Tram1"      "Lactb2"     "Terf1"
  [21] "Rdh10"      "Stau2"      "Ube2w"      "Tmem70"     "Jph1"
  [26] "Crispld1"   "Mcm3"       "Tram2"      "Tmem14a"    "Ogfrl1"
  [31] "Smap1"      "Sdhaf4"     "Fam135a"    "Col9a1"     "Lmbrd1"
  [36] "Phf3"       "Ptp4a1"     "Prim2"      "Rab23"      "Bag2"
  [41] "Zfp451"     "Dst"        "Ccdc115"    "Imp4"       "Ptpn18"
  [46] "Cfc1"       "Fam168b"    "Plekhb2"    "Hs6st1"     "Uggt1"
  [51] "Kansl3"     "Lman2l"     "Cnnm4"      "Cnnm3"      "Ankrd39"
  [56] "Sema4c"     "Fam178b"    "Cox5b"      "Actr1b"     "Tmem131"
  [61] "Coa5"       "Unc50"      "Mgat4a"     "Tsga10"     "Lipt1"
  [66] "Mitd1"      "Mrpl30"     "Txndc9"     "Eif5b"      "Rev1"
  [71] "Aff3"       "Pdcl3"      "Cnot11"     "Rnf149"     "Map4k4"
  [76] "Mrps9"      "Tgfbrap1"   "AI597479"   "Fhl2"       "Uxs1"
  [81] "Tpp2"       "Tex30"      "Kdelc1"     "Bivm"       "Ercc5"
  [86] "Gulp1"      "Wdr75"      "Slc40a1"    "Dnah7b"     "Slc39a10"
  [91] "Nabp1"      "Myo1b"      "Stat1"      "Gls"        "Nab1"
  [96] "Nemp2"      "Inpp1"      "Hibch"      "Pms1"       "Ormdl1"
 [101] "Osgepl1"    "Asnsd1"     "Stk17b"     "Gtf3c3"     "Pgap1"
 [106] "Sf3b1"      "Coq10b"     "Hspd1"      "Hspe1"      "Mob4"
 [111] "Mars2"      "Satb2"      "Tyw5"       "Spats2l"    "Kctd18"
 [116] "Sgol2a"     "Bzw1"       "Clk1"       "Ppil3"      "Nif3l1"
 [121] "Orc2"       "Fam126b"    "Ndufb3"     "Cflar"      "Casp8"
 [126] "Trak2"      "Stradb"     "Tmem237"    "Als2"       "Fzd7"
 [131] "Sumo1"      "Nop58"      "Bmpr2"      "Fam117b"    "Wdr12"
 [136] "Carf"       "Nbeal1"     "Cyp20a1"    "Abi2"       "Raph1"
 [141] "Nrp2"       "Ino80d"     "Ndufs1"     "Eef1b2"     "Zdbf2"
 [146] "Fastkd2"    "Klf7"       "Creb1"      "Mettl21a"   "Ccnyl1"
 [151] "Fzd5"       "Plekhm3"    "Idh1"       "Pikfyve"    "Map2"
 [156] "Rpe"        "Kansl1l"    "Acadl"      "Lancl1"     "Ikzf2"
 [161] "Bard1"      "Atic"       "Fn1"        "Mreg"       "Pecr"
 [166] "Xrcc5"      "Smarcal1"   "Igfbp2"     "Igfbp5"     "Tns1"
 [171] "Arpc2"      "Aamp"       "Pnkd"       "Tmbim1"     "Ctdsp1"
 [176] "Usp37"      "Cnot9"      "Zfp142"     "Bcs1l"      "Rnf25"
 [181] "Ttll4"      "Cyp27a1"    "Wnt6"       "Ihh"        "Nhej1"
 [186] "Cnppd1"     "Fam134a"    "Zfand2b"    "Abcb6"      "Atg9a"
 [191] "Ankzf1"     "Stk16"      "Tuba4a"     "Dnajb2"     "Ptprn"
 [196] "Dnpep"      "Des"        "Speg"       "Chpf"       "Obsl1"
 [201] "Stk11ip"    "Slc4a3"     "Epha4"      "Sgpp2"      "Farsb"
 [206] "Acsl3"      "Utp14b"     "Ap1s3"      "Wdfy1"      "Mrpl44"
 [211] "Serpine2"   "Cul3"       "Irs1"       "Rhbdd1"     "Mff"
 [216] "Agfg1"      "Pid1"       "Trip12"     "Fbxo36"     "Cab39"
 [221] "Itm2c"      "Psmd1"      "Armc9"      "B3gnt7"     "Ncl"
 [226] "Ptma"       "Pde6d"      "Cops7b"     "Dis3l2"     "Eif4e2"
 [231] "Gigyf2"     "Atg16l1"    "Sag"        "Dgkd"       "Usp40"
 [236] "Dnajb3"     "Hjurp"      "Arl4c"      "Sh3bp4"     "Agap1"
 [241] "Gbx2"       "Ackr3"      "Cops8"      "Lrrfip1"    "Ube2f"
 [246] "Scly"       "Ilkap"      "Hes6"       "Traf3ip1"   "Asb1"
 [251] "Twist2"     "Hdac4"      "Ndufa10"    "Gpc1"       "Dusp28"
 [256] "Rnpepl1"    "Capn10"     "Kif1a"      "Mterf4"     "Pask"
 [261] "Ppp1r7"     "Hdlbp"      "Stk25"      "Bok"        "Thap4"
 [266] "Atg4b"      "Dtymk"      "Ing5"       "D2hgdh"     "Fam174a"
 [271] "D1Ertd622e" "Ppip5k2"    "Gin1"       "Pam"        "Pign"
 [276] "Zcchc2"     "Phlpp1"     "Bcl2"       "Kdsr"       "Vps4b"
 [281] "Dsel"       "Tsn"        "Nifk"       "Clasp1"     "Tfcp2l1"
 [286] "Gli2"       "Ralb"       "Tmem185b"   "Epb41l5"    "Ptpn4"
 [291] "Tmem177"    "Tmem37"     "Dbi"        "Steap3"     "En1"
 [296] "Insig2"     "Ccdc93"     "Ddx18"      "Actr3"      "Slc35f5"
 [301] "Lypd1"      "Mgat5"      "Ccnt2"      "Rab3gap1"   "Zranb3"
 [306] "R3hdm1"     "Ubxn4"      "Mcm6"       "Dars"       "Cd55"
 [311] "Yod1"       "AA986860"   "Mapkapk2"   "Dyrk3"      "Eif2d"
 [316] "Srgap2"     "Fam72a"     "Slc41a1"    "Nucks1"     "Slc45a3"
 [321] "Elk4"       "Cdk18"      "Lemd1"      "Nuak2"      "Tmcc2"
 [326] "Dstyk"      "Rbbp5"      "Nfasc"      "Mdm4"       "Pik3c2b"
 [331] "Ppp1r15b"   "Plekha6"    "Etnk2"      "Sox13"      "Snrpe"
 [336] "Zc3h11a"    "Btg2"       "Tmem183a"   "Cyb5r1"     "Adipor1"
 [341] "Klhl12"     "Rabif"      "Kdm5b"      "Ppp1r12b"   "Ube2t"
 [346] "Arl8a"      "Elf3"       "Rnpep"      "Timm17a"    "Shisa4"
 [351] "Ipo9"       "Nav1"       "Csrp1"      "Phlda3"     "Tnni1"
 [356] "Lad1"       "Tnnt2"      "Tmem9"      "Kif21b"     "Camsap2"
 [361] "Ddx59"      "Kif14"      "Zfp281"     "Nek7"       "Dennd1b"
 [366] "Zbtb41"     "Aspm"       "Cdc73"      "Glrx2"      "Trove2"
 [371] "Uchl5"      "Rgs2"       "BC003331"   "Tpr"        "Ivns1abp"
 [376] "Swt1"       "Trmt1l"     "Rnf2"       "Edem3"      "Tsen15"
 [381] "Rgl1"       "Arpc5"      "Smg7"       "Nmnat2"     "Lamc1"
 [386] "Dhx9"       "Npl"        "Rgs16"      "Glul"       "Ier5"
 [391] "Stx6"       "BC034090"   "Xpr1"       "Acbd6"      "Qsox1"
 [396] "Cep350"     "Tor1aip1"   "Tor1aip2"   "Soat1"      "Abl2"
 [401] "Tor3a"      "Fam20b"     "Ralgps2"    "Rasal2"     "BC026585"
 [406] "Rfwd2"      "Mrps14"     "Cacybp"     "Rabgap1l"   "Rc3h1"
 [411] "Serpinc1"   "Zbtb37"     "Dars2"      "Cenpl"      "Klhl20"
 [416] "Ankrd45"    "Prdx6"      "Suco"       "Pigc"       "Mettl13"
 [421] "Vamp4"      "Prrc2c"     "Fmo1"       "Prrx1"      "Gorab"
 [426] "Kifap3"     "Scyl3"      "BC055324"   "Mettl18"    "F5"
 [431] "Slc19a2"    "Ccdc181"    "Blzf1"      "Nme7"       "Atp1b1"
 [436] "Sft2d2"     "Tiprl"      "Dcaf6"      "Mpc2"       "Mpzl1"
 [441] "Rcsd1"      "Creg1"      "Pou2f1"     "Tada1"      "Pogk"
 [446] "Uck2"       "Tmco1"      "Aldh9a1"    "Mgst3"      "Rxrg"
 [451] "Pbx1"       "Nuf2"       "Rgs5"       "Hsd17b7"    "Uap1"
 [456] "Uhmk1"      "Nos1ap"     "Atf6"       "Dusp12"     "Fcgr3"
 [461] "Cfap126"    "Sdhc"       "Tomm40l"    "Apoa2"      "Ndufs2"
 [466] "B4galt3"    "Ppox"       "Usp21"      "Ufc1"       "Dedd"
 [471] "Nit1"       "Pfdn2"      "Usf1"       "F11r"       "Alyref2"
 [476] "Slamf1"     "Vangl2"     "Ncstn"      "Copa"       "Pex19"
 [481] "Dcaf8"      "Pea15a"     "Igsf8"      "Pigm"       "Igsf9"
 [486] "Tagln2"     "Cfap45"     "Dusp23"     "Cadm3"      "Fh1"
 [491] "Opn3"       "Chml"       "Exo1"       "Rbm8a2"     "Cep170"
 [496] "Sdccag8"    "Akt3"       "Zbtb18"     "Adss"       "Desi2"
 [501] "Cox20"      "Hnrnpu"     "Efcab2"     "Kif26b"     "Smyd3"
 [506] "Tfb2m"      "Cnst"       "Sccpdh"     "Ahctf1"     "Cdc42bpa"
 [511] "Psen2"      "Stum"       "Parp1"      "Lin9"       "Mixl1"
 [516] "Acbd3"      "H3f3a"      "Sde2"       "Pycr2"      "Nvl"
 [521] "Cnih4"      "Wdr26"      "Lbr"        "Enah"       "Srp9"
 [526] "Degs1"      "Fbxo28"     "Trp53bp2"   "Capn2"      "Susd4"
 [531] "Disp1"      "Brox"       "Aida"       "Mia3"       "Taf1a"
 [536] "Dusp10"     "Hlx"        "Marc1"      "Marc2"      "Mark1"
 [541] "Rab3gap2"   "Iars2"      "Bpnt1"      "Eprs"       "Lyplal1"
 [546] "Tgfb2"      "Rrp15"      "Gpatch2"    "Kctd3"      "Kcnk2"
 [551] "Cenpf"      "Ptpn14"     "Smyd2"      "Prox1"      "Angel2"
 [556] "Vash2"      "Mfsd7b"     "Tatdn3"     "Nsl1"       "Batf3"
 [561] "Atf3"       "Nenf"       "Tmem206"    "Ppp2r5a"    "Dtl"
 [566] "Ints7"      "Lpgat1"     "Nek2"       "Slc30a1"    "Rcor3"
 [571] "Sertad4"    "Syt14"      "Diexf"      "Irf6"       "G0s2"
 [576] "Camk1g"     "Plxna2"     "Cd34"       "Cr1l"       "Fam171a1"
 [581] "Nmt2"       "Rpp38"      "Acbd7"      "Dclre1c"    "Suv39h2"
 [586] "Fam107b"    "Frmd4a"     "Prpf18"     "Bend7"      "Sephs1"
 [591] "Phyh"       "Mcm10"      "Optn"       "Cdc123"     "Nudt5"
 [596] "Sec61a2"    "Upf2"       "Proser2"    "Echdc3"     "Usp6nl"
 [601] "Celf2"      "Gata3"      "Taf3"       "Atp5c1"     "Kin"
 [606] "Itih5"      "Sfmbt2"     "Pfkfb3"     "Rbm17"      "Fbxo18"
 [611] "Ankrd16"    "Fam188a"    "Pter"       "Rsu1"       "Trdmt1"
 [616] "Vim"        "Hacd1"      "Stam"       "Nsun6"      "Arl5b"
 [621] "Plxdc2"     "Skida1"     "Mllt10"     "Dnajc1"     "Commd3"
 [626] "Bmi1"       "Pip4k2a"    "Msrb2"      "Otud1"      "Etl4"
 [631] "Arhgap21"   "Enkur"      "Thnsl1"     "Pdss1"      "Abi1"
 [636] "Acbd5"      "Mastl"      "Yme1l1"     "Spopl"      "Cacna1b"
 [641] "Ehmt1"      "Arrdc1"     "Zmynd19"    "Dph7"       "Mrpl41"
 [646] "Pnpla7"     "Nsmf"       "Nrarp"      "Nelfb"      "Tubb4b"
 [651] "Rnf208"     "Ndor1"      "Tmem203"    "Tprn"       "Ssna1"
 [656] "Anapc2"     "Man1b1"     "Dpp7"       "Uap1l1"     "Sapcd2"
 [661] "Npdc1"      "BC029214"   "C8g"        "Fbxw5"      "Traf2"
 [666] "Edf1"       "Phpt1"      "Rabl6"      "Tmem141"    "Bmyc"
 [671] "Camsap1"    "Ubac1"      "Nacc2"      "Qsox2"      "Gpsm1"
 [676] "Dnlz"       "Snapc4"     "Sdccag3"    "Pmpca"      "Inpp5e"
 [681] "Sec16a"     "Notch1"     "Egfl7"      "Agpat2"     "Fam69b"
 [686] "Surf6"      "Med22"      "Surf1"      "Surf2"      "Surf4"
 [691] "Rexo4"      "Cacfd1"     "Vav2"       "Brd3"       "Wdr5"
 [696] "Rxra"       "Col5a1"     "Olfm1"      "Ppp1r26"    "Mrps2"
 [701] "Ralgds"     "Gtf3c5"     "Gfi1b"      "Tsc1"       "Gtf3c4"
 [706] "Ddx31"      "Ttf1"       "Setx"       "Med27"      "Rapgef1"
 [711] "Trub2"      "Coq4"       "Slc27a4"    "Urm1"       "Cercam"
 [716] "Odf2"       "Gle1"       "Sptan1"     "Wdr34"      "Set"
 [721] "Pkn3"       "Zdhhc12"    "Zer1"       "Tbc1d13"    "Endog"
 [726] "Spout1"     "Kyat1"      "Lrrc8a"     "Dolk"       "Nup188"
 [731] "Sh3glb2"    "Miga2"      "Dolpp1"     "Crat"       "Ptpa"
 [736] "Ier5l"      "Ntmt1"      "Asb6"       "Prrx2"      "Ptges"
 [741] "Tor1b"      "Tor1a"      "BC005624"   "Usp20"      "Fnbp1"
 [746] "Gpr107"     "Ncs1"       "Ass1"       "Fubp3"      "Exosc2"
 [751] "Abl1"       "Aif1l"      "Nup214"     "Plpp7"      "Prrc2b"
 [756] "Pomt1"      "Uck1"       "Swi5"       "Golga2"     "Ciz1"
 [761] "Ptges2"     "Slc25a25"   "Naif1"      "Fam102a"    "Dpm2"
 [766] "St6galnac4" "St6galnac6" "Ak1"        "Eng"        "Fpgs"
 [771] "Cdk9"       "Sh2d3c"     "Tor2a"      "Ptrh1"      "Stxbp1"
 [776] "Fam129b"    "Lrsam1"     "Slc2a8"     "Garnl3"     "Ralgps1"
 [781] "Angptl2"    "Zbtb34"     "Zbtb43"     "Lmx1b"      "Mvb12b"
 [786] "Pbx3"       "Mapkap1"    "Gapvd1"     "Hspa5"      "Rabepk"
 [791] "Fbxw2"      "Psmd5"      "Phf19"      "Cntrl"      "Rab14"
 [796] "Gsn"        "Stom"       "Ggta1"      "Dab2ip"     "Ndufa8"
 [801] "Rbm18"      "Mrrf"       "Ptgs1"      "Pdcl"       "Rc3h2"
 [806] "Zbtb6"      "Zbtb26"     "Rabgap1"    "Strbp"      "Crb2"
 [811] "Dennd1a"    "Lhx2"       "Nek6"       "Psmb7"      "Nr6a1"
 [816] "Arpc5l"     "Golga1"     "Scai"       "Ppp6c"      "Gtdc1"
 [821] "Zeb2"       "Zeb2os"     "Acvr2a"     "Orc4"       "Mbd5"
 [826] "Epc2"       "Kif5c"      "Lypd6b"     "Lypd6"      "Mmadhc"
 [831] "Rnd3"       "Rbm43"      "Nmi"        "Rif1"       "Arl5a"
 [836] "Stam2"      "Fmnl2"      "Prpf40a"    "Arl6ip6"    "Rprm"
 [841] "Gpd2"       "Acvr1"      "Upp2"       "Pkp4"       "Tanc1"
 [846] "Wdsub1"     "Baz2b"      "March7"     "Cd302"      "Ly75"
 [851] "Rbms1"      "Tank"       "Psmd14"     "Dpp4"       "Gca"
 [856] "Kcnh7"      "Fign"       "Grb14"      "Cobll1"     "Csrnp3"
 [861] "Galnt3"     "Ttc21b"     "Stk39"      "Cers6"      "Spc25"
 [866] "Lrp2"       "Bbs5"       "Fastkd1"    "Ppig"       "Ccdc173"
 [871] "Phospho2"   "Klhl23"     "Ssb"        "Mettl5"     "Ubr3"
 [876] "Sp5"        "Erich2"     "Gorasp2"    "Tlk1"       "Mettl8"
 [881] "Dcaf17"     "Dync1i2"    "Slc25a12"   "Hat1"       "Metap1d"
 [886] "Itga6"      "Pdk1"       "Cdca7"      "Sp3"        "Sp3os"
 [891] "Ola1"       "Cir1"       "Scrn3"      "Gpr155"     "Wipf1"
 [896] "Chn1"       "Atf2"       "Atp5g3"     "Hoxd9"      "Haglr"
 [901] "Hoxd1"      "Mtx2"       "Hnrnpa3"    "Nfe2l2"     "Agps"
 [906] "Ttc30a1"    "Rbm45"      "Osbpl6"     "Prkra"      "Fkbp7"
 [911] "Plekha3"    "Sestd1"     "Cwc22"      "Ube2e3"     "Ssfa2"
 [916] "Dnajc10"    "Frzb"       "Nckap1"     "Dusp19"     "Nup35"
 [921] "Zc3h15"     "Itgav"      "Fam171b"    "Tfpi"       "Ctnnd1"
 [926] "Selenoh"    "Tmx2"       "Med19"      "Zdhhc5"     "Clp1"
 [931] "Serping1"   "Ube2l6"     "Timm10"     "Slc43a1"    "Slc43a3"
 [936] "Ssrp1"      "Tnks1bp1"   "Aplnr"      "Nup160"     "Fnbp4"
 [941] "Mtch2"      "C1qtnf4"    "Ndufs3"     "Kbtbd4"     "Celf1"
 [946] "Psmc3"      "Slc39a13"   "Spi1"       "Madd"       "Nr1h3"
 [951] "Acp2"       "Ddb2"       "Pacsin3"    "Arfgap2"    "Lrp4"
 [956] "Ckap5"      "Zfp408"     "Arhgap1"    "Atg13"      "Harbi1"
 [961] "Ambra1"     "Mdk"        "Dgkz"       "Creb3l1"    "Phf21a"
 [966] "Large2"     "Pex16"      "Mapk8ip1"   "Cry2"       "Slc35c1"
 [971] "Chst1"      "Syt13"      "Prdm11"     "Trp53i11"   "Tspan18"
 [976] "Cd82"       "Ext2"       "Alkbh3"     "Hsd17b12"   "Ttc17"
 [981] "Api5"       "Traf6"      "Prr5l"      "Commd9"     "Ldlrad3"
 [986] "Trim44"     "Fjx1"       "Cd44"       "Pdhx"       "Apip"
 [991] "Cat"        "Abtb2"      "Nat10"      "Caprin1"    "Lmo2"
 [996] "Fbxo3"      "Cd59b"      "Cd59a"      "Hipk3"      "Cstf3"

In [31]:

# Subset SingleCellExperiment objects
sce_query  <- sce_query[genes.intersect,]
sce_atlas <- sce_atlas[genes.intersect,]

In [45]:
#######################
## Feature selection ##
#######################

if (args$use_marker_genes) {
  # Load marker genes
  marker_genes.dt <- fread(io$rna.atlas.marker_genes)
  genes_to_use <- genes.intersect[genes.intersect%in%unique(marker_genes.dt$gene)]
} else {
  # Load gene statistics from the atlas
  gene_stats.dt <- fread(paste0(io$atlas.basedir,"/results/gene_statistics/gene_statistics.txt.gz")) %>%
    .[gene%in%genes.intersect]
  genes_to_use <- gene_stats.dt %>% setorder(-var_pseudobulk, na.last = T) %>% head(n=2500) %>% .$gene  
  
  # Calculate mean-variance relationship and extract HVGs
  # decomp <- modelGeneVar(sce_atlas, block=sce_atlas$sample)
  # genes_to_use <- rownames(decomp)[decomp$p.value<=0.01 & decomp$mean>0.1]
}

stopifnot(genes_to_use%in%rownames(sce_atlas))
stopifnot(genes_to_use%in%rownames(sce_query))

In [47]:
head(genes_to_use, 20)

 [1] "Hbb-y"    "Hbb-bh1"  "Ptma"     "Hba-a1"   "Npm1"     "Fth1"
 [7] "Ttr"      "Ftl1"     "Hsp90ab1" "Rbp4"     "Apoa1"    "Ppia"
[13] "Apoe"     "Eef1a1"   "Tpt1"     "Ldha"     "H2afz"    "Hspa8"
[19] "Ubb"      "Actg1"

# MapWrap unpacked

In [48]:
  sce_atlas = sce_atlas
  meta_atlas = meta_atlas
  sce_query = sce_query
  meta_query = meta_query
  genes = genes_to_use
  npcs = args$npcs
  k = args$n_neighbours
  cosineNorm = args$cosine_normalisation
  order = NULL

In [49]:
   
  # Normalisation
  message(sprintf("Normalizing joint dataset using cosineNorm=%s...",cosineNorm))
  sce_all <- joint.normalisation(sce_query, sce_atlas, cosineNorm)
  message("Done\n")

Normalizing joint dataset using cosineNorm=FALSE...

Done

In [50]:
  
  # Feature selection
  if (is.null(genes)) {
    message("Genes not provided. Computing highly variable genes...")
    # hvgs <- getHVGs(sce_all, block=c(meta_atlas$sample, meta_query$sample))
    genes <- getHVGs(sce_all, block=sce_all$block)
    message("Done\n")
  } else {
    message(sprintf("%d Genes provided...",length(genes)))
  }

2500 Genes provided...

In [51]:
  # Dimensionality reduction
  message("Performing PCA...")
  big_pca <- multiBatchPCA(
    sce_all,
    batch = sce_all$block,
    subset.row = genes,
    d = npcs,
    preserve.single = TRUE,
    assay.type = if (cosineNorm) "cosineNorm" else "logcounts"
  )[[1]]
  rownames(big_pca) <- colnames(sce_all) 
  atlas_pca <- big_pca[1:ncol(sce_atlas),]
  query_pca   <- big_pca[-(1:ncol(sce_atlas)),]
  message("Done\n")

Performing PCA...

Done

In [52]:
  
  # Batch effect correction for the atlas
  message("Batch effect correction for the atlas...")  
  order_df        <- meta_atlas[!duplicated(meta_atlas$sample), c("stage", "sample")]
  order_df$ncells <- sapply(order_df$sample, function(x) sum(meta_atlas$sample == x))
  order_df$stage  <- factor(order_df$stage, levels = rev(c("E9.5",
                                       "E9.25",
                                       "E9.0",
                                       "E8.75",
                                       "E8.5",
                                       "E8.25",
                                       "E8.0",
                                       "E7.75",
                                       "E7.5",
                                       "E7.25",
                                       "mixed_gastrulation",
                                       "E7.0",
                                       "E6.75",
                                       "E6.5")))
  order_df       <- order_df[order(order_df$stage, order_df$ncells, decreasing = TRUE),]
  order_df$stage <- as.character(order_df$stage)
  
  set.seed(42)
  pca_atlas_corrected <- doBatchCorrect(counts         = logcounts(sce_atlas[genes,]), 
                                    timepoints      = meta_atlas$stage, 
                                    samples         = meta_atlas$sample, 
                                    timepoint_order = order_df$stage, 
                                    sample_order    = order_df$sample, 
                                    pc_override     = atlas_pca,
                                    npc             = npcs)
  message("Done\n")

Batch effect correction for the atlas...

Loading required package: BiocParallel

Done

In [54]:
  # Mapping query to batch-corrected atlas
  message("MNN mapping...")              
  # correct <- reducedMNN(rbind(pca_atlas_corrected, query_pca), batch = sce_all$block)[["corrected"]]
  correct <- reducedMNN(rbind(pca_atlas_corrected, query_pca),
                      # batch=c(rep("ATLAS", dim(meta_atlas)[1]), meta_query$sample),
                      batch = as.character(sce_all$block),
                      merge.order = order)$corrected
  pca_atlas_corrected <- correct[1:nrow(atlas_pca),]
  pca_query_corrected   <- correct[-(1:nrow(atlas_pca)),]

MNN mapping...

In [56]:
head(pca_query_corrected)
head(pca_atlas_corrected)

                                              [,1]       [,2]     [,3]
SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1 -14.987037 2.413490  24.6406411
SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1  -7.940671 7.905278 -14.2722171
SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1  -8.726419 8.758685  -0.9571918
SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1 -13.366618 3.451749  23.3918650
SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTGATAGTA-1 -15.784547 1.576234  23.8164706
SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTTAAGACA-1  -8.859923 9.763747   2.7037113
                                              [,4]       [,5]
SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1  -3.032402  5.767520
SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1 -16.816031 10.581002
SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1  -8.901286 -1.698947
SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1  -5.954716  0.584606
SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTGATAGTA-1  -1.795425  6.121257
SLX-21143_SITTA2_HTJH3DSX2#AAACGAAGTTAAGACA-1  -5.096928 -4.358171

         [,1]      [,2]      [,3]      [,4]        [,5]
cell_361 -22.18608 -5.858202 -7.477659 13.22464068 -8.494032
cell_362 -12.44580  6.015637  2.600329 -1.15762130  2.156080
cell_363 -10.66507  8.345092  7.358897 -3.35566261  3.066436
cell_364 -10.77508  6.928303  9.191929 -4.99766121 -4.773238
cell_365 -12.98190  5.618987  1.879723  0.01229901  2.966236
cell_366 -10.58148  6.606713  6.264774 -6.22517346 -5.805861

In [59]:
meta_atlas$celltype = meta_atlas$celltype_extended_atlas

In [60]:
  mapping <- get_meta(pca_atlas = pca_atlas_corrected,
                      meta_atlas = meta_atlas,
                      pca_query = pca_query_corrected,
                      meta_query = meta_query,
                      k = k)
  message("Done\n")

Done

In [61]:

  

  


  



  
  # Mapping scores
  message("Computing mapping scores...") 
  out <- list()
  for (i in seq(from = 1, to = k)) {
    out$closest.cells[[i]]     <- sapply(mapping, function(x) x$cells.mapped[i])
    out$celltypes.mapped[[i]]  <- sapply(mapping, function(x) x$celltypes.mapped[i])
    out$cellstages.mapped[[i]] <- sapply(mapping, function(x) x$stages.mapped[i])
  }  
  multinomial.prob <- getMappingScore(out)
  message("Done\n")
  
  # Prepare output
  message("Writing output...") 
  out$pca_atlas_corrected <- pca_atlas_corrected
  out$pca_query_corrected <- pca_query_corrected
  ct <- sapply(mapping, function(x) x$celltype.mapped); is.na(ct) <- lengths(ct) == 0
  st <- sapply(mapping, function(x) x$stage.mapped); is.na(st) <- lengths(st) == 0
  cm <- sapply(mapping, function(x) x$cells.mapped[1]); is.na(cm) <- lengths(cm) == 0
  out$mapping <- data.frame(
      cell            = names(mapping), 
      celltype.mapped = unlist(ct),
      stage.mapped    = unlist(st),
      closest.cell    = unlist(cm))
  
  out$mapping <- cbind(out$mapping,multinomial.prob)
  out$pca <- big_pca
  message("Done\n")
  
  return(out)

Computing mapping scores...

Done


Writing output...

Done

In [62]:
str(out)

List of 7
 $ closest.cells      :List of 25
  ..$ : Named chr [1:1000] "cell_393" "cell_965" "cell_1108" "cell_393" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_592" "cell_711" "cell_1386" "cell_1434" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_398" "cell_1099" "cell_1196" "cell_2671" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_2671" "cell_686" "cell_962" "cell_592" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_539" "cell_2664" "cell_807" "cell_830" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_698" "cell_756" "cell_457" "cell_384" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_761" "cell_1445" "cell_1319" "cell_446" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_519" "cell_1020" "cell_950" "cell_2676" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_484" "cell_909" "cell_410" "cell_846" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_737" "cell_939" "cell_888" "cell_364" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_846" "cell_827" "cell_757" "cell_539" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_1039" "cell_958" "cell_2667" "cell_737" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_498" "cell_679" "cell_996" "cell_1084" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_1434" "cell_1410" "cell_672" "cell_519" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_830" "cell_823" "cell_841" "cell_1281" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_363" "cell_1114" "cell_1251" "cell_498" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_384" "cell_1277" "cell_1048" "cell_957" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_1254" "cell_2678" "cell_1339" "cell_470" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_710" "cell_684" "cell_953" "cell_560" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_716" "cell_532" "cell_759" "cell_877" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_642" "cell_400" "cell_1443" "cell_2672" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_385" "cell_1440" "cell_1208" "cell_604" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_691" "cell_403" "cell_817" "cell_1402" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_1089" "cell_689" "cell_2661" "cell_398" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "cell_896" "cell_1009" "cell_609" "cell_779" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
 $ celltypes.mapped   :List of 25
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Erythroid" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "ExE ectoderm" "Amniotic ectoderm" "Haematoendothelial progenitors" "Erythroid" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Non-neural ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Haematoendothelial progenitors" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Paraxial mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Haematoendothelial progenitors" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Paraxial mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Paraxial mesoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Lateral plate mesoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Paraxial mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "ExE ectoderm" "Mesenchyme" "ExE ectoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "ExE ectoderm" "Mesenchyme" "Paraxial mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Lateral plate mesoderm" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "ExE ectoderm" "Mesenchyme" "Lateral plate mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Haematoendothelial progenitors" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "ExE ectoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Lateral plate mesoderm" "Lateral plate mesoderm" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Epiblast" "Mesenchyme" "Caudal epiblast" "Blood progenitors" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "Blood progenitors" "Mesenchyme" "Haematoendothelial progenitors" "ExE ectoderm" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
 $ cellstages.mapped  :List of 25
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...
  .. ..- attr(*, "names")= chr [1:1000] "SLX-21143_SITTA2_HTJH3DSX2#AAACCCAAGATGTTCC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACCCATCAGACCTA-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACAATGTTGC-1" "SLX-21143_SITTA2_HTJH3DSX2#AAACGAACACACCAGC-1" ...
  ..$ : Named chr [1:1000] "E7.5" "E7.5" "E7.5" "E7.5" ...