In [1]:
library(data.table)

In [2]:
name_conversion = data.frame(input = paste0('SINA', LETTERS[1], '3'), output = paste0('BGRGP', 1))

In [3]:
name_conversion

  input  output
1 SINAA3 BGRGP1

In [4]:
path = '/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/data/raw'

In [7]:
i = 1
frag_list = list()
frag_list$frag_SLX18911 = fread(file.path(path, 'SLX18911', name_conversion[i,1], 'outs/fragments.tsv.gz'))
frag_list$frag_SLX19158 = fread(file.path(path, 'SLX19158', name_conversion[i,1], 'outs/fragments.tsv.gz'))
header = colnames(frag_list$frag_SLX18911)[1]

Warning message in fread(file.path(path, "SLX18911", name_conversion[i, 1], "outs/fragments.tsv.gz")):
“Detected 1 column names but the data has 5 columns (i.e. invalid file). Added 4 extra default column names at the end.”
Warning message in fread(file.path(path, "SLX19158", name_conversion[i, 1], "outs/fragments.tsv.gz")):
“Detected 1 column names but the data has 5 columns (i.e. invalid file). Added 4 extra default column names at the end.”

In [8]:
head(frag_list$frag_SLX18911)

  # primary_contig=X V2 V3  V4                 V5
1 1                   8  96 GCCAGCAGTAACGGTG-1 1
2 1                   8 355 TACCTATCAAGGAGTC-1 1
3 1                  10  38 CCAGAATAGTGATTAG-1 1
4 1                  15  90 ATTGTCTCAGGCAAGT-1 1
5 1                  15  95 CCGAAGCGTTGGTAAA-1 1
6 1                  26  88 TTACCCGTCGGGTCCA-1 2

In [9]:
frag_list_test = list()
frag_list_test$frag_SLX18911 = head(frag_list$frag_SLX18911, 1000)
frag_list_test$frag_SLX19158 = head(frag_list$frag_SLX19158, 1000)

In [34]:
fragment_combined = rbindlist(frag_list)

In [35]:
nrow(fragment_combined)

[1] 453236005

In [36]:
fragment_combined = unique(fragment_combined) # This is assuming that the 5th column 'readSupport' doesn't add information for ArchR

In [37]:
nrow(fragment_combined)

[1] 421077607

In [38]:
out = '/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/data/'
gz = gzfile(paste0(out, name_conversion[i,2], '_fragments.tsv.gz'), 'w')

write.table(fragment_combined, gz, sep='\t', col.names=c(header, '','','',''), quote=FALSE, row.names = FALSE)
close(gz)

In [25]:
library(ArchR)

Loading required package: ggplot2

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:data.table’:

    first, second


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following object is masked from ‘package:data.table’:

    shift


Loading required package: GenomeInfoDb

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians


Loading required package: Matrix


Attaching package: ‘Matrix’


The following object is masked from ‘package:S4Vectors’:

    expand


Loading required package: rhdf5

Loading required package: magrittr

In [27]:
addArchRThreads(threads = 1)

Setting default number of Parallel threads to 1.

In [26]:
addArchRGenome("mm10")

BSgenome for mm10 not installed! Now installing by the following:
	BiocManager::install("BSgenome.Mmusculus.UCSC.mm10")

'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cran.r-project.org


Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.1 (2021-08-10)

Installing package(s) 'BSgenome.Mmusculus.UCSC.mm10'

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Old packages: 'biomaRt', 'carData', 'DropletUtils', 'Gviz', 'HDF5Array',
  'scran', 'textshaping', 'xgboost'

Setting default genome to Mm10.

In [31]:
inputFiles = paste0(out, name_conversion[i,2], '_fragments.tsv.gz')

In [39]:
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = 'TEST1',
  minTSS = 4, #Dont set this too high because you can always increase later
  minFrags = 3000, 
  addTileMat = FALSE,
  addGeneScoreMat = FALSE
)

Using GeneAnnotation set by addArchRGenome(Mm10)!

Using GeneAnnotation set by addArchRGenome(Mm10)!

ArchR logging to : ArchRLogs/ArchR-createArrows-21cc8445c244f-Date-2022-01-07_Time-23-38-17.log
If there is an issue, please report to github with logFile!

Cleaning Temporary Files

2022-01-07 23:38:17 : Batch Execution w/ safelapply!, 0 mins elapsed.

(TEST1 : 1 of 1) Determining Arrow Method to use!

Attempting to index /rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/data/BGRGP1_fragments.tsv.gz as tabix..

createArrowFiles has encountered an error, checking if any ArrowFiles completed..

2022-01-07 23:38:18 :

ArchR logging successful to : ArchRLogs/ArchR-createArrows-21cc8445c244f-Date-2022-01-07_Time-23-38-17.log

In [ ]:
name_conversion = data.frame(input = paste0('SINA', LETTERS[1:8], '3'), output = paste0('BGRGP', 1:8))

###### TEST ######
name_conversion = data.frame(input = paste0('SINA', LETTERS[1], '3'), output = paste0('BGRGP', 1))


for(i in 1:nrow(name_conversion){
path = '/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/data/raw'
frag_list = list()
frag_list$frag_SLX18911 = fread(file.path(path, 'SLX18911', name_conversion[i,1], 'outs/fragments.tsv.gz'))
frag_list$frag_SLX19158 = fread(file.path(path, 'SLX19158', name_conversion[i,1], 'outs/fragments.tsv.gz'))
header = colnames(frag_list$frag_SLX18911)[1]

fragment_combined = rbindlist(frag_list)

out = '/rds/project/rds-SDzz0CATGms/users/bt392/04_Rabbit_ATAC_final/data/'
gz = gzfile(paste0(out, name_conversion[i,2], '_fragments.tsv.gz'), 'w')

write.table(fragment_combined, gz, sep='\t', col.names=c(header, '','','',''), quote=FALSE, row.names = FALSE)
close(gz)

}